#define FW_FILE "/tmp/og4610_fw.img"
//#define FW_UP_CMD "/etc/rc.d/invoke_upgrade.sh /tmp/fullimage.img fullimage 1 saveenv reboot &"
#define FW_UP_CMD "/etc/rc.d/invoke_upgrade.sh "
#define CGI_FILE "/tmp/cgixyz"
#define CGI_FW_UPLOAD "system/system_fw_upgrade.asp"
#define CGI_FW_PREPARE "/sbin/fw_upgrade_prepare.sh"
#define MODULE_FILE "/tmp/mdm_mass_storage/mdm_fw"
