O 1 FW
G 1 1 GLOBAL_GID_802_11H
G 1 2 GLOBAL_GID_802_11_PROTOCOL
G 1 3 GLOBAL_GID_AOCS
G 1 4 GLOBAL_GID_BSS
G 1 5 GLOBAL_GID_RSN
G 1 6 GLOBAL_GID_BSS_MANAGER
G 1 7 GLOBAL_GID_TX
G 1 8 GLOBAL_GID_DATABASE
G 1 9 GLOBAL_GID_SECURITY_DEBRA
G 1 10 GLOBAL_GID_DEBUG_ENVIRONMENT
G 1 11 GLOBAL_GID_DUT
G 1 12 GID_MTIDLPARSER
G 1 13 GLOBAL_GID_RTLOGGER
G 1 14 GID_LOG
G 1 15 GLOBAL_GID_HDK_MODULE
G 1 16 GLOBAL_GID_HOST_IF
G 1 17 GLOBAL_GID_KERNEL
G 1 18 GLOBAL_GID_LOGGER
G 1 19 GLOBAL_GID_LOWER_MAC
G 1 20 GLOBAL_GID_QUEUE_MGMT
G 1 21 GLOBAL_GID_LOWER_MAC_IF
G 1 22 GLOBAL_GID_MAIN
G 1 23 GLOBAL_GID_SYS
G 1 24 GLOBAL_GID_MAINSM
G 1 25 GLOBAL_GID_MEMORY_MGMT
G 1 26 GLOBAL_GID_PERIPHERALS
G 1 27 GLOBAL_GID_SECURITY
G 1 28 GLOBAL_GID_RX
G 1 29 GLOBAL_GID_SECURITY_UNIT_TEST
G 1 30 GLOBAL_GID_UPPER_MAC_INTERFACE
G 1 31 GLOBAL_GID_UTILS
S 1 1 2 111 Assert in file: "MT_RadarDetection.c" in line: 111
S 1 1 2 150 Assert in file: "MT_RadarDetection.c" in line: 150
S 1 1 2 151 Assert in file: "MT_RadarDetection.c" in line: 151
S 1 1 2 235 Assert in file: "MT_RadarDetection.c" in line: 235
S 1 1 2 259 Assert in file: "MT_RadarDetection.c" in line: 259
S 1 1 2 295 Assert in file: "MT_RadarDetection.c" in line: 295
S 1 1 2 431 Assert in file: "MT_RadarDetection.c" in line: 431
S 1 1 2 438 Assert in file: "MT_RadarDetection.c" in line: 438
S 1 1 2 479 Assert in file: "MT_RadarDetection.c" in line: 479
S 1 1 2 485 Assert in file: "MT_RadarDetection.c" in line: 485
S 1 1 2 572 Assert in file: "MT_RadarDetection.c" in line: 572
S 1 1 2 573 Assert in file: "MT_RadarDetection.c" in line: 573
S 1 1 2 586 Assert in file: "MT_RadarDetection.c" in line: 586
S 1 1 2 599 Assert in file: "MT_RadarDetection.c" in line: 599
S 1 1 2 621 Assert in file: "MT_RadarDetection.c" in line: 621
S 1 1 2 672 Assert in file: "MT_RadarDetection.c" in line: 672
S 1 1 2 694 Assert in file: "MT_RadarDetection.c" in line: 694
S 1 1 2 737 Assert in file: "MT_RadarDetection.c" in line: 737
S 1 1 2 778 Assert in file: "MT_RadarDetection.c" in line: 778
S 1 2 1 526 Assert in file: "elements.c" in line: 526
S 1 2 1 1066 Assert in file: "elements.c" in line: 1066
S 1 2 1 1557 Assert in file: "elements.c" in line: 1557
S 1 2 1 1645 Assert in file: "elements.c" in line: 1645
S 1 2 1 2551 Assert in file: "elements.c" in line: 2551
S 1 2 1 2653 Assert in file: "elements.c" in line: 2653
S 1 2 1 2654 Assert in file: "elements.c" in line: 2654
S 1 2 1 2901 EL_UpdateSTBCParmeters()  mask = %x addr = 0X%x%x%x%x%x%x
S 1 2 2 85 Assert in file: "frame.c" in line: 85
S 1 2 3 116 Assert in file: "ieee_address.c" in line: 116
S 1 2 3 140 Assert in file: "ieee_address.c" in line: 140
S 1 2 4 389 Assert in file: "probe_task.c" in line: 389
S 1 3 1 247 Assert in file: "MT_aocs_task.c" in line: 247
S 1 3 1 475 Assert in file: "MT_aocs_task.c" in line: 475
S 1 3 1 590 Fatal Error in file: "MT_aocs_task.c"; Fatal Print: Error unknow state
S 1 4 2 285 Assert in file: "auth_requester_task.c" in line: 285
S 1 4 2 486 Assert in file: "auth_requester_task.c" in line: 486
S 1 4 2 601 Assert in file: "auth_requester_task.c" in line: 601
S 1 4 7 222 vAUTHres_RxAuthenticateMsg u8ResponderState=%d
S 1 4 7 262 vAUTHres_RxAuthenticateMsg : send AUTH_RES with fail status: %d
S 1 4 7 349 Assert in file: "auth_responder_task.c" in line: 349
S 1 4 7 503 Assert in file: "auth_responder_task.c" in line: 503
S 1 4 7 822 Assert in file: "auth_responder_task.c" in line: 822
S 1 4 7 837 Assert in file: "auth_responder_task.c" in line: 837
S 1 4 7 884 Assert in file: "auth_responder_task.c" in line: 884
S 1 4 7 899 Assert in file: "auth_responder_task.c" in line: 899
S 1 4 7 930 Assert in file: "auth_responder_task.c" in line: 930
S 1 4 4 644 Assert in file: "bss_station_task.c" in line: 644
S 1 4 4 1014 Assert in file: "bss_station_task.c" in line: 1014
S 1 4 4 1058 Assert in file: "bss_station_task.c" in line: 1058
S 1 4 4 1225 vSTA_DisAssociate, Num DisAssoc Req - %d, VAP ID - %d
S 1 4 4 1250 vSTA_DisAssociate, Send Failed, Num DisAssoc Req - %d
S 1 4 4 1255 vSTA_DisAssociate, Send DisAssoc, STA - %d
S 1 4 4 1269 vSTA_DisAssociate:sid=%d bPostponeDelete = TRUE 
S 1 4 4 1274 Assert in file: "bss_station_task.c" in line: 1274
S 1 4 4 1365 Assert in file: "bss_station_task.c" in line: 1365
S 1 4 4 1377 Assert in file: "bss_station_task.c" in line: 1377
S 1 4 4 1516 vSTA_TxCallbackDisAssoc, Num DisAssoc Req - %d
S 1 4 4 1525 vSTA_TxCallbackDisAssoc, Remove STA - %d
S 1 4 4 1544 Assert in file: "bss_station_task.c" in line: 1544
S 1 4 4 1547 vSTA_TxCallbackDisAssoc, call pending , SID - %d
S 1 4 4 1588 vSTA_ConnectionEventResponse - Get Pending Indication
S 1 4 4 1670 Assert in file: "bss_station_task.c" in line: 1670
S 1 4 4 1674 vSTA_ReportDisconnection: SID=%d, state=%d, poseponeDelete=%d, reason=%d, dropReason=%d
S 1 4 4 1778 Assert in file: "bss_station_task.c" in line: 1778
S 1 4 4 1816 vSTA_ReportConnectionEvent - SID = %d, State - %d, ConnState = %d, Reason = %d, Failreason = %d
S 1 4 4 1824 Assert in file: "bss_station_task.c" in line: 1824
S 1 4 4 1866 Assert in file: "bss_station_task.c" in line: 1866
S 1 4 4 1869 vSTA_ReportConnectionEvent - Put Pending Indication, SID = %d
S 1 4 4 2009 vSTA_SendConnectionIndication
S 1 4 4 2075 vSTA_ReportAuthEvent - Put Pending Indication, State = %d, Reason = %d, Failreason = %d
S 1 4 4 2090 Assert in file: "bss_station_task.c" in line: 2090
S 1 4 4 2095 vSTA_ReportAuthEvent
S 1 4 4 2157 Assert in file: "bss_station_task.c" in line: 2157
S 1 4 4 2200 Assert in file: "bss_station_task.c" in line: 2200
S 1 4 4 2203 vSTA_TxAssocResponseCb, call pending , SID - %d
S 1 4 4 2257 Assert in file: "bss_station_task.c" in line: 2257
S 1 4 4 2258 Assert in file: "bss_station_task.c" in line: 2258
S 1 4 4 2275 vSTA_RxManActionInd, received ADDBA_REQ_ACTION from sid %d, tid:%d
S 1 4 4 2284 vSTA_RxManActionInd, received ADDBA_RES_ACTION from sid %d
S 1 4 4 2295 vSTA_RxManActionInd, received DELBA_ACTION from sid %d, tid:%d
S 1 4 4 2302 Assert in file: "bss_station_task.c" in line: 2302
S 1 4 4 2363 -- vSTA_RxManActionInd, management action frame not recognized ---
S 1 4 4 2416 Assert in file: "bss_station_task.c" in line: 2416
S 1 4 4 2422 Assert in file: "bss_station_task.c" in line: 2422
S 1 4 4 2428 Assert in file: "bss_station_task.c" in line: 2428
S 1 4 4 2477 vSTA_SendAssocReply, add pending , SID - %d
S 1 4 4 2529 vSTA_SendAssocReply, u16FmCapabilityInformation:%x, u16FmStatusCode:%d, u16FmSid:%x
S 1 4 4 2544 Assert in file: "bss_station_task.c" in line: 2544
S 1 4 4 2566 vSTA_SendDisAssocReq, STA pending - SID %d
S 1 4 4 2574 vSTA_SendDisAssocReq, Add STA to Pending - SID %d
S 1 4 4 2580 vSTA_SendDisAssocReq, send PKT_DISASSOC_REQUEST, u16ReasonCode:%d
S 1 4 4 2582 Assert in file: "bss_station_task.c" in line: 2582
S 1 4 4 2608 Assert in file: "bss_station_task.c" in line: 2608
S 1 4 4 2627 vSTA_DisconnectSingleSTA:SID=%d txCount=%d 
S 1 4 4 2648 vSTA_DisconnectSingleSTA:%d, bPostponeConnect:%d, u16DBstate:%d, bPeerDisconnected:%d, bPeerAP:%d
S 1 4 4 2705 vSTA_DisconnectSingleSTA:sid=%d bPostponeDelete = TRUE 
S 1 4 4 2731 vSTA_DisconnectReq: address %Y
S 1 4 4 2778 Assert in file: "bss_station_task.c" in line: 2778
S 1 4 4 2808 vSTA_DisconnectReq:sid=%d bPostponeDelete = TRUE 
S 1 4 4 2821 vSTA_DisconnectReq: SID=%d bPostponeDelete,u8TxCount=%d
S 1 4 4 2855 vSTA_PostponedDisconnect:SendDisAssocReq SID=%d  
S 1 4 4 2887 vSTA_PostponedDisconnect:vSTA_RemoveStation SID=%d  
S 1 4 4 2915 Assert in file: "bss_station_task.c" in line: 2915
S 1 4 4 2940 vSTA_RemoveStation:SID=%d
S 1 4 4 2960 Assert in file: "bss_station_task.c" in line: 2960
S 1 4 4 2963 Assert in file: "bss_station_task.c" in line: 2963
S 1 4 4 2976 vSTA_RemoveStation send RX_AUTHENTICATE
S 1 4 4 3001 Assert in file: "bss_station_task.c" in line: 3001
S 1 4 5 245 BGScan_RestoreNetParams: psPS_NET_PARAMS: mixedNetwork11g %d, workingChannel %d, switchMode %d
S 1 4 5 276 PS_ON_ReqHandler: u8BSSmanState: %d, PS_State = %d, workingChannel: %d, switchMode %d, mixedNetwork11g: %d
S 1 4 5 327 vPS_OFF_ReqHandler: PS_State = %d
S 1 4 5 419 BGScan_CallBack: PS_State = %d
S 1 4 5 441 Assert in file: "MT_bgscan_task.c" in line: 441
S 1 4 5 462 BGScan_HandleStopOnlineCalibrationCfm: online calibration stopped, do pause tx
S 1 4 5 524 BGScan_ResumeNetwork: psPS_NET_PARAMS.PS_State %d
S 1 4 5 560 vBGScan_HandlePauseTxCfm: psPS_NET_PARAMS.PS_State: %d
S 1 4 5 561 Assert in file: "MT_bgscan_task.c" in line: 561
S 1 4 5 582 Assert in file: "MT_bgscan_task.c" in line: 582
S 1 4 6 362 Assert in file: "mt_powersave.c" in line: 362
S 1 4 6 580 psStaExitPs SID=%d prio=%d after Proc=%d pending PS=%d pending=%d
S 1 4 6 583 Assert in file: "mt_powersave.c" in line: 583
S 1 4 6 665 Assert in file: "mt_powersave.c" in line: 665
S 1 4 6 675 PS_TxQueueRxPsPoll: send packet in response to ps-poll
S 1 4 6 719 Assert in file: "mt_powersave.c" in line: 719
S 1 4 6 1035 Assert in file: "mt_powersave.c" in line: 1035
S 1 4 6 1407 Assert in file: "mt_powersave.c" in line: 1407
S 1 4 6 1450 Assert in file: "mt_powersave.c" in line: 1450
S 1 4 6 1509 Assert in file: "mt_powersave.c" in line: 1509
S 1 4 6 1510 Assert in file: "mt_powersave.c" in line: 1510
S 1 4 6 1538 Assert in file: "mt_powersave.c" in line: 1538
S 1 4 6 1625 Assert in file: "mt_powersave.c" in line: 1625
S 1 4 6 1627 Assert in file: "mt_powersave.c" in line: 1627
S 1 4 6 1724 psEnterPs SID=%d prio=%d after Proc=%d pending PS=%d pending=%d
S 1 4 6 1728 Assert in file: "mt_powersave.c" in line: 1728
S 1 4 6 1810 psStartUSP: send packet in USP!  AC == : %x
S 1 4 6 1829 Assert in file: "mt_powersave.c" in line: 1829
S 1 4 6 1846 psStartUSP: send packet in USP from Aggregation!  AC == : %x
S 1 4 6 1864 psStartUSP: pri == 0xFF, USP ended!  pri ==  %x
S 1 4 6 1867 Assert in file: "mt_powersave.c" in line: 1867
S 1 4 6 1871 psStartUSP: Trying to send Null data packet on AC== %x  :) 
S 1 4 6 1876 psStartUSP: Null Data Packet sent!   :) 
S 1 4 6 1880 psStartUSP: No resorces for Null Data Pckt - unserviced USP  :( 
S 1 4 6 1889 psStartUSP: Service period is ended, sent frames == %x
S 1 4 6 2115 Assert in file: "mt_powersave.c" in line: 2115
S 1 4 6 2117 Assert in file: "mt_powersave.c" in line: 2117
S 1 4 6 2127 Assert in file: "mt_powersave.c" in line: 2127
S 1 4 6 2136 psStartUSP: Queued Null Data Packet sent!   :) 
S 1 5 7 319 PMF_checkProtectionOfRobustManagementFramesRx discardFrame:%d, u16TypeAndSubtype:%d, myMfpc:%d, myMfpr:%d, peerMfpc:%d
S 1 5 7 361 PMF_updateIsPmfNegotiated, isPmfNegotiated: %d
S 1 5 7 468 Assert in file: "pmf.c" in line: 468
S 1 5 7 474 PMF_startTimer, sid:%d, tsfStartOfSAQueryProcedure:%u
S 1 5 7 480 PMF_startTimer: adding sid:%d to pmfSaqueryActiveStaQueue and setting PMF_SAQUERY_PROCEDURE_ACTIVE
S 1 5 7 601 Assert in file: "pmf.c" in line: 601
S 1 5 7 630 PMF dot11AssociationSAQueryRetryTimeout:%d
S 1 5 7 672 PMF_checkSAQueryTimeout, tsfStartOfSAQueryProcedure:%u, currentTsfTime:%u, overAllSAQueryPassedTime:%u, max retries:%u
S 1 5 7 757 Assert in file: "pmf.c" in line: 757
S 1 5 7 760 PMF_handleSAQueryTimeout, currentTsfTime:%u, numEntries:%d
S 1 5 7 770 PMF_handleSAQueryTimeout, check if this STA was timed out ,poppedSid:%d queuedTimestamp:%u, sTIM.u32TSFtimerLow:%u
S 1 5 7 776 Assert in file: "pmf.c" in line: 776
S 1 5 7 791 PMF_handleSAQueryTimeout, reporting disconnection due to max timeout, sid:%d, tsf:%u
S 1 5 7 801 time not passed max timeout, return to queue
S 1 5 7 809 time not passed retry timeout, return to queue
S 1 5 7 818 PMF_handleSAQueryTimeout, OSQEntries:%d
S 1 5 7 848 PMF_sendSaquery SA_QUERY_REQUEST
S 1 5 7 863 Assert in file: "pmf.c" in line: 863
S 1 5 7 884 PMF_sendSaquery SA_QUERY_RESPONSE
S 1 5 7 898 Assert in file: "pmf.c" in line: 898
S 1 5 7 940 Assert in file: "pmf.c" in line: 940
S 1 5 7 960 Assert in file: "pmf.c" in line: 960
S 1 5 7 972 Assert in file: "pmf.c" in line: 972
S 1 5 7 1059 PMF_stopSaquery calling PMF_stopTimer 
S 1 5 7 1087 Assert in file: "pmf.c" in line: 1087
S 1 5 7 1090 PMF_handleRxSaqueryRes, flags:%x
S 1 5 7 1110 PMF_handleRxSaqueryRes: got unexpected SaqueryRes from sid:%d
S 1 5 7 1129 isRxPmfProtected, isStaInActiveSAQueryProcedure == TRUE
S 1 5 7 1153 PMF_handleRxProtectedFrame, calling PMF_stopSaquery 
S 1 5 7 1180 got SA_QUERY_REQUEST
S 1 5 7 1188 got SA_QUERY_RESPONSE
S 1 5 7 1193 got action frame SA_QUERY_CATEGORY with unexpected action code:%d !!!
S 1 5 7 1221 PMF_txSaqueryCb called
S 1 5 7 1247 PMF_txSaqueryCb -> PMF_startTimer
S 1 5 7 1261 Assert in file: "pmf.c" in line: 1261
S 1 5 7 1278 Assert in file: "pmf.c" in line: 1278
S 1 5 7 1287 Assert in file: "pmf.c" in line: 1287
S 1 5 7 1332 PMF_handleAssocReq: assoc req while STA is already associated, flags:%x
S 1 6 1 249 BSSmanager_RemoveVapReq, vapId:%d
S 1 6 1 307 PreTbtt, Number of FSDU in DeferActive before[%d]: %d
S 1 6 1 327 PreTbtt, Number of FSDU in DeferActive[%d]: %d
S 1 6 1 334 PreTbtt Qswitch to VAP index:%d
S 1 6 1 348 PreTbtt, MpsMsduScheduled[%d]: %X
S 1 6 1 450 Assert in file: "BSSmanager_API.c" in line: 450
S 1 6 1 627 Assert in file: "BSSmanager_API.c" in line: 627
S 1 6 1 662 SetMpsQueueSize, MpsSize[%d]: %d
S 1 6 3 239 Assert in file: "BSSmanager_BeaconSM.c" in line: 239
S 1 6 3 241 Assert in file: "BSSmanager_BeaconSM.c" in line: 241
S 1 6 3 660 Assert in file: "BSSmanager_BeaconSM.c" in line: 660
S 1 6 3 664 Assert in file: "BSSmanager_BeaconSM.c" in line: 664
S 1 6 3 693 Assert in file: "BSSmanager_BeaconSM.c" in line: 693
S 1 6 3 763 Assert in file: "BSSmanager_BeaconSM.c" in line: 763
S 1 6 3 765 Assert in file: "BSSmanager_BeaconSM.c" in line: 765
S 1 6 3 819 Assert in file: "BSSmanager_BeaconSM.c" in line: 819
S 1 6 3 821 Assert in file: "BSSmanager_BeaconSM.c" in line: 821
S 1 6 3 863 Fatal Error in file: "BSSmanager_BeaconSM.c"; Fatal Print: invalid state/event
S 1 6 3 925 Fatal Error in file: "BSSmanager_BeaconSM.c"; Fatal Print: invalid state/event
S 1 6 3 977 Fatal Error in file: "BSSmanager_BeaconSM.c"; Fatal Print: invalid state/event
S 1 6 3 1012 Assert in file: "BSSmanager_BeaconSM.c" in line: 1012
S 1 6 3 1053 Assert in file: "BSSmanager_BeaconSM.c" in line: 1053
S 1 6 3 1151 UpdateMpsFlag[%d]:%d
S 1 6 3 1198 UpdateDtimCout[%d], DtimCount: %d, isDtimPeriodBitMap: %d,	isMPSactive: %d, isMpsEmpty: %X
S 1 6 3 1222 UpdateDtimCout, InsertEvnet[%d]: NSE_BCN_CP
S 1 6 3 1232 UpdateDtimCout, lastMpsConfiguredIndxMask: %d, isMpsActivs: %d
S 1 6 3 1239 UpdateDtimCout, InsertEvetn:%d
S 1 6 3 1260 UpdateDtimCout, InsertEvnet[%d]: NSE_DTIM_END
S 1 6 3 1311 Assert in file: "BSSmanager_BeaconSM.c" in line: 1311
S 1 6 3 1360 Assert in file: "BSSmanager_BeaconSM.c" in line: 1360
S 1 6 4 150 Assert in file: "BSSmanager_VapSM.c" in line: 150
S 1 6 4 163 Assert in file: "BSSmanager_VapSM.c" in line: 163
S 1 6 4 182 Assert in file: "BSSmanager_VapSM.c" in line: 182
S 1 6 4 198 Assert in file: "BSSmanager_VapSM.c" in line: 198
S 1 6 4 203 Assert in file: "BSSmanager_VapSM.c" in line: 203
S 1 6 4 628 Assert in file: "BSSmanager_VapSM.c" in line: 628
S 1 6 4 695 disconnectStaFromVap:sid=%d bPostponeDelete = TRUE 
S 1 6 4 912 Assert in file: "BSSmanager_VapSM.c" in line: 912
S 1 6 4 1298 Assert in file: "BSSmanager_VapSM.c" in line: 1298
S 1 6 4 1516 Assert in file: "BSSmanager_VapSM.c" in line: 1516
S 1 6 4 1539 Assert in file: "BSSmanager_VapSM.c" in line: 1539
S 1 6 5 72 Assert in file: "BSSmanager_BeaconSMinterface.c" in line: 72
S 1 4 8 209 CoC_UMreqChangePowerState  stopOnlineCalib = %d   CbTransmitPowerLimit = %d  nCbTransmitPowerLimit = %d returnTask = %d
S 1 4 8 244 Assert in file: "CoC.c" in line: 244
S 1 4 8 371 CoC_changePowerStateReqHandler  NewTxNum = %d	NewRxNum = %d  CbTransmitPowerLimit = %d  nCbTransmitPowerLimit = %d stopOnlineCalib =%d
S 1 4 8 387 Assert in file: "CoC.c" in line: 387
S 1 4 8 426 CoC_storeUMstate rateMasksStored = %d
S 1 4 8 450 CoC_restoreUMstate()
S 1 4 8 548 CoC_stopOnlineCalibCfmHandler requestedRxNum = %d requestedTxNum = %d
S 1 4 8 570 CoC_TxPauseCfmHandler  requestedRxNum = %d requestedTxNum = %d returnTask = %d sendCfmToDriver = %d
S 1 4 8 619 Assert in file: "CoC.c" in line: 619
S 1 8 1 215 Assert in file: "database.c" in line: 215
S 1 8 1 598 add STA to VAP
S 1 8 1 610 ADDR = %d pointer = %d
S 1 8 1 630 ERROR! psDB_AddStationToVap: database full
S 1 8 1 694 Assert in file: "database.c" in line: 694
S 1 8 1 860 Assert in file: "database.c" in line: 860
S 1 8 1 866 Assert in file: "database.c" in line: 866
S 1 8 1 889 u16DB_RemoveStation SID=%d
S 1 8 1 912 Assert in file: "database.c" in line: 912
S 1 8 1 930 Assert in file: "database.c" in line: 930
S 1 8 1 971 Assert in file: "database.c" in line: 971
S 1 8 1 981 Assert in file: "database.c" in line: 981
S 1 8 1 1020 Assert in file: "database.c" in line: 1020
S 1 8 1 1060 u16DB_RemoveStation:u16CurrentSID=%d set to DBS_FREE 
S 1 8 1 1066 Assert in file: "database.c" in line: 1066
S 1 8 1 1073 Assert in file: "database.c" in line: 1073
S 1 8 1 1093 Assert in file: "database.c" in line: 1093
S 1 8 1 1111 Assert in file: "database.c" in line: 1111
S 1 8 1 1131 Assert in file: "database.c" in line: 1131
S 1 8 1 1189 Assert in file: "database.c" in line: 1189
S 1 8 1 1536 Assert in file: "database.c" in line: 1536
S 1 8 1 1930 vDB_SetPreamble: SID=%d, old common mask=0x%x, new common mask=0x%x, rate mask=0x%x, min rate=%d, max rate = %d, data rate=%d
S 1 8 1 1981 vDB_SetPreamble: SID=%d, old common mask=0x%x, new common mask=0x%x, rate mask=0x%x, min rate=%d, max rate = %d, data rate=%d
S 1 8 1 2085 Assert in file: "database.c" in line: 2085
S 1 8 1 2162 Assert in file: "database.c" in line: 2162
S 1 8 1 2195 DB_setStationNewState: SID=%d, old State=%d, new State=%d, smEvent=%d, newState=%d
S 1 8 1 2378 DB_HandleAuthTimeout, removing station, currentTS:%u, authTS:%u, lifeTime:%u, staId:%d
S 1 8 1 2396 DB_HandleAuthTimeout, still items in pending assoc queue, restarting timer
S 1 8 1 2423 DB_updatePendingForAssociationQ, add STA to pendingForAssoc Queue
S 1 8 1 2446 DB_updatePendingForAssociationQ, STA still in pending for Assoc queue, and trying to auth again !
S 1 8 1 2466 DB_removeStaFromPendingAssoc queue
S 1 8 1 2476 DB_removeStaFromPendingAssocQ, pendingForAssoc queue is empty, reset timer
S 1 8 2 349 Assert in file: "mib.c" in line: 349
S 1 8 2 677 Assert in file: "mib.c" in line: 677
S 1 8 2 717 u16MIB_PutValue: u16ID=%d 
S 1 8 2 722 PMF, mib ID=%d , val:%d
S 1 8 2 774 Assert in file: "mib.c" in line: 774
S 1 9 1 296 Assert in file: "Debra.c" in line: 296
S 1 9 1 318 Assert in file: "Debra.c" in line: 318
S 1 10 4 104 Assert in file: "msdu_timing.c" in line: 104
S 1 10 4 105 Assert in file: "msdu_timing.c" in line: 105
S 1 10 4 114 Assert in file: "msdu_timing.c" in line: 114
S 1 10 4 143 Assert in file: "msdu_timing.c" in line: 143
S 1 10 4 173 Assert in file: "msdu_timing.c" in line: 173
S 1 10 5 44 Assert in file: "MT_agg_fsdu_timing.c" in line: 44
S 1 10 5 61 Assert in file: "MT_agg_fsdu_timing.c" in line: 61
S 1 10 5 62 Assert in file: "MT_agg_fsdu_timing.c" in line: 62
S 1 10 2 89 Assert in file: "mt_event_logger.c" in line: 89
S 1 10 1 48 Assert in file: "MT_mips_control.c" in line: 48
S 1 10 1 72 Fatal Error in file: "MT_mips_control.c"; Fatal Print: Assert Requested by the Host
S 1 10 6 57 Assert in file: "MT_Msdu_Timing.c" in line: 57
S 1 10 6 60 Assert in file: "MT_Msdu_Timing.c" in line: 60
S 1 10 6 105 Assert in file: "MT_Msdu_Timing.c" in line: 105
S 1 10 6 131 Assert in file: "MT_Msdu_Timing.c" in line: 131
S 1 10 6 173 Assert in file: "MT_Msdu_Timing.c" in line: 173
S 1 10 7 226 Assert in file: "mt_phy_statisctics.c" in line: 226
S 1 10 7 574 Assert in file: "mt_phy_statisctics.c" in line: 574
S 1 10 7 723 Assert in file: "mt_phy_statisctics.c" in line: 723
S 1 10 7 803 Assert in file: "mt_phy_statisctics.c" in line: 803
S 1 10 7 839 Assert in file: "mt_phy_statisctics.c" in line: 839
S 1 10 7 1003 Assert in file: "mt_phy_statisctics.c" in line: 1003
S 1 10 7 1018 Assert in file: "mt_phy_statisctics.c" in line: 1018
S 1 10 7 1050 Assert in file: "mt_phy_statisctics.c" in line: 1050
S 1 10 7 1061 Assert in file: "mt_phy_statisctics.c" in line: 1061
S 1 10 7 1101 Assert in file: "mt_phy_statisctics.c" in line: 1101
S 1 10 8 68 Assert in file: "timing_stats.c" in line: 68
S 1 10 8 91 Assert in file: "timing_stats.c" in line: 91
S 1 10 8 110 Assert in file: "timing_stats.c" in line: 110
S 1 10 8 111 Assert in file: "timing_stats.c" in line: 111
S 1 10 8 134 Assert in file: "timing_stats.c" in line: 134
S 1 10 8 135 Assert in file: "timing_stats.c" in line: 135
S 1 10 8 184 Assert in file: "timing_stats.c" in line: 184
S 1 10 8 185 Assert in file: "timing_stats.c" in line: 185
S 1 10 8 186 Assert in file: "timing_stats.c" in line: 186
S 1 11 1 176 dutDispatcher Recived message with ID = 0x%X
S 1 11 1 180 Assert in file: "Dut.c" in line: 180
S 1 11 1 197 Assert in file: "Dut.c" in line: 197
S 1 11 4 141 DutHwAccess_Dispatcher Recieved Message with ID = 0x%X
S 1 11 4 229 Assert in file: "Dut_HwAccess.c" in line: 229
S 1 11 4 506 Assert in file: "Dut_HwAccess.c" in line: 506
S 1 11 4 686 Assert in file: "Dut_HwAccess.c" in line: 686
S 1 11 4 700 Assert in file: "Dut_HwAccess.c" in line: 700
S 1 11 4 721 Assert in file: "Dut_HwAccess.c" in line: 721
S 1 11 4 735 Assert in file: "Dut_HwAccess.c" in line: 735
S 1 11 4 756 Assert in file: "Dut_HwAccess.c" in line: 756
S 1 11 2 150 Assert in file: "Dut_Managment.c" in line: 150
S 1 11 3 121 Assert in file: "Dut_Tx.c" in line: 121
S 1 11 3 196 Assert in file: "Dut_Tx.c" in line: 196
S 1 11 3 223 Assert in file: "Dut_Tx.c" in line: 223
S 1 11 3 237 Assert in file: "Dut_Tx.c" in line: 237
S 1 12 1 48 Failed to open directory \"%s\"
S 1 12 1 92 Failed to load MTIDL file \"%s\"
S 1 12 1 134 Invalid MTIDL file \"%s\"
S 1 12 1 205 Invalid MTIDL file section \"%s\"
S 1 12 1 294 Failed to traverse binary type %s, error %d
S 1 12 1 374 Failed to load MTIDL file \"%s\"
S 1 13 1 107 Assert in file: "logdefs.h" in line: 107
S 1 15 31 523 START AFE CALIBRATION
S 1 15 31 551 retVal=%d, packetMod=%d
S 1 15 31 555 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 15 31 558 exit ALB mode, calibration end!
S 1 15 31 565 LastClRunTime: %d
S 1 15 31 625 QBF calibration finished
S 1 15 31 768 Assert in file: "BeamFormingClbrHndlr.c" in line: 768
S 1 15 31 783 Send packet %d => %d
S 1 15 31 799 Packet sent from ant %d to ant %d
S 1 15 31 817 BM calibration fail! number of recorded bins from sessions not identical
S 1 15 31 841 StopRisc called
S 1 15 31 878 Assert in file: "BeamFormingClbrHndlr.c" in line: 878
S 1 15 31 888 StartRisc called
S 1 15 31 949 Short1: %X
S 1 15 31 950 Short2: %X
S 1 15 31 997 Assert in file: "BeamFormingClbrHndlr.c" in line: 997
S 1 15 31 1021 Assert in file: "BeamFormingClbrHndlr.c" in line: 1021
S 1 15 31 1069 Registers values were not saved, cannot restore them
S 1 15 31 1070 Assert in file: "BeamFormingClbrHndlr.c" in line: 1070
S 1 15 31 1074 Stop risc
S 1 15 31 1090 Run risc
S 1 15 31 1136 Assert in file: "BeamFormingClbrHndlr.c" in line: 1136
S 1 15 31 1185 BF Calibration Failed!! could not achieve a good channel
S 1 15 31 1201 triggerTB
S 1 15 31 1263 Record Channel Failed !! packet did not arrive in time
S 1 15 31 1275 Record Channel Failed!! wrong channel size, CB: %d, numOfBins:%d
S 1 15 31 1286 Record Channel Failed!! Wrong Packet received with length %d
S 1 15 31 1300 Record channel failed!!! CRC error
S 1 15 31 1351 Assert in file: "BeamFormingClbrHndlr.c" in line: 1351
S 1 15 31 1357 Record %d bins
S 1 15 31 1505 CaluclateCalResult, calPair=%d
S 1 15 31 1507 Assert in file: "BeamFormingClbrHndlr.c" in line: 1507
S 1 15 31 1569 NCB mode: Start checking phase jump
S 1 15 31 1578 PhaseDiff = %d
S 1 15 31 1587 Phase jump found! correcting K calibration
S 1 15 31 1612 Phase jump not found
S 1 15 31 1698 Assert in file: "BeamFormingClbrHndlr.c" in line: 1698
S 1 15 31 1768 Assert in file: "BeamFormingClbrHndlr.c" in line: 1768
S 1 15 31 1784 START AGC GAINS CALIBRATION
S 1 15 31 1795 START K CALIBRATION
S 1 15 31 1805 START AGC OFFSET CALIBRATION
S 1 15 31 1814 START TX OFFSET CALIBRATION
S 1 15 31 1821 exit ALB mode, calibration end!, calStatus = %X
S 1 15 31 1851 Start K%d calibration, CB=%d
S 1 15 31 1911 Assert in file: "BeamFormingClbrHndlr.c" in line: 1911
S 1 15 31 1926 Warning: working at %d instead of 15 dB backoff
S 1 15 31 1933 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 15 31 1960 Send packet: Ant%d->Ant%d
S 1 15 31 2134 Assert in file: "BeamFormingClbrHndlr.c" in line: 2134
S 1 15 31 2335 avgPower=%d,  avgPowerDb=%d, gainCorrection=%d
S 1 15 31 2351 ramGainVal: %X
S 1 15 31 2431 Assert in file: "BeamFormingClbrHndlr.c" in line: 2431
S 1 15 31 2522 phaseValWriteToRam: %X
S 1 15 31 2523 phaseAddr: %X
S 1 15 31 2616 Assert in file: "BeamFormingClbrHndlr.c" in line: 2616
S 1 15 31 2666 BF Calibration Failed!! could not achieve a good channel
S 1 15 31 2691 DisTxCancel
S 1 15 31 2698 EnTxCancel
S 1 15 3 196 LPF: Executing Calibration.
S 1 15 3 209 LPF: Finished Calibration. Ret Val = %d, Run Time = %d
S 1 15 3 236 LPF_LoadResults(): Ant %u lpfI=%u lpfQ=%u
S 1 15 30 123 Assert in file: "LpfClbrUtils.c" in line: 123
S 1 15 27 139 MsSsiAdc: Executing Calibration
S 1 15 27 476 MsSsiAdc verifyCalibrationResults: antNum = %d Status = %d
S 1 15 27 477 MsSsiAdc verifyCalibrationResults: statusGain = %d gainDist = %d
S 1 15 27 478 MsSsiAdc verifyCalibrationResults: statusOffset = %d offsetDist = %d
S 1 15 27 516 MsSsiAdc: Finished Calibration. Ret Code = 0x%x, Run Time = %d
S 1 15 27 524 MsSsiAdc: AntNum = %d
S 1 15 27 529 MsSsiAdc: status = %d, statusGain = %d, statusOffset = %d
S 1 15 27 530 MsSsiAdc: gain = %d, offset = %d
S 1 15 27 531 MsSsiAdc: dataOutGain = %d, dataOutOffset = %d
S 1 15 28 112 RficBias: Executing Calibration
S 1 15 28 144 RficBias: status = %d, statusRpos = %d, statusRneg = %d
S 1 15 28 145 RficBias: Rint = %d Rpos = %d, Rneg = %d
S 1 15 28 157 RficBias: Finished Calibration. Run Time = %d
S 1 15 28 217 RficBias_calibrateRpos:Failed to reach comparator SUCCESS
S 1 15 28 278 RficBias_calibrateRneg:Failed to reach comparator SUCCESS
S 1 15 28 395 RficBias_LoadResults(): Rint=%d
S 1 15 28 432 RficBias_StoreResults(): Rint=%d
S 1 15 26 130 RssiDcOffset: Executing Calibration
S 1 15 26 351 RssiDcOffset min_search !!! DEBUG !!!: delta=0: antenna %d
S 1 15 26 447 RssiDcOffset: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 15 26 455 RssiDcOffset: AntNum = %d Status = %d
S 1 15 26 463 RssiDcOffset OFFSETS: I1 = %d I2 = %d I3 = %d
S 1 15 26 464 RssiDcOffset OFFSETS: I4 = %d I5 = %d
S 1 15 26 465 RssiDcOffset OFFSETS: Q1 = %d Q2 = %d Q3 = %d
S 1 15 26 466 RssiDcOffset OFFSETS: Q4 = %d Q5 = %d
S 1 15 26 474 RssiDcOffset DATA OUT OFFSETS: I1 = %d I2 = %d I3 = %d
S 1 15 26 475 RssiDcOffset DATA OUT OFFSETS: I4 = %d I5 = %d
S 1 15 26 476 RssiDcOffset DATA OUT OFFSETS: Q1 = %d Q2 = %d Q3 = %d
S 1 15 26 477 RssiDcOffset DATA OUT OFFSETS: Q4 = %d Q5 = %d
S 1 15 26 592 RssiDcOffset_LoadResults(): Ant %d Stage %d offset=%d
S 1 15 26 642 RssiDcOffset_StoreResults(): Ant %u Stage %u offset=%u
S 1 15 4 240 RSSI Path: Executing Calibration
S 1 15 4 270 RSSI Path Calibration:Antenna %d status %d
S 1 15 4 287 RSSI Path Calibration:Finished Calibration. ret = %d, Run Time = %d
S 1 15 4 327 RSSI Path calibrateSingleAntenna(): Antenna %d
S 1 15 4 340 Assert in file: "RssiPathClbrHndlr.c" in line: 340
S 1 15 4 363 RSSI Path calibrateSingleAntenna:Rssi = %d
S 1 15 4 402 RSSI Path calibrateSingleAntenna():Index = %d,Rssi = %d
S 1 15 4 427 RSSI Path calibrateSingleAntenna:Partitioned Section =%d Index = %d,Rssi = %d
S 1 15 4 586 Assert in file: "RssiPathClbrHndlr.c" in line: 586
S 1 15 4 630 RSSI Path measureRssi: measureRssi() time = %d
S 1 15 4 706 Assert in file: "RssiPathClbrHndlr.c" in line: 706
S 1 15 4 721 RSSI CalcDerivative: section=%d a=%d b=%d
S 1 15 4 737 RSSI Path calcDerivative(): time = %d
S 1 15 4 879 GenerateRssiTable:Dynamic Range low =%d high %d
S 1 15 4 880 GenerateRssiTable:First Calibrated Power In Dynamic Range: %d
S 1 15 4 881 GenerateRssiTable:Last Calibrated Power In Dynamic Range: %d
S 1 15 4 911 Assert in file: "RssiPathClbrHndlr.c" in line: 911
S 1 15 4 924 Assert in file: "RssiPathClbrHndlr.c" in line: 924
S 1 15 4 971 Assert in file: "RssiPathClbrHndlr.c" in line: 971
S 1 15 4 1025 RSSI path VerifyResult: AntNum %d
S 1 15 4 1061 RSSI path VerifyResult: transmit power %d  meaured rssi %d  calibrated power %d
S 1 15 4 1086 RSSI path VerifyResult: Dynamic range %d low_power %d high_power %d
S 1 15 4 1095 RSSI path VerifyResult: Status Fail, dynamicRange below minimum allowed %d
S 1 15 4 1104 RSSI path VerifyResult: rssiPowerDiff %d maxDiffIsInPower %d
S 1 15 4 1113 RSSI path VerifyResult: Status Fail, rssiPowerDiff exceeds maximum allowed %d
S 1 15 4 1128 RSSI path VerifyResult: measurementVariation %d min_measure %d max_measure %d
S 1 15 4 1137 RSSI path VerifyResult: Status Fail, measurementVariation exceeds maximum allowed %d
S 1 15 4 1153 RSSI Path VerifyResult(): ret %d status %d
S 1 15 4 1161 RSSI Path VerifyResult(): verify run time %d
S 1 15 4 1181 Assert in file: "RssiPathClbrHndlr.c" in line: 1181
S 1 15 5 207 DC_STATE_DAC1 value[%d][0]=%d value[%d][1]=%d correction[%d][0]=%d correction[%d][1]=%d
S 1 15 5 212 DC_STATE_DAC2 value[%d][0]=%d value[%d][1]=%d
S 1 15 5 215 Dac0 ant =%d  lna = %d I=%d Q=%d MID_GAIN I=%d Q=%d LOW_GAIN I=%d Q=%d
S 1 15 5 220 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 220
S 1 15 5 244 RxDc_BackupElements.Dac1correction[%d][%d][%d] = %d RxDc_BackupElements.Dac1Residual[%d][%d][%d] = %d 
S 1 15 5 249 RxDc_BackupElements.Dac2Correction[%d][%d]=%d
S 1 15 5 257 Dac0 HIGH_GAIN  I=%d Q=%d MID_GAIN I=%d Q=%d LOW_GAIN I=%d Q=%d
S 1 15 5 283 restoreBackupValues DAC2 ant==%d ,pgcIndex==%d valueI = %d, valueQ= %d
S 1 15 5 316 restoreShadowValues DAC1  ant==%d lnaIndex==%d ,pgcIndex==%d valueI = %d, valueQ= %d
S 1 15 5 327 restoreShadowValues DAC2 ant==%d ,pgcIndex==%d valueI = %d, valueQ= %d
S 1 15 5 334 Dac0 HIGH_GAIN  I=%d Q=%d MID_GAIN I=%d Q=%d LOW_GAIN I=%d Q=%d
S 1 15 5 519 Rx DC: DAC2 Calibration Results for Antenna %d: I = %d, Q= %d.
S 1 15 5 523 Rx DC: DAC2 Calibration Exit, calibration state = %d, state count = %d.
S 1 15 5 558 ERROR!!!! Rx DC: verifyDac1Step. Antenna = %d, II = %d, QQ = %d.
S 1 15 5 722 Rx DC: DAC1 Calibration Results for Antenna %d: I = %d, Q = %d.
S 1 15 5 723 Rx DC: DAC1 Calibration Results for Antenna %d: Residual I = %d, Residual Q = %d.
S 1 15 5 768 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 768
S 1 15 5 914 Rx DC: Restore Done. Duration = %d
S 1 15 5 1175 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 1175
S 1 15 5 1319 RxDcOffset_LoadResults(): Ant0 PGC0, LNA index=%d  I=%d, Q=%d
S 1 15 5 1320 RxDcOffset_LoadResults(): Ant1 PGC0, LNA index=%d  I=%d, Q=%d
S 1 15 5 1321 RxDcOffset_LoadResults(): Ant2 PGC0, LNA index=%d  I=%d, Q=%d
S 1 15 5 1334 RxDcOffset_LoadResults(): Ant=%d PGC1=%d values:     I=%d, Q=%d
S 1 15 5 1335 RxDcOffset_LoadResults(): Ant=%d PGC1=%d correction: I=%d, Q=%d
S 1 15 5 1345 RxDcOffset_LoadResults(): Ant=%d PGC2=%d I=%d, Q=%d
S 1 15 5 1374 RxDcOffset_StoreResults(): Ant0 PGC0, LNA index=%d I=%d, Q=%d
S 1 15 5 1375 RxDcOffset_StoreResults(): Ant1 PGC0, LNA index=%d I=%d, Q=%d
S 1 15 5 1376 RxDcOffset_StoreResults(): Ant2 PGC0, LNA index=%d I=%d, Q=%d
S 1 15 5 1395 RxDcOffset_StoreResults(): Ant=%d PGC1=%d values:     I=%d, Q=%d
S 1 15 5 1396 RxDcOffset_StoreResults(): Ant=%d PGC1=%d correction: I=%d, Q=%d
S 1 15 5 1404 RxDcOffset_StoreResults(): Ant=%d PGC2=%d I=%d, Q=%d
S 1 15 25 173 Rx IQ: Executing Calibration
S 1 15 25 203 RxIQ calibrated values for ANTENNA %d  w1 = %d w2 = %d
S 1 15 25 204 RxIQ calibrated coefficients II = %d QQ = %d IQ = %d
S 1 15 25 218 RxIQ ALGO:Finished Calibration. Ret Code = %d, Run Time = %d
S 1 15 25 252 Rx IQ: Restore Done. Duration = %d
S 1 15 25 299 Rx IQ: Init Done. Duration = %d
S 1 15 25 455 RxIQ error verification for ANTENNA %d  w1 = %d w2 = %d
S 1 15 25 456 RxIQ error verification II = %d QQ = %d IQ = %d
S 1 15 25 475 RxIQ verifyCalibrationResults: error verification Status = %d w1_Error= %d w2_Error= %d
S 1 15 25 604 RxIQ_LoadResults(): Ant %d w1=%d w2=%d
S 1 15 25 648 RxIQ_StoreResults(): Ant %d w1=%d w2=%d
S 1 15 7 274 TxIQ ALGO:Executing Calibration: CalibType(offline(1)/online(2)) = %d,
S 1 15 7 318 Tx IQ: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 15 7 402 Tx IQ initAntennaOnlineIterationDetails: last antenna = %d
S 1 15 7 506 TXIQ calibrateSingleAntenna:RF Ant %d,LoopBackRxAnt %d, LoopBackTxAnt %d
S 1 15 7 561 Tx IQ calibrateSingleAntenna(): Restore Hw Registers Run Time = %d
S 1 15 7 610 Tx IQ: Init Done. Duration = %d
S 1 15 7 640 Tx IQ: Restore Done. Duration = %d
S 1 15 7 758 Tx IQ calibrateAndVerifySingleBin:Bin %d
S 1 15 7 792 Tx IQ calibrateAndVerifySingleBin(): Run Time = %d
S 1 15 7 849 Tx IQ calcMinimumCoeffcientsValue(): b energy x0=%d x1=%d x2=%d
S 1 15 7 850 Tx IQ calcMinimumCoeffcientsValue(): b energy x3=%d x4=%d x5=%d
S 1 15 7 851 Tx IQ calcMinimumCoeffcientsValue(): b energy x6=%d x7=%d x8=%d
S 1 15 7 871 Tx IQ calcMinimumCoeffcientsValue(): a energy x0=%d x1=%d x2=%d
S 1 15 7 872 Tx IQ calcMinimumCoeffcientsValue(): a energy x3=%d x4=%d x5=%d
S 1 15 7 873 Tx IQ calcMinimumCoeffcientsValue(): a energy x6=%d x7=%d x8=%d
S 1 15 7 885 Tx IQ calcMinCoeffcientValues(): a=%d, b=%d
S 1 15 7 1049 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1049
S 1 15 7 1086 Tx IQ VerifyCalibrationResults(): Energy(log) = %d
S 1 15 7 1099 Tx IQ verifyCalibrationResults():Energy exceeds max TH = %d status = %d
S 1 15 7 1116 Tx IQ verifyCalibrationResults(): Single bin verify Run Time = %d
S 1 15 7 1256 Tx IQ fixFailedBins(): Can't fix bins - calibration of all bins in range failed !!!
S 1 15 7 1272 Tx IQ fixFailedBins():Minimal Coefficient Values: bin=%d a=%d, b=%d
S 1 15 7 1283 Tx IQ fixFailedBins(): Failed bins %d, Fixed bins %d
S 1 15 7 1303 Tx IQ fixFailedBins(): Range sign %d, Run Time = %d
S 1 15 7 1417 Tx IQ calcInterpolatedCoefficients(): Interpolation between 2 bins [0,1] Run Time = %d
S 1 15 7 1491 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1491
S 1 15 7 1515 TxIQClbr_LoadResults(): binIndex %d a=%d b=%d
S 1 15 7 1530 TxIQClbr_LoadResults(): binIndex %d a=%d b=%d
S 1 15 7 1573 TxIQClbr_StoreResults(): CB mode %d
S 1 15 7 1594 TxIQClbr_StoreResults(): binIndex %d a=%d b=%d
S 1 15 7 1606 TxIQClbr_StoreResults(): binIndex %d a=%d b=%d
S 1 15 24 301 Tx Lo: Executing Calibration: CalibType(offline(1)/online(2)) = %d,
S 1 15 24 338 Tx Lo: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 15 24 523 TXLo calibrateSingleAntenna:RF Ant %d,LoopBackRxAnt %d, LoopBackTxAnt %d
S 1 15 24 539 TxLo calibrateSingleAntenna(): Restore Hw Registers Run Time = %d
S 1 15 24 607 Tx LO: Init Done. Duration = %d
S 1 15 24 659 Tx LO: Restore HwRegisters Done. Duration = %d
S 1 15 24 811 TxLo calibrateAndVerifySingleTpc: TPC %d
S 1 15 24 845 Tx Lo calibrateAndVerifySingleTpc(): Verify reference Energy(log) = %d
S 1 15 24 911 TxLo doAxisIteration(). Iteration = %d, I = %d
S 1 15 24 922 TxLo doAxisIteration(). Iteration = %d, Q = %d
S 1 15 24 936 TxLo calibrateAndVerifySingleTpc digitalDacI = %d, digitalDacQ = %d
S 1 15 24 945 TxLo calibrateAndVerifySingleTpc dacI = %d, dacQ = %d
S 1 15 24 962 TxLo calibrateAndVerifySingleTpc(): Run Time = %d
S 1 15 24 1121 TxLo digitalDacUpdateRequired() DAC  %d exceeds allowed range but digital DAC max iterations %d exceeded
S 1 15 24 1180 TxLo addDigitalDac: iteration %d digitalDacQ = %d
S 1 15 24 1197 TxLo addDigitalDac: iteration %d digitalDacQ = %d
S 1 15 24 1215 TxLo addDigitalDac: iteration %d digitalDacI = %d
S 1 15 24 1232 TxLo addDigitalDac: iteration %d digitalDacI = %d
S 1 15 24 1292 Tx Lo VerifyCalibrationResults(): TPC Energy(log) = %d Diff from Ref %d
S 1 15 24 1303 Tx Lo verifyCalibrationResults():Energy diff from ref %d below TH = %d status = %d
S 1 15 24 1312 TxLo verifyCalibrationResults status = %d
S 1 15 24 1345 TxLo verifyCalibrationResults(): Single TPC verify Run Time = %d
S 1 15 24 1497 TxLo updateTpcsToNextCalibTpc: next TPC = %d
S 1 15 24 1607 TxLoLeakage_LoadResults(): Ant %d Digital DAC: I=%d Q=%d
S 1 15 24 1617 TxLoLeakage_LoadResults(): Ant %d Num Calibrated TPCs=%d
S 1 15 24 1626 Assert in file: "TxLOLeakageClbrHndlr.c" in line: 1626
S 1 15 24 1638 TxLoLeakage_StoreResults(): Ant %d TPC %d DAC: I=%d Q=%d
S 1 15 24 1677 TxLoLeakage_StoreResults(): Ant %d Digital DAC: I=%d Q=%d
S 1 15 24 1685 TxLoLeakage_StoreResults(): Ant %d Num Calibrated TPCs=%d
S 1 15 24 1696 TxLoLeakage_StoreResults(): Ant %d TPC %d DAC: I=%d Q=%d
S 1 15 21 123 Run TxJumpOffset Calibration
S 1 15 21 235 Assert in file: "TxPhaseJumpClbrHndlr.c" in line: 235
S 1 15 21 250 Send packet from ant %d to ant %d
S 1 15 21 272 Tx phase jump Calibration flipping ant %d
S 1 15 21 320 Assert in file: "TxPhaseJumpClbrHndlr.c" in line: 320
S 1 15 21 354 Assert in file: "TxPhaseJumpClbrHndlr.c" in line: 354
S 1 15 21 357 Tx phase jump calibration, flipI = %d, flipQ=%d, constantK.real = %d, constantK.image = %d
S 1 15 21 404 Assert in file: "TxPhaseJumpClbrHndlr.c" in line: 404
S 1 15 21 423 Assert in file: "TxPhaseJumpClbrHndlr.c" in line: 423
S 1 15 21 472 Assert in file: "TxPhaseJumpClbrHndlr.c" in line: 472
S 1 15 9 104 LoadCalibrationResults: start: buffer at: 0x%x
S 1 15 9 116 Assert in file: "CalibrationHandler.c" in line: 116
S 1 15 9 137 LoadCalibrationResults: end
S 1 15 9 262 Checking VCO status
S 1 15 9 269 Assert in file: "CalibrationHandler.c" in line: 269
S 1 15 9 277 Assert in file: "CalibrationHandler.c" in line: 277
S 1 15 9 279 Assert in file: "CalibrationHandler.c" in line: 279
S 1 15 9 288 VCO handling complete. status = %d
S 1 15 9 302 CH:: runCalibration() type %d (1-offline, 2-online)
S 1 15 9 340 Start Calibrations: mode=%d, calibration proc bitmap=0x%x
S 1 15 9 353 @@CH: Start Calibrations: mode=%d, proc=%d, remaining procs bitmap=0x%x
S 1 15 9 355 Assert in file: "CalibrationHandler.c" in line: 355
S 1 15 9 359 @@CH: Finished Calibration. rc = %d
S 1 15 9 366 Finished Calibrations.
S 1 15 9 499 CalibrationHandler getUpdateStatus(). StatusVector = 0x%x %d
S 1 15 23 26 Assert in file: "CalibrationHandlerUtils.c" in line: 26
S 1 15 23 32 Assert in file: "CalibrationHandlerUtils.c" in line: 32
S 1 15 18 653 Assert in file: "Afe.c" in line: 653
S 1 15 18 734 Assert in file: "Afe.c" in line: 734
S 1 15 19 955 Assert in file: "Afe.c" in line: 955
S 1 15 19 988 Assert in file: "Afe.c" in line: 988
S 1 15 19 1097 Assert in file: "Afe.c" in line: 1097
S 1 15 19 1221 Assert in file: "Afe.c" in line: 1221
S 1 15 8 257 Assert in file: "IndirectAccess.c" in line: 257
S 1 15 11 511 Assert in file: "PhyCalDriver.c" in line: 511
S 1 15 11 901 Assert in file: "PhyCalDriver.c" in line: 901
S 1 15 11 1120 Assert in file: "PhyCalDriver.c" in line: 1120
S 1 15 11 1327 Assert in file: "PhyCalDriver.c" in line: 1327
S 1 15 11 1355 Assert in file: "PhyCalDriver.c" in line: 1355
S 1 15 11 1385 Assert in file: "PhyCalDriver.c" in line: 1385
S 1 15 16 561 Assert in file: "PhyCalDriver.c" in line: 561
S 1 15 16 981 Assert in file: "PhyCalDriver.c" in line: 981
S 1 15 16 1210 Assert in file: "PhyCalDriver.c" in line: 1210
S 1 15 16 1417 Assert in file: "PhyCalDriver.c" in line: 1417
S 1 15 16 1444 Assert in file: "PhyCalDriver.c" in line: 1444
S 1 15 16 1475 Assert in file: "PhyCalDriver.c" in line: 1475
S 1 15 1 307 Fatal Error in file: "mt_phy_dummy.c"; Fatal Print: Bad PHY mdoe
S 1 15 1 377 Assert in file: "mt_phy_dummy.c" in line: 377
S 1 15 12 478 Assert in file: "PhyDriver.c" in line: 478
S 1 15 12 489 Assert in file: "PhyDriver.c" in line: 489
S 1 15 12 658 Assert in file: "PhyDriver.c" in line: 658
S 1 15 12 682 Assert in file: "PhyDriver.c" in line: 682
S 1 15 2 393 Fatal Error in file: "phy_dummy.c"; Fatal Print: Bad PHY mdoe
S 1 15 2 555 Fatal Error in file: "phy_dummy.c"; Fatal Print: Bad PHY mdoe
S 1 15 13 117 Assert in file: "PhyTestBus.c" in line: 117
S 1 15 13 137 Assert in file: "PhyTestBus.c" in line: 137
S 1 15 17 378 Assert in file: "RficDriver.c" in line: 378
S 1 15 17 421 Assert in file: "RficDriver.c" in line: 421
S 1 15 17 462 Assert in file: "RficDriver.c" in line: 462
S 1 15 17 568 Assert in file: "RficDriver.c" in line: 568
S 1 15 17 710 Assert in file: "RficDriver.c" in line: 710
S 1 15 17 711 Assert in file: "RficDriver.c" in line: 711
S 1 15 17 732 Assert in file: "RficDriver.c" in line: 732
S 1 15 17 774 Assert in file: "RficDriver.c" in line: 774
S 1 15 17 775 Assert in file: "RficDriver.c" in line: 775
S 1 15 17 776 Assert in file: "RficDriver.c" in line: 776
S 1 15 17 855 Assert in file: "RficDriver.c" in line: 855
S 1 15 17 1070 Assert in file: "RficDriver.c" in line: 1070
S 1 15 17 1086 Assert in file: "RficDriver.c" in line: 1086
S 1 15 17 1541 Assert in file: "RficDriver.c" in line: 1541
S 1 15 17 1828 Assert in file: "RficDriver.c" in line: 1828
S 1 15 17 1853 Assert in file: "RficDriver.c" in line: 1853
S 1 15 17 1925 Assert in file: "RficDriver.c" in line: 1925
S 1 15 17 1930 Assert in file: "RficDriver.c" in line: 1930
S 1 15 17 2044 Assert in file: "RficDriver.c" in line: 2044
S 1 15 22 486 Assert in file: "RficDriver.c" in line: 486
S 1 15 22 538 Assert in file: "RficDriver.c" in line: 538
S 1 15 22 579 Assert in file: "RficDriver.c" in line: 579
S 1 15 22 832 Assert in file: "RficDriver.c" in line: 832
S 1 15 22 889 Assert in file: "RficDriver.c" in line: 889
S 1 15 22 890 Assert in file: "RficDriver.c" in line: 890
S 1 15 22 891 Assert in file: "RficDriver.c" in line: 891
S 1 15 22 963 Assert in file: "RficDriver.c" in line: 963
S 1 15 22 1119 Assert in file: "RficDriver.c" in line: 1119
S 1 15 22 1181 Assert in file: "RficDriver.c" in line: 1181
S 1 15 22 1229 Assert in file: "RficDriver.c" in line: 1229
S 1 15 22 1270 Assert in file: "RficDriver.c" in line: 1270
S 1 15 22 1314 Assert in file: "RficDriver.c" in line: 1314
S 1 15 22 1354 Assert in file: "RficDriver.c" in line: 1354
S 1 15 22 1459 Assert in file: "RficDriver.c" in line: 1459
S 1 15 22 1537 Assert in file: "RficDriver.c" in line: 1537
S 1 15 22 1552 Assert in file: "RficDriver.c" in line: 1552
S 1 15 22 1619 Assert in file: "RficDriver.c" in line: 1619
S 1 15 22 1683 Assert in file: "RficDriver.c" in line: 1683
S 1 15 22 1721 Assert in file: "RficDriver.c" in line: 1721
S 1 15 22 1917 Assert in file: "RficDriver.c" in line: 1917
S 1 15 22 2093 Assert in file: "RficDriver.c" in line: 2093
S 1 15 22 2193 Assert in file: "RficDriver.c" in line: 2193
S 1 15 22 2251 Assert in file: "RficDriver.c" in line: 2251
S 1 15 22 2343 Assert in file: "RficDriver.c" in line: 2343
S 1 15 22 2344 Assert in file: "RficDriver.c" in line: 2344
S 1 15 22 2384 Assert in file: "RficDriver.c" in line: 2384
S 1 15 22 2385 Assert in file: "RficDriver.c" in line: 2385
S 1 15 22 2461 Assert in file: "RficDriver.c" in line: 2461
S 1 15 22 2551 Assert in file: "RficDriver.c" in line: 2551
S 1 15 29 363 Assert in file: "LmHdk.c" in line: 363
S 1 16 1 441 Assert in file: "him.c" in line: 441
S 1 16 1 572 Error buffer descriptor in FIFO! sDesc.u16Info 0x%04x, sDesc.u8Index 0x%04x, sDesc.u8Type 0x%04x
S 1 16 1 573 Fatal Error in file: "him.c"; Fatal Print: Error buffer descriptor in FIFO!
S 1 16 1 602 Assert in file: "him.c" in line: 602
S 1 16 1 756 Assert in file: "him.c" in line: 756
S 1 16 1 818 Fatal Error in file: "him.c"; Fatal Print: Error buffer descriptor in FIFO!
S 1 16 1 853 Assert in file: "him.c" in line: 853
S 1 16 4 163 Assert in file: "him_api.c" in line: 163
S 1 16 4 256 Assert in file: "him_api.c" in line: 256
S 1 16 2 139 Assert in file: "him_buffer_manager.c" in line: 139
S 1 16 2 218 Assert in file: "him_buffer_manager.c" in line: 218
S 1 16 2 248 Assert in file: "him_buffer_manager.c" in line: 248
S 1 16 2 352 Assert in file: "him_buffer_manager.c" in line: 352
S 1 16 3 262 Assert in file: "him_serial.c" in line: 262
S 1 17 1 192 Assert in file: "kccmsg.c" in line: 192
S 1 17 1 262 Fatal Error in file: "kccmsg.c"; Fatal Print: pre-allocated message space insufficient
S 1 17 1 302 Assert in file: "kccmsg.c" in line: 302
S 1 17 1 311 Assert in file: "kccmsg.c" in line: 311
S 1 17 1 315 Assert in file: "kccmsg.c" in line: 315
S 1 17 1 414 Assert in file: "kccmsg.c" in line: 414
S 1 17 1 435 Assert in file: "kccmsg.c" in line: 435
S 1 17 1 436 Assert in file: "kccmsg.c" in line: 436
S 1 17 1 556 Assert in file: "kccmsg.c" in line: 556
S 1 17 1 576 Fatal Error in file: "kccmsg.c"; Fatal Print: Attempt to free a non freeable message
S 1 17 1 687 Assert in file: "kccmsg.c" in line: 687
S 1 17 1 741 Assert in file: "kccmsg.c" in line: 741
S 1 17 1 817 Fatal Error in file: "kccmsg.c"; Fatal Print: Tried to increase a reference count past limit
S 1 17 1 852 Fatal Error in file: "kccmsg.c"; Fatal Print: Tried to decrease a reference count past zero
S 1 17 3 61 Assert in file: "kccsched.c" in line: 61
S 1 17 3 331 Assert in file: "kccsched.c" in line: 331
S 1 17 3 490 Assert in file: "kccsched.c" in line: 490
S 1 17 3 636 Assert in file: "kccsched.c" in line: 636
S 1 17 2 210 sleep time in micro %010u out of %010u
S 1 17 2 413 Assert in file: "kcctimer.c" in line: 413
S 1 17 2 694 Fatal Error in file: "kcctimer.c"; Fatal Print: no timers left to allocate
S 1 17 2 1304 Assert in file: "kcctimer.c" in line: 1304
S 1 17 2 1309 Assert in file: "kcctimer.c" in line: 1309
S 1 17 2 1374 Assert in file: "kcctimer.c" in line: 1374
S 1 18 3 70 Assert in file: "loggerAPI.h" in line: 70
S 1 18 5 269 Assert in file: "logger.c" in line: 269
S 1 18 5 324 Assert in file: "logger.c" in line: 324
S 1 18 5 504 Assert in file: "logger.c" in line: 504
S 1 18 5 508 Assert in file: "logger.c" in line: 508
S 1 18 5 539 Assert in file: "logger.c" in line: 539
S 1 18 5 540 Assert in file: "logger.c" in line: 540
S 1 18 5 658 Assert in file: "logger.c" in line: 658
S 1 18 5 837 Assert in file: "logger.c" in line: 837
S 1 18 5 891 Assert in file: "logger.c" in line: 891
S 1 18 5 897 Assert in file: "logger.c" in line: 897
S 1 18 5 913 Assert in file: "logger.c" in line: 913
S 1 18 5 944 Assert in file: "logger.c" in line: 944
S 1 18 5 1062 !! requested trace is too large to fit in buffer: %d Bytes, limit is %d Bytes !!
S 1 18 5 1102 Assert in file: "logger.c" in line: 1102
S 1 18 5 1195 Assert in file: "logger.c" in line: 1195
S 1 18 5 1243 Assert in file: "logger.c" in line: 1243
S 1 18 5 1247 Assert in file: "logger.c" in line: 1247
S 1 18 5 1280 ** missed logs: lack of buffers: %d, lack of BD: %d
S 1 18 5 1383 Assert in file: "logger.c" in line: 1383
S 1 18 5 1410 Assert in file: "logger.c" in line: 1410
S 1 18 5 1519 PhyLogger_DumpCurrentChunk, writePtr:%d, chunkNum:%d
S 1 18 5 1557 ** missed phy logger chunk/s **
S 1 18 5 1602 LoggerApi_PhyLogTest1, diff time:%d, cpuLoad:%d, totalCpuLoad:%d, chunkNum:%d
S 1 18 5 1621 Assert in file: "logger.c" in line: 1621
S 1 18 2 203 LoggerApi_SetSeverity, level:%d, targetCPU:%d
S 1 18 2 209 Logger severity request is out of range:%d ! (should be [%d, %d]
S 1 18 2 269 Assert in file: "loggerAPI.c" in line: 269
S 1 18 2 291 Assert in file: "loggerAPI.c" in line: 291
S 1 18 2 464 KERNEL_EVENT_RECV_KNL_MSG fromTask_toTask_kMsgId: %08x
S 1 18 2 476 KERNEL_EVENT_RECV_FROM_HOST_MSG kMsgType: %08x
S 1 18 2 488 KERNEL_EVENT_SEND_TO_HOST_MSG kMsgType: %08x
S 1 18 2 636 Assert in file: "loggerAPI.c" in line: 636
S 1 19 2 213 Fatal Error in file: "lmint.c"; Fatal Print: Status FIFO has overflowed
S 1 19 2 282 vLM_pac_tsf_timer_int: TIM_TIMER_CTRL_EV3_CLR_TSF1, time %u
S 1 19 2 533 Assert in file: "lmint.c" in line: 533
S 1 19 2 628 Fatal Error in file: "lmint.c"; Fatal Print: WD(phy) interrupt occured
S 1 19 2 639 Fatal Error in file: "lmint.c"; Fatal Print: RDT Buffer Overrun
S 1 19 6 241 Assert in file: "lmqueue.c" in line: 241
S 1 19 4 767 uiPrepareTxopFrag, FRM_CTRL_TYPE_MGMT, length:%d
S 1 19 4 2171 Fatal Error in file: "lmutil.c"; Fatal Print: Out of messages
S 1 19 4 2593 Fatal Error in file: "lmutil.c"; Fatal Print: Unknown rate type
S 1 19 4 3165 Assert in file: "lmutil.c" in line: 3165
S 1 19 4 3272 Assert in file: "lmutil.c" in line: 3272
S 1 19 4 3558 Assert in file: "lmutil.c" in line: 3558
S 1 19 7 76 Assert in file: "MT_HaltTx_11H.c" in line: 76
S 1 19 7 145 Assert in file: "MT_HaltTx_11H.c" in line: 145
S 1 19 9 701 Assert in file: "mt_lm_n_rtns.c" in line: 701
S 1 19 8 101 QSMinsertEvent, Occured
S 1 19 8 183 Assert in file: "MT_QSmachine.c" in line: 183
S 1 19 8 193 Assert in file: "MT_QSmachine.c" in line: 193
S 1 19 8 364 Assert in file: "MT_QSmachine.c" in line: 364
S 1 19 8 413 Assert in file: "MT_QSmachine.c" in line: 413
S 1 19 12 539 Assert in file: "MT_RecipeConstructionHyp3.c" in line: 539
S 1 20 5 75 Assert in file: "lmi_queue.c" in line: 75
S 1 22 1 35 Assert in file: "sysinfo.h" in line: 35
S 1 23 3 558 vAPP_Assert assertGroupId=%d assertFileId=%d assertLine=%d
S 1 24 1 228 Online Calib Timer Expired. online enabled = %d, main state = %d
S 1 24 1 295 CM finished online calibrations, resuming Tx. Net Duration = %d, state = %d
S 1 24 1 313 CM finished offline calibrations, resuming Tx. state = %d
S 1 24 1 322 CM finished offline calibrations, notifying task %d. state = %d
S 1 24 1 337 Assert in file: "MainSM.c" in line: 337
S 1 24 1 419 Assert in file: "MainSM.c" in line: 419
S 1 24 1 464 Assert in file: "MainSM.c" in line: 464
S 1 24 1 509 HW dependent configuration finished. moving to IDLE state and notifying Host.
S 1 24 1 525 Assert in file: "MainSM.c" in line: 525
S 1 24 1 590 Assert in file: "MainSM.c" in line: 590
S 1 24 1 643 handleStopOnlineCalibCfm: m_state: %d, m_onlineStopReqTask: %d
S 1 24 1 675 Assert in file: "MainSM.c" in line: 675
S 1 24 1 686 handleStopOnlineCalibReq: state: %d
S 1 24 1 690 handleStopOnlineCalibReq: origin task: %d, m_state: %d, m_waitForOnlineStop %d
S 1 24 1 731 Assert in file: "MainSM.c" in line: 731
S 1 24 1 742 Assert in file: "MainSM.c" in line: 742
S 1 24 1 749 Assert in file: "MainSM.c" in line: 749
S 1 24 1 804 handleTxQueueChangeCfm: Tx Pause state = %d, Main state = %d
S 1 24 1 806 handleTxQueueChangeCfm: m_txPauseState %d, m_state %d, pauseMsg->returnTaskId: %d
S 1 24 1 825 Tx resumed after offline calibrations, notifying task %d. state = %d
S 1 24 1 840 Assert in file: "MainSM.c" in line: 840
S 1 24 1 847 Tx resumed after online calibrations. Duration = %d, state = %d
S 1 24 1 871 Assert in file: "MainSM.c" in line: 871
S 1 24 1 978 Assert in file: "MainSM.c" in line: 978
S 1 24 1 990 Assert in file: "MainSM.c" in line: 990
S 1 24 1 1025 *handleCTSToSelfCallback success: status UMI_OK
S 1 24 1 1037 *Fail handleCTSToSelfCallback fail: status %d (2=UMI_BAD_PARAMETER)
S 1 24 1 1058 restartOnlineCalibSched: m_waitForOnlineStop %d
S 1 24 1 1087 Assert in file: "MainSM.c" in line: 1087
S 1 24 1 1116 Assert in file: "MainSM.c" in line: 1116
S 1 24 1 1178 MainSM_EnableOnlineCalibration: state: %d
S 1 24 1 1214 Received HW dependent configuration from Host. Moving to state HW_DEP_CONF. notifying LM.
S 1 24 1 1240 handle11hChangeTxStateCfm: m_state: %d, m_txPauseState: %d, ChangeTxStateMsg->returnTaskId: %d
S 1 24 1 1269 Assert in file: "MainSM.c" in line: 1269
S 1 24 1 1286 Assert in file: "MainSM.c" in line: 1286
S 1 24 1 1308 Assert in file: "MainSM.c" in line: 1308
S 1 24 1 1346 handle11hChangeTxStateReq: m_state: %d  m_txPauseState: %d
S 1 24 1 1379 Assert in file: "MainSM.c" in line: 1379
S 1 24 1 1399 MainSM_ChangeTxQueuesState: Requested State = %d, Requsting Task ID = %d
S 1 24 1 1537 Assert in file: "MainSM.c" in line: 1537
S 1 25 1 105 Assert in file: "fsdu_resource.c" in line: 105
S 1 25 1 107 Assert in file: "fsdu_resource.c" in line: 107
S 1 25 1 201 Fatal Error in file: "fsdu_resource.c"; Fatal Print: No FPDUS when there should be!
S 1 25 2 73 Assert in file: "init_ifmsg.c" in line: 73
S 1 25 2 75 Assert in file: "init_ifmsg.c" in line: 75
S 1 25 2 125 Assert in file: "init_ifmsg.c" in line: 125
S 1 25 2 157 Assert in file: "init_ifmsg.c" in line: 157
S 1 25 2 312 Assert in file: "init_ifmsg.c" in line: 312
S 1 25 3 99 Assert in file: "init_msdu.c" in line: 99
S 1 25 3 176 Assert in file: "init_msdu.c" in line: 176
S 1 25 5 62 Assert in file: "MT_NSSMemoryPool.c" in line: 62
S 1 25 5 75 Assert in file: "MT_NSSMemoryPool.c" in line: 75
S 1 25 5 81 Assert in file: "MT_NSSMemoryPool.c" in line: 81
S 1 25 5 127 Assert in file: "MT_NSSMemoryPool.c" in line: 127
S 1 25 5 135 Assert in file: "MT_NSSMemoryPool.c" in line: 135
S 1 25 5 165 Assert in file: "MT_NSSMemoryPool.c" in line: 165
S 1 25 5 173 Assert in file: "MT_NSSMemoryPool.c" in line: 173
S 1 25 5 186 Assert in file: "MT_NSSMemoryPool.c" in line: 186
S 1 25 5 351 Assert in file: "MT_NSSMemoryPool.c" in line: 351
S 1 25 5 453 Assert in file: "MT_NSSMemoryPool.c" in line: 453
S 1 25 5 457 Assert in file: "MT_NSSMemoryPool.c" in line: 457
S 1 25 5 496 Assert in file: "MT_NSSMemoryPool.c" in line: 496
S 1 25 4 381 Assert in file: "um_mem_task.c" in line: 381
S 1 25 4 386 Assert in file: "um_mem_task.c" in line: 386
S 1 25 4 567 Assert in file: "um_mem_task.c" in line: 567
S 1 25 4 568 Assert in file: "um_mem_task.c" in line: 568
S 1 25 4 721 Assert in file: "um_mem_task.c" in line: 721
S 1 25 4 726 Assert in file: "um_mem_task.c" in line: 726
S 1 25 4 750 Assert in file: "um_mem_task.c" in line: 750
S 1 26 3 173 Assert in file: "mt_addr_sharing.c" in line: 173
S 1 26 3 223 Assert in file: "mt_addr_sharing.c" in line: 223
S 1 26 4 132 Assert in file: "app_serial.c" in line: 132
S 1 26 4 146 Assert in file: "app_serial.c" in line: 146
S 1 26 4 207 Assert in file: "app_serial.c" in line: 207
S 1 26 4 233 Assert in file: "app_serial.c" in line: 233
S 1 26 6 134 Assert in file: "ccmp_drv.c" in line: 134
S 1 26 6 135 Assert in file: "ccmp_drv.c" in line: 135
S 1 26 6 136 Assert in file: "ccmp_drv.c" in line: 136
S 1 26 6 137 Assert in file: "ccmp_drv.c" in line: 137
S 1 26 6 256 Assert in file: "ccmp_drv.c" in line: 256
S 1 26 6 257 Assert in file: "ccmp_drv.c" in line: 257
S 1 26 6 259 Assert in file: "ccmp_drv.c" in line: 259
S 1 26 6 260 Assert in file: "ccmp_drv.c" in line: 260
S 1 26 6 261 Assert in file: "ccmp_drv.c" in line: 261
S 1 26 6 387 Assert in file: "ccmp_drv.c" in line: 387
S 1 26 6 388 Assert in file: "ccmp_drv.c" in line: 388
S 1 26 6 389 Assert in file: "ccmp_drv.c" in line: 389
S 1 26 6 393 Assert in file: "ccmp_drv.c" in line: 393
S 1 26 6 498 Assert in file: "ccmp_drv.c" in line: 498
S 1 26 6 499 Assert in file: "ccmp_drv.c" in line: 499
S 1 26 6 501 Assert in file: "ccmp_drv.c" in line: 501
S 1 26 6 502 Assert in file: "ccmp_drv.c" in line: 502
S 1 26 6 503 Assert in file: "ccmp_drv.c" in line: 503
S 1 26 7 287 Assert in file: "dma.c" in line: 287
S 1 26 7 369 Assert in file: "dma.c" in line: 369
S 1 26 7 477 Assert in file: "dma.c" in line: 477
S 1 26 7 482 Assert in file: "dma.c" in line: 482
S 1 26 7 509 Assert in file: "dma.c" in line: 509
S 1 26 7 624 Assert in file: "dma.c" in line: 624
S 1 26 7 745 Assert in file: "dma.c" in line: 745
S 1 26 7 762 Assert in file: "dma.c" in line: 762
S 1 26 7 778 Assert in file: "dma.c" in line: 778
S 1 26 7 783 Assert in file: "dma.c" in line: 783
S 1 26 7 884 Assert in file: "dma.c" in line: 884
S 1 26 7 891 Assert in file: "dma.c" in line: 891
S 1 26 7 893 Assert in file: "dma.c" in line: 893
S 1 26 7 1051 Assert in file: "dma.c" in line: 1051
S 1 26 7 1224 Assert in file: "dma.c" in line: 1224
S 1 26 1 117 Assert in file: "interrupt.c" in line: 117
S 1 26 1 449 Fatal Error in file: "interrupt.c"; Fatal Print: Spurious Interrupt
S 1 26 1 634 Assert in file: "interrupt.c" in line: 634
S 1 26 1 657 Assert in file: "interrupt.c" in line: 657
S 1 26 1 661 reg: 0x%08x, index %d
S 1 26 1 664 Assert in file: "interrupt.c" in line: 664
S 1 26 1 774 Assert in file: "interrupt.c" in line: 774
S 1 26 1 778 Assert in file: "interrupt.c" in line: 778
S 1 26 8 157 Assert in file: "int_gen.c" in line: 157
S 1 26 8 159 Assert in file: "int_gen.c" in line: 159
S 1 26 8 192 Assert in file: "int_gen.c" in line: 192
S 1 26 8 194 Assert in file: "int_gen.c" in line: 194
S 1 26 10 60 Assert in file: "MT_hw_info.c" in line: 60
S 1 26 10 187 Assert in file: "MT_hw_info.c" in line: 187
S 1 26 9 76 Assert in file: "rxf.c" in line: 76
S 1 26 9 118 Assert in file: "rxf.c" in line: 118
S 1 26 9 146 Assert in file: "rxf.c" in line: 146
S 1 26 9 164 Assert in file: "rxf.c" in line: 164
S 1 26 9 187 Assert in file: "rxf.c" in line: 187
S 1 26 9 201 Assert in file: "rxf.c" in line: 201
S 1 26 9 218 Assert in file: "rxf.c" in line: 218
S 1 26 9 251 Assert in file: "rxf.c" in line: 251
S 1 26 9 287 Assert in file: "rxf.c" in line: 287
S 1 26 9 310 Assert in file: "rxf.c" in line: 310
S 1 26 9 323 Assert in file: "rxf.c" in line: 323
S 1 26 9 341 Assert in file: "rxf.c" in line: 341
S 1 26 9 351 Assert in file: "rxf.c" in line: 351
S 1 26 9 371 Assert in file: "rxf.c" in line: 371
S 1 26 11 76 Assert in file: "shram_dma_drv.c" in line: 76
S 1 26 11 77 Assert in file: "shram_dma_drv.c" in line: 77
S 1 26 2 123 Assert in file: "tkip_drv.c" in line: 123
S 1 26 2 124 Assert in file: "tkip_drv.c" in line: 124
S 1 26 2 189 Assert in file: "tkip_drv.c" in line: 189
S 1 26 2 190 Assert in file: "tkip_drv.c" in line: 190
S 1 26 2 205 vTKIP_DRV_CalcMic, prio:%d, psFsdu:%x
S 1 26 2 439 Assert in file: "tkip_drv.c" in line: 439
S 1 26 2 440 Assert in file: "tkip_drv.c" in line: 440
S 1 26 2 441 Assert in file: "tkip_drv.c" in line: 441
S 1 26 2 442 Assert in file: "tkip_drv.c" in line: 442
S 1 26 2 452 vTKIP_DRV_EncryptMpdu, prio:%d, psFsdu:%x
S 1 26 2 508 Fatal Error in file: "tkip_drv.c"; Fatal Print: Not supported on FPGA
S 1 26 2 595 Assert in file: "tkip_drv.c" in line: 595
S 1 26 2 596 Assert in file: "tkip_drv.c" in line: 596
S 1 26 2 597 Assert in file: "tkip_drv.c" in line: 597
S 1 26 2 598 Assert in file: "tkip_drv.c" in line: 598
S 1 26 2 687 Assert in file: "tkip_drv.c" in line: 687
S 1 26 13 173 Assert in file: "um_dma_cmplt_task.c" in line: 173
S 1 26 14 87 Assert in file: "wep_drv.c" in line: 87
S 1 26 14 88 Assert in file: "wep_drv.c" in line: 88
S 1 26 14 89 Assert in file: "wep_drv.c" in line: 89
S 1 26 14 90 Assert in file: "wep_drv.c" in line: 90
S 1 26 14 193 Assert in file: "wep_drv.c" in line: 193
S 1 26 14 194 Assert in file: "wep_drv.c" in line: 194
S 1 26 14 195 Assert in file: "wep_drv.c" in line: 195
S 1 26 14 197 Assert in file: "wep_drv.c" in line: 197
S 1 26 14 271 Assert in file: "wep_drv.c" in line: 271
S 1 26 14 272 Assert in file: "wep_drv.c" in line: 272
S 1 26 14 273 Assert in file: "wep_drv.c" in line: 273
S 1 26 14 277 Assert in file: "wep_drv.c" in line: 277
S 1 26 14 379 Assert in file: "wep_drv.c" in line: 379
S 1 26 14 380 Assert in file: "wep_drv.c" in line: 380
S 1 26 14 381 Assert in file: "wep_drv.c" in line: 381
S 1 26 14 382 Assert in file: "wep_drv.c" in line: 382
S 1 20 7 203 Assert in file: "Qbf.c" in line: 203
S 1 20 7 211 Assert in file: "Qbf.c" in line: 211
S 1 20 7 233 Assert in file: "Qbf.c" in line: 233
S 1 20 7 250 Assert in file: "Qbf.c" in line: 250
S 1 20 7 304 Assert in file: "Qbf.c" in line: 304
S 1 20 4 63 Assert in file: "MAC_Addr_Queue.c" in line: 63
S 1 20 1 126 Assert in file: "MT_FifoQ.c" in line: 126
S 1 20 1 161 Assert in file: "MT_FifoQ.c" in line: 161
S 1 20 1 166 Assert in file: "MT_FifoQ.c" in line: 166
S 1 20 1 196 Assert in file: "MT_FifoQ.c" in line: 196
S 1 20 1 226 Assert in file: "MT_FifoQ.c" in line: 226
S 1 20 1 231 Assert in file: "MT_FifoQ.c" in line: 231
S 1 20 1 259 Assert in file: "MT_FifoQ.c" in line: 259
S 1 20 1 293 Assert in file: "MT_FifoQ.c" in line: 293
S 1 20 1 298 Assert in file: "MT_FifoQ.c" in line: 298
S 1 20 1 309 Assert in file: "MT_FifoQ.c" in line: 309
S 1 20 2 138 Assert in file: "MT_TQPB_utility.c" in line: 138
S 1 20 2 259 Assert in file: "MT_TQPB_utility.c" in line: 259
S 1 20 2 284 Assert in file: "MT_TQPB_utility.c" in line: 284
S 1 20 2 340 Assert in file: "MT_TQPB_utility.c" in line: 340
S 1 20 2 376 Assert in file: "MT_TQPB_utility.c" in line: 376
S 1 20 2 463 Assert in file: "MT_TQPB_utility.c" in line: 463
S 1 20 2 467 Assert in file: "MT_TQPB_utility.c" in line: 467
S 1 20 2 530 Assert in file: "MT_TQPB_utility.c" in line: 530
S 1 20 3 336 Assert in file: "queue_utility.c" in line: 336
S 1 20 3 591 Assert in file: "queue_utility.c" in line: 591
S 1 20 3 602 Assert in file: "queue_utility.c" in line: 602
S 1 20 3 749 Assert in file: "queue_utility.c" in line: 749
S 1 20 3 926 Assert in file: "queue_utility.c" in line: 926
S 1 20 3 964 Assert in file: "queue_utility.c" in line: 964
S 1 20 3 968 Assert in file: "queue_utility.c" in line: 968
S 1 20 3 1092 Assert in file: "queue_utility.c" in line: 1092
S 1 28 4 220 Assert in file: "Rx_Manager_API.c" in line: 220
S 1 28 1 397 Assert in file: "rx_manage_task.c" in line: 397
S 1 28 1 407 Assert in file: "rx_manage_task.c" in line: 407
S 1 28 1 424 Assert in file: "rx_manage_task.c" in line: 424
S 1 28 1 436 Assert in file: "rx_manage_task.c" in line: 436
S 1 28 1 482 Assert in file: "rx_manage_task.c" in line: 482
S 1 28 1 484 vRX_ReadyReq
S 1 28 1 598 Assert in file: "rx_manage_task.c" in line: 598
S 1 28 1 601 Assert in file: "rx_manage_task.c" in line: 601
S 1 28 1 619 Assert in file: "rx_manage_task.c" in line: 619
S 1 28 1 648 Assert in file: "rx_manage_task.c" in line: 648
S 1 28 1 956 Assert in file: "rx_manage_task.c" in line: 956
S 1 28 2 557 vRXMPDU_WepCfm, discard packet STAT_RX_DISCARD++ !! 
S 1 28 2 2117 vRXMPDU_DataIn, AUTHENTICATION is encrypted, sending to decryptor.. sid:%d
S 1 28 2 2182 vRXMPDU_DataIn: delete reason:%d
S 1 28 2 2200 Assert in file: "rx_mpdu_task.c" in line: 2200
S 1 28 2 2582 Assert in file: "rx_mpdu_task.c" in line: 2582
S 1 27 2 50 Assert in file: "counter_cbc_mac.c" in line: 50
S 1 27 2 108 Assert in file: "counter_cbc_mac.c" in line: 108
S 1 27 2 109 Assert in file: "counter_cbc_mac.c" in line: 109
S 1 27 2 110 Assert in file: "counter_cbc_mac.c" in line: 110
S 1 27 2 111 Assert in file: "counter_cbc_mac.c" in line: 111
S 1 27 3 185 Assert in file: "michael.c" in line: 185
S 1 27 3 206 Assert in file: "michael.c" in line: 206
S 1 27 3 238 Assert in file: "michael.c" in line: 238
S 1 27 3 252 Assert in file: "michael.c" in line: 252
S 1 27 3 273 Assert in file: "michael.c" in line: 273
S 1 27 3 299 Assert in file: "michael.c" in line: 299
S 1 27 3 307 Assert in file: "michael.c" in line: 307
S 1 27 3 315 Assert in file: "michael.c" in line: 315
S 1 27 3 323 Assert in file: "michael.c" in line: 323
S 1 27 3 335 Assert in file: "michael.c" in line: 335
S 1 27 4 58 Assert in file: "rc4_cipher.c" in line: 58
S 1 27 5 85 Assert in file: "wep_algorithm.c" in line: 85
S 1 27 5 147 Assert in file: "wep_algorithm.c" in line: 147
S 1 27 5 250 Assert in file: "wep_algorithm.c" in line: 250
S 1 27 5 251 Assert in file: "wep_algorithm.c" in line: 251
S 1 27 5 252 Assert in file: "wep_algorithm.c" in line: 252
S 1 27 5 253 Assert in file: "wep_algorithm.c" in line: 253
S 1 27 31 90 Assert in file: "cipher_shared_ram_db.c" in line: 90
S 1 27 31 91 Assert in file: "cipher_shared_ram_db.c" in line: 91
S 1 27 31 148 Assert in file: "cipher_shared_ram_db.c" in line: 148
S 1 27 31 150 Assert in file: "cipher_shared_ram_db.c" in line: 150
S 1 27 31 181 Assert in file: "cipher_shared_ram_db.c" in line: 181
S 1 27 31 182 Assert in file: "cipher_shared_ram_db.c" in line: 182
S 1 27 31 184 Assert in file: "cipher_shared_ram_db.c" in line: 184
S 1 27 31 213 Assert in file: "cipher_shared_ram_db.c" in line: 213
S 1 27 6 105 Assert in file: "cipher_suite.c" in line: 105
S 1 27 6 106 Assert in file: "cipher_suite.c" in line: 106
S 1 27 6 126 Assert in file: "cipher_suite.c" in line: 126
S 1 27 6 127 Assert in file: "cipher_suite.c" in line: 127
S 1 27 6 161 Assert in file: "cipher_suite.c" in line: 161
S 1 27 6 210 Assert in file: "cipher_suite.c" in line: 210
S 1 27 6 211 Assert in file: "cipher_suite.c" in line: 211
S 1 27 6 212 Assert in file: "cipher_suite.c" in line: 212
S 1 27 6 273 Assert in file: "cipher_suite.c" in line: 273
S 1 27 6 274 Assert in file: "cipher_suite.c" in line: 274
S 1 27 6 275 Assert in file: "cipher_suite.c" in line: 275
S 1 27 6 276 Assert in file: "cipher_suite.c" in line: 276
S 1 27 6 292 Assert in file: "cipher_suite.c" in line: 292
S 1 27 6 318 Assert in file: "cipher_suite.c" in line: 318
S 1 27 6 319 Assert in file: "cipher_suite.c" in line: 319
S 1 27 6 356 Assert in file: "cipher_suite.c" in line: 356
S 1 27 6 357 Assert in file: "cipher_suite.c" in line: 357
S 1 27 6 359 Assert in file: "cipher_suite.c" in line: 359
S 1 27 6 361 Assert in file: "cipher_suite.c" in line: 361
S 1 27 6 397 Assert in file: "cipher_suite.c" in line: 397
S 1 27 6 398 Assert in file: "cipher_suite.c" in line: 398
S 1 27 6 401 Assert in file: "cipher_suite.c" in line: 401
S 1 27 6 403 Assert in file: "cipher_suite.c" in line: 403
S 1 27 6 404 Assert in file: "cipher_suite.c" in line: 404
S 1 27 6 422 pThis->psFuncSpecialisations->pfnSetTk == NULL
S 1 27 6 443 Assert in file: "cipher_suite.c" in line: 443
S 1 27 6 463 Assert in file: "cipher_suite.c" in line: 463
S 1 27 6 464 Assert in file: "cipher_suite.c" in line: 464
S 1 27 6 507 Assert in file: "cipher_suite.c" in line: 507
S 1 27 6 508 Assert in file: "cipher_suite.c" in line: 508
S 1 27 6 536 Assert in file: "cipher_suite.c" in line: 536
S 1 27 6 593 Assert in file: "cipher_suite.c" in line: 593
S 1 27 6 699 Assert in file: "cipher_suite.c" in line: 699
S 1 27 6 700 Assert in file: "cipher_suite.c" in line: 700
S 1 27 7 132 Assert in file: "cipher_suite_ccmp.c" in line: 132
S 1 27 7 163 Assert in file: "cipher_suite_ccmp.c" in line: 163
S 1 27 7 166 Assert in file: "cipher_suite_ccmp.c" in line: 166
S 1 27 7 229 Assert in file: "cipher_suite_ccmp.c" in line: 229
S 1 27 7 230 Assert in file: "cipher_suite_ccmp.c" in line: 230
S 1 27 7 233 Assert in file: "cipher_suite_ccmp.c" in line: 233
S 1 27 7 346 Assert in file: "cipher_suite_ccmp.c" in line: 346
S 1 27 7 347 Assert in file: "cipher_suite_ccmp.c" in line: 347
S 1 27 7 385 Assert in file: "cipher_suite_ccmp.c" in line: 385
S 1 27 7 481 Assert in file: "cipher_suite_ccmp.c" in line: 481
S 1 27 7 482 Assert in file: "cipher_suite_ccmp.c" in line: 482
S 1 27 7 519 Assert in file: "cipher_suite_ccmp.c" in line: 519
S 1 27 7 524 Assert in file: "cipher_suite_ccmp.c" in line: 524
S 1 27 7 557 Assert in file: "cipher_suite_ccmp.c" in line: 557
S 1 27 7 581 Assert in file: "cipher_suite_ccmp.c" in line: 581
S 1 27 7 582 Assert in file: "cipher_suite_ccmp.c" in line: 582
S 1 27 7 583 Assert in file: "cipher_suite_ccmp.c" in line: 583
S 1 27 7 613 Assert in file: "cipher_suite_ccmp.c" in line: 613
S 1 27 7 614 Assert in file: "cipher_suite_ccmp.c" in line: 614
S 1 27 7 615 Assert in file: "cipher_suite_ccmp.c" in line: 615
S 1 27 7 644 Assert in file: "cipher_suite_ccmp.c" in line: 644
S 1 27 7 645 Assert in file: "cipher_suite_ccmp.c" in line: 645
S 1 27 7 704 Assert in file: "cipher_suite_ccmp.c" in line: 704
S 1 27 7 728 Assert in file: "cipher_suite_ccmp.c" in line: 728
S 1 27 7 785 Assert in file: "cipher_suite_ccmp.c" in line: 785
S 1 27 8 74 Assert in file: "cipher_suite_rsn.c" in line: 74
S 1 27 8 114 Assert in file: "cipher_suite_rsn.c" in line: 114
S 1 27 8 149 Assert in file: "cipher_suite_rsn.c" in line: 149
S 1 27 8 151 Assert in file: "cipher_suite_rsn.c" in line: 151
S 1 27 8 153 Assert in file: "cipher_suite_rsn.c" in line: 153
S 1 27 8 204 Assert in file: "cipher_suite_rsn.c" in line: 204
S 1 27 8 205 Assert in file: "cipher_suite_rsn.c" in line: 205
S 1 27 8 206 Assert in file: "cipher_suite_rsn.c" in line: 206
S 1 27 8 255 Assert in file: "cipher_suite_rsn.c" in line: 255
S 1 27 8 332 Assert in file: "cipher_suite_rsn.c" in line: 332
S 1 27 8 333 Assert in file: "cipher_suite_rsn.c" in line: 333
S 1 27 8 335 Assert in file: "cipher_suite_rsn.c" in line: 335
S 1 27 8 359 Assert in file: "cipher_suite_rsn.c" in line: 359
S 1 27 8 403 Assert in file: "cipher_suite_rsn.c" in line: 403
S 1 27 8 404 Assert in file: "cipher_suite_rsn.c" in line: 404
S 1 27 8 417 Assert in file: "cipher_suite_rsn.c" in line: 417
S 1 27 8 451 Assert in file: "cipher_suite_rsn.c" in line: 451
S 1 27 9 132 Assert in file: "cipher_suite_shram_dma.c" in line: 132
S 1 27 1 243 Assert in file: "cipher_suite_tkip.c" in line: 243
S 1 27 1 281 Assert in file: "cipher_suite_tkip.c" in line: 281
S 1 27 1 316 Assert in file: "cipher_suite_tkip.c" in line: 316
S 1 27 1 401 Assert in file: "cipher_suite_tkip.c" in line: 401
S 1 27 1 407 Assert in file: "cipher_suite_tkip.c" in line: 407
S 1 27 1 408 Assert in file: "cipher_suite_tkip.c" in line: 408
S 1 27 1 411 Assert in file: "cipher_suite_tkip.c" in line: 411
S 1 27 1 480 Assert in file: "cipher_suite_tkip.c" in line: 480
S 1 27 1 481 Assert in file: "cipher_suite_tkip.c" in line: 481
S 1 27 1 485 Assert in file: "cipher_suite_tkip.c" in line: 485
S 1 27 1 625 Assert in file: "cipher_suite_tkip.c" in line: 625
S 1 27 1 626 Assert in file: "cipher_suite_tkip.c" in line: 626
S 1 27 1 632 Assert in file: "cipher_suite_tkip.c" in line: 632
S 1 27 1 710 boCIPH_TKIP_DoDecrypt, TKIP frag
S 1 27 1 758 Assert in file: "cipher_suite_tkip.c" in line: 758
S 1 27 1 824 Assert in file: "cipher_suite_tkip.c" in line: 824
S 1 27 1 825 Assert in file: "cipher_suite_tkip.c" in line: 825
S 1 27 1 828 Assert in file: "cipher_suite_tkip.c" in line: 828
S 1 27 1 874 Assert in file: "cipher_suite_tkip.c" in line: 874
S 1 27 1 900 Assert in file: "cipher_suite_tkip.c" in line: 900
S 1 27 1 901 Assert in file: "cipher_suite_tkip.c" in line: 901
S 1 27 1 1056 Fatal Error in file: "cipher_suite_tkip.c"; Fatal Print: Not Supported
S 1 27 1 1139 Assert in file: "cipher_suite_tkip.c" in line: 1139
S 1 27 1 1147 Assert in file: "cipher_suite_tkip.c" in line: 1147
S 1 27 1 1300 Assert in file: "cipher_suite_tkip.c" in line: 1300
S 1 27 1 1447 Assert in file: "cipher_suite_tkip.c" in line: 1447
S 1 27 1 1448 Assert in file: "cipher_suite_tkip.c" in line: 1448
S 1 27 1 1453 Assert in file: "cipher_suite_tkip.c" in line: 1453
S 1 27 1 1587 Assert in file: "cipher_suite_tkip.c" in line: 1587
S 1 27 1 1603 ------tCIPH_TKIP_CheckRxMic: RSN_STATUS_TKIP_MIC_FAILURE -------------------------------
S 1 27 1 1848 Assert in file: "cipher_suite_tkip.c" in line: 1848
S 1 27 1 1849 Assert in file: "cipher_suite_tkip.c" in line: 1849
S 1 27 1 1850 Assert in file: "cipher_suite_tkip.c" in line: 1850
S 1 27 10 130 Assert in file: "cipher_suite_wep.c" in line: 130
S 1 27 10 159 Assert in file: "cipher_suite_wep.c" in line: 159
S 1 27 10 216 Assert in file: "cipher_suite_wep.c" in line: 216
S 1 27 10 217 Assert in file: "cipher_suite_wep.c" in line: 217
S 1 27 10 237 Assert in file: "cipher_suite_wep.c" in line: 237
S 1 27 10 238 Assert in file: "cipher_suite_wep.c" in line: 238
S 1 27 10 257 Assert in file: "cipher_suite_wep.c" in line: 257
S 1 27 10 258 Assert in file: "cipher_suite_wep.c" in line: 258
S 1 27 10 404 Assert in file: "cipher_suite_wep.c" in line: 404
S 1 27 10 405 Assert in file: "cipher_suite_wep.c" in line: 405
S 1 27 10 514 Assert in file: "cipher_suite_wep.c" in line: 514
S 1 27 10 515 Assert in file: "cipher_suite_wep.c" in line: 515
S 1 27 10 542 Assert in file: "cipher_suite_wep.c" in line: 542
S 1 27 10 592 Assert in file: "cipher_suite_wep.c" in line: 592
S 1 27 10 629 Assert in file: "cipher_suite_wep.c" in line: 629
S 1 27 10 655 Assert in file: "cipher_suite_wep.c" in line: 655
S 1 27 10 683 Assert in file: "cipher_suite_wep.c" in line: 683
S 1 27 10 703 Assert in file: "cipher_suite_wep.c" in line: 703
S 1 27 11 410 Assert in file: "encryptor.c" in line: 410
S 1 27 11 411 Assert in file: "encryptor.c" in line: 411
S 1 27 11 420 Assert in file: "encryptor.c" in line: 420
S 1 27 11 421 Assert in file: "encryptor.c" in line: 421
S 1 27 11 487 Assert in file: "encryptor.c" in line: 487
S 1 27 11 488 Assert in file: "encryptor.c" in line: 488
S 1 27 11 510 Assert in file: "encryptor.c" in line: 510
S 1 27 11 682 Assert in file: "encryptor.c" in line: 682
S 1 27 11 705 Assert in file: "encryptor.c" in line: 705
S 1 27 11 1200 Assert in file: "encryptor.c" in line: 1200
S 1 27 11 1270 vENC_HwComplete: DECRYPTION_FAILED
S 1 27 11 1295 Assert in file: "encryptor.c" in line: 1295
S 1 27 11 1317 Assert in file: "encryptor.c" in line: 1317
S 1 27 11 1318 Assert in file: "encryptor.c" in line: 1318
S 1 27 11 1355 Assert in file: "encryptor.c" in line: 1355
S 1 27 11 1388 Assert in file: "encryptor.c" in line: 1388
S 1 27 11 1435 Assert in file: "encryptor.c" in line: 1435
S 1 27 11 1725 Assert in file: "encryptor.c" in line: 1725
S 1 27 11 1727 Assert in file: "encryptor.c" in line: 1727
S 1 27 11 1728 Assert in file: "encryptor.c" in line: 1728
S 1 27 11 1729 Assert in file: "encryptor.c" in line: 1729
S 1 27 11 1735 Assert in file: "encryptor.c" in line: 1735
S 1 27 11 1736 Assert in file: "encryptor.c" in line: 1736
S 1 27 11 1751 Assert in file: "encryptor.c" in line: 1751
S 1 27 11 1823 Assert in file: "encryptor.c" in line: 1823
S 1 27 11 1824 Assert in file: "encryptor.c" in line: 1824
S 1 27 12 56 Assert in file: "fsdu.c" in line: 56
S 1 27 12 88 Assert in file: "fsdu.c" in line: 88
S 1 27 12 123 Assert in file: "fsdu.c" in line: 123
S 1 27 13 85 Assert in file: "key.c" in line: 85
S 1 27 13 87 Assert in file: "key.c" in line: 87
S 1 27 13 89 Assert in file: "key.c" in line: 89
S 1 27 13 90 Assert in file: "key.c" in line: 90
S 1 27 13 91 Assert in file: "key.c" in line: 91
S 1 27 13 131 Assert in file: "key.c" in line: 131
S 1 27 14 79 Assert in file: "key_manager.c" in line: 79
S 1 27 14 85 vUM_MAN_SET_KEY_REQ, u16KeyType:%d, u16CipherSuite:%d, u16DefaultKeyIndex:%d, u16StationRole:%d
S 1 27 14 99 vUM_MAN_SET_KEY_REQ: u16Status:%d psMsg->vapId:%d
S 1 27 14 119 Assert in file: "key_manager.c" in line: 119
S 1 27 14 161 u16KEYM_SetKey, got UMI_RSN_CIPHER_SUITE_IGTK
S 1 27 14 168 u16KEYM_SetKey: u16CipherSuite = %d
S 1 27 14 186 u16KEYM_SetKey, boIsGroup = %d
S 1 27 14 240 Assert in file: "key_manager.c" in line: 240
S 1 27 14 314 u16KEYM_SetKey: VapDBptr->numOfPeerWepAP++ = %d, VapDBptr->numOfPeerAP = %d, vapIndex = %d
S 1 27 14 379 Assert in file: "key_manager.c" in line: 379
S 1 27 14 425 Assert in file: "key_manager.c" in line: 425
S 1 27 15 93 Assert in file: "one_x_filter.c" in line: 93
S 1 27 15 113 Assert in file: "one_x_filter.c" in line: 113
S 1 27 15 132 Assert in file: "one_x_filter.c" in line: 132
S 1 27 15 154 Assert in file: "one_x_filter.c" in line: 154
S 1 27 15 155 Assert in file: "one_x_filter.c" in line: 155
S 1 27 15 183 Assert in file: "one_x_filter.c" in line: 183
S 1 27 15 184 Assert in file: "one_x_filter.c" in line: 184
S 1 27 16 70 Assert in file: "replay_window.c" in line: 70
S 1 27 16 92 Assert in file: "replay_window.c" in line: 92
S 1 27 16 115 Assert in file: "replay_window.c" in line: 115
S 1 27 16 116 Assert in file: "replay_window.c" in line: 116
S 1 27 16 143 Assert in file: "replay_window.c" in line: 143
S 1 27 16 144 Assert in file: "replay_window.c" in line: 144
S 1 27 16 198 Assert in file: "replay_window.c" in line: 198
S 1 27 16 243 Assert in file: "replay_window.c" in line: 243
S 1 27 16 275 Assert in file: "replay_window.c" in line: 275
S 1 5 1 66 Assert in file: "rsn_caps.c" in line: 66
S 1 5 1 105 Assert in file: "rsn_caps.c" in line: 105
S 1 5 1 127 Assert in file: "rsn_caps.c" in line: 127
S 1 5 1 128 Assert in file: "rsn_caps.c" in line: 128
S 1 5 1 155 Assert in file: "rsn_caps.c" in line: 155
S 1 5 1 156 Assert in file: "rsn_caps.c" in line: 156
S 1 5 1 178 Assert in file: "rsn_caps.c" in line: 178
S 1 5 1 179 Assert in file: "rsn_caps.c" in line: 179
S 1 5 1 208 Assert in file: "rsn_caps.c" in line: 208
S 1 5 1 209 Assert in file: "rsn_caps.c" in line: 209
S 1 5 1 233 Assert in file: "rsn_caps.c" in line: 233
S 1 5 2 63 Assert in file: "rsn_ie_ieee.c" in line: 63
S 1 5 2 64 Assert in file: "rsn_ie_ieee.c" in line: 64
S 1 5 2 101 Assert in file: "rsn_ie_ieee.c" in line: 101
S 1 5 2 176 Assert in file: "rsn_ie_ieee.c" in line: 176
S 1 5 2 197 Assert in file: "rsn_ie_ieee.c" in line: 197
S 1 5 2 219 Assert in file: "rsn_ie_ieee.c" in line: 219
S 1 5 2 240 Assert in file: "rsn_ie_ieee.c" in line: 240
S 1 5 2 261 Assert in file: "rsn_ie_ieee.c" in line: 261
S 1 5 3 63 Assert in file: "rsn_ie_weca.c" in line: 63
S 1 5 3 64 Assert in file: "rsn_ie_weca.c" in line: 64
S 1 5 3 102 Assert in file: "rsn_ie_weca.c" in line: 102
S 1 5 3 178 Assert in file: "rsn_ie_weca.c" in line: 178
S 1 5 3 206 Assert in file: "rsn_ie_weca.c" in line: 206
S 1 5 3 228 Assert in file: "rsn_ie_weca.c" in line: 228
S 1 5 3 249 Assert in file: "rsn_ie_weca.c" in line: 249
S 1 5 3 273 Assert in file: "rsn_ie_weca.c" in line: 273
S 1 5 4 63 Assert in file: "rsn_info.c" in line: 63
S 1 5 4 92 Assert in file: "rsn_info.c" in line: 92
S 1 5 5 125 Assert in file: "rsn_interface.c" in line: 125
S 1 5 5 181 Assert in file: "rsn_interface.c" in line: 181
S 1 5 5 182 Assert in file: "rsn_interface.c" in line: 182
S 1 5 5 233 Assert in file: "rsn_interface.c" in line: 233
S 1 5 6 160 Assert in file: "rsn_manager.c" in line: 160
S 1 5 6 202 Assert in file: "rsn_manager.c" in line: 202
S 1 5 6 224 Assert in file: "rsn_manager.c" in line: 224
S 1 5 6 243 Assert in file: "rsn_manager.c" in line: 243
S 1 5 6 267 Assert in file: "rsn_manager.c" in line: 267
S 1 5 6 298 Assert in file: "rsn_manager.c" in line: 298
S 1 5 6 299 Assert in file: "rsn_manager.c" in line: 299
S 1 5 6 401 Assert in file: "rsn_manager.c" in line: 401
S 1 5 6 738 Assert in file: "rsn_manager.c" in line: 738
S 1 5 6 768 Assert in file: "rsn_manager.c" in line: 768
S 1 5 6 793 Assert in file: "rsn_manager.c" in line: 793
S 1 27 22 61 Assert in file: "security_log.c" in line: 61
S 1 27 22 81 Assert in file: "security_log.c" in line: 81
S 1 27 22 82 Assert in file: "security_log.c" in line: 82
S 1 27 22 109 Assert in file: "security_log.c" in line: 109
S 1 27 22 110 Assert in file: "security_log.c" in line: 110
S 1 27 22 166 Assert in file: "security_log.c" in line: 166
S 1 27 22 191 Assert in file: "security_log.c" in line: 191
S 1 27 23 54 Assert in file: "seq_num.c" in line: 54
S 1 27 23 73 Assert in file: "seq_num.c" in line: 73
S 1 27 23 91 Assert in file: "seq_num.c" in line: 91
S 1 27 23 111 Assert in file: "seq_num.c" in line: 111
S 1 27 23 135 Assert in file: "seq_num.c" in line: 135
S 1 27 23 136 Assert in file: "seq_num.c" in line: 136
S 1 27 23 161 Assert in file: "seq_num.c" in line: 161
S 1 27 23 162 Assert in file: "seq_num.c" in line: 162
S 1 27 24 210 Assert in file: "tkip_key_mixing.c" in line: 210
S 1 27 24 211 Assert in file: "tkip_key_mixing.c" in line: 211
S 1 27 24 219 Assert in file: "tkip_key_mixing.c" in line: 219
S 1 27 24 220 Assert in file: "tkip_key_mixing.c" in line: 220
S 1 27 24 224 Assert in file: "tkip_key_mixing.c" in line: 224
S 1 27 25 88 Assert in file: "tx_buffer_fragment.c" in line: 88
S 1 27 25 89 Assert in file: "tx_buffer_fragment.c" in line: 89
S 1 27 25 90 Assert in file: "tx_buffer_fragment.c" in line: 90
S 1 27 25 91 Assert in file: "tx_buffer_fragment.c" in line: 91
S 1 27 25 144 Assert in file: "tx_buffer_fragment.c" in line: 144
S 1 27 25 145 Assert in file: "tx_buffer_fragment.c" in line: 145
S 1 27 25 252 Assert in file: "tx_buffer_fragment.c" in line: 252
S 1 27 25 284 Assert in file: "tx_buffer_fragment.c" in line: 284
S 1 27 25 285 Assert in file: "tx_buffer_fragment.c" in line: 285
S 1 27 25 306 Assert in file: "tx_buffer_fragment.c" in line: 306
S 1 27 26 72 Assert in file: "wep_iv.c" in line: 72
S 1 27 26 73 Assert in file: "wep_iv.c" in line: 73
S 1 27 27 63 Assert in file: "wep_mib.c" in line: 63
S 1 27 27 64 Assert in file: "wep_mib.c" in line: 64
S 1 27 27 100 Assert in file: "wep_mib.c" in line: 100
S 1 27 27 101 Assert in file: "wep_mib.c" in line: 101
S 1 29 1 103 Assert in file: "fake_cipher_suite.c" in line: 103
S 1 29 1 104 Assert in file: "fake_cipher_suite.c" in line: 104
S 1 29 1 123 Assert in file: "fake_cipher_suite.c" in line: 123
S 1 29 1 143 Assert in file: "fake_cipher_suite.c" in line: 143
S 1 29 1 144 Assert in file: "fake_cipher_suite.c" in line: 144
S 1 29 1 145 Assert in file: "fake_cipher_suite.c" in line: 145
S 1 29 1 177 Assert in file: "fake_cipher_suite.c" in line: 177
S 1 29 1 178 Assert in file: "fake_cipher_suite.c" in line: 178
S 1 29 1 206 Assert in file: "fake_cipher_suite.c" in line: 206
S 1 29 1 226 Assert in file: "fake_cipher_suite.c" in line: 226
S 1 29 1 227 Assert in file: "fake_cipher_suite.c" in line: 227
S 1 29 1 228 Assert in file: "fake_cipher_suite.c" in line: 228
S 1 29 1 259 Assert in file: "fake_cipher_suite.c" in line: 259
S 1 29 1 260 Assert in file: "fake_cipher_suite.c" in line: 260
S 1 29 1 261 Assert in file: "fake_cipher_suite.c" in line: 261
S 1 29 1 292 Assert in file: "fake_cipher_suite.c" in line: 292
S 1 29 1 293 Assert in file: "fake_cipher_suite.c" in line: 293
S 1 29 1 294 Assert in file: "fake_cipher_suite.c" in line: 294
S 1 29 1 316 Assert in file: "fake_cipher_suite.c" in line: 316
S 1 29 1 317 Assert in file: "fake_cipher_suite.c" in line: 317
S 1 29 1 318 Assert in file: "fake_cipher_suite.c" in line: 318
S 1 29 1 319 Assert in file: "fake_cipher_suite.c" in line: 319
S 1 29 1 336 Assert in file: "fake_cipher_suite.c" in line: 336
S 1 29 1 353 Assert in file: "fake_cipher_suite.c" in line: 353
S 1 29 1 370 Assert in file: "fake_cipher_suite.c" in line: 370
S 1 29 1 425 Assert in file: "fake_cipher_suite.c" in line: 425
S 1 29 1 432 Assert in file: "fake_cipher_suite.c" in line: 432
S 1 29 1 438 Assert in file: "fake_cipher_suite.c" in line: 438
S 1 29 2 205 Assert in file: "test_encryptor.c" in line: 205
S 1 29 2 222 Assert in file: "test_encryptor.c" in line: 222
S 1 29 2 227 Assert in file: "test_encryptor.c" in line: 227
S 1 29 2 237 Assert in file: "test_encryptor.c" in line: 237
S 1 29 2 256 Assert in file: "test_encryptor.c" in line: 256
S 1 29 2 261 Assert in file: "test_encryptor.c" in line: 261
S 1 29 2 313 Assert in file: "test_encryptor.c" in line: 313
S 1 29 4 192 Assert in file: "test_one_x_filter.c" in line: 192
S 1 29 4 241 Assert in file: "test_one_x_filter.c" in line: 241
S 1 29 4 285 Assert in file: "test_one_x_filter.c" in line: 285
S 1 29 4 325 Assert in file: "test_one_x_filter.c" in line: 325
S 1 29 5 198 Assert in file: "test_tkip_key_mixing.c" in line: 198
S 1 29 5 210 Assert in file: "test_tkip_key_mixing.c" in line: 210
S 1 29 6 772 Assert in file: "test_tkip_rx_buffer.c" in line: 772
S 1 29 6 782 Assert in file: "test_tkip_rx_buffer.c" in line: 782
S 1 29 6 783 Assert in file: "test_tkip_rx_buffer.c" in line: 783
S 1 29 6 784 Assert in file: "test_tkip_rx_buffer.c" in line: 784
S 1 29 6 785 Assert in file: "test_tkip_rx_buffer.c" in line: 785
S 1 29 6 786 Assert in file: "test_tkip_rx_buffer.c" in line: 786
S 1 29 6 787 Assert in file: "test_tkip_rx_buffer.c" in line: 787
S 1 29 6 797 Assert in file: "test_tkip_rx_buffer.c" in line: 797
S 1 29 7 397 Assert in file: "test_tx_buffer_fragment.c" in line: 397
S 1 29 7 398 Assert in file: "test_tx_buffer_fragment.c" in line: 398
S 1 29 7 399 Assert in file: "test_tx_buffer_fragment.c" in line: 399
S 1 29 7 400 Assert in file: "test_tx_buffer_fragment.c" in line: 400
S 1 29 7 401 Assert in file: "test_tx_buffer_fragment.c" in line: 401
S 1 29 7 410 Assert in file: "test_tx_buffer_fragment.c" in line: 410
S 1 29 7 413 Assert in file: "test_tx_buffer_fragment.c" in line: 413
S 1 29 7 418 Assert in file: "test_tx_buffer_fragment.c" in line: 418
S 1 23 9 64 Assert in file: "btdebug.h" in line: 64
S 1 23 1 204 Assert in file: "mt_chipreg.c" in line: 204
S 1 23 1 236 Assert in file: "mt_chipreg.c" in line: 236
S 1 23 2 407 Assert in file: "mt_osint.c" in line: 407
S 1 23 2 425 Assert in file: "mt_osint.c" in line: 425
S 1 23 2 449 Assert in file: "mt_osint.c" in line: 449
S 1 7 4 295 LBF_ApplySet()isQbfEnable = %d
S 1 7 4 336 LBF_ApplySet():LBF_RA_PROBING_PACKET set: MAT: %d,  CDD: %d
S 1 7 4 400 Assert in file: "LBF.c" in line: 400
S 1 7 4 401 LBF_ProcessFeedback(): nextProbe CDDindex = %d
S 1 7 4 500 LBF_ProcessFeedback psDBentry->LBFstate =%d psDBentry->RFB_IsStable = %d 
S 1 7 4 507 LBF_ProcessFeedback set %d tableIndx=%d
S 1 7 4 513 Assert in file: "LBF.c" in line: 513
S 1 7 4 522 LBF_ProcessFeedback(): 1)REGULAR_PACKET LBFind= %d set = %d
S 1 7 4 526 LBF_ProcessFeedback(): 2)LBF_PROBING_PACKET LBFind= %d set = %d
S 1 7 4 530 LBF_ProcessFeedback(): 3)PROBING_PACKET LBFind= %d set = %d
S 1 7 4 556 Assert in file: "LBF.c" in line: 556
S 1 7 4 560 LBF_ProcessFeedback(): setIndx = %d LBFind = %d 
S 1 7 4 562 Assert in file: "LBF.c" in line: 562
S 1 7 4 564 Assert in file: "LBF.c" in line: 564
S 1 7 4 681 Assert in file: "LBF.c" in line: 681
S 1 7 4 850 LBF_SelectBestLBFsets()  pLBFstats->u8RateIdx = %d psDBentry->LBFmask = %d pLBFstats->u16TxTries = %d 
S 1 7 4 889 LBF_SelectBestLBFsets(): bestCDDsetIndex= %d SecondbestCDDsetIndex = %d
S 1 7 4 894 Assert in file: "LBF.c" in line: 894
S 1 7 4 948 Assert in file: "LBF.c" in line: 948
S 1 7 4 956 LBF_SelectProbingSet() lastProbeWasQbf= %d setInd = %d lastProbeInd = %d setsOffset =%d
S 1 7 4 965 SelectProbingSet(): setInd = %d setsOffset = %d LBFmask = 0X%x totalSets = %d setsOffset =%d
S 1 7 4 972 QBF setInd = %d
S 1 7 4 981 CDD setInd = %d
S 1 7 4 988 Assert in file: "LBF.c" in line: 988
S 1 7 4 992 LBF_SelectProbingSet() selectedProbe= %d 
S 1 7 4 1047 ProbingSet, lbfRankMask=%X, bestLBFsetIndx=%d, bestSetRetries=%d, qbfIsbestSet=%d
S 1 7 4 1063 Set %d tableindx %d, Tries=%d, Retries=%d, acked=%d
S 1 7 4 1070 set %d not in DB
S 1 7 4 1079 Add set %d to relevant set, numOfSet=%d
S 1 7 4 1084 QBFProbing= %d
S 1 7 4 1176 UpdateTwoAnt ForAllStations MAC = 0X%x%x%x%x%x%x 
S 1 7 5 208 Assert in file: "MT_RFManagement.c" in line: 208
S 1 7 5 290 Assert in file: "MT_RFManagement.c" in line: 290
S 1 7 5 324 Assert in file: "MT_RFManagement.c" in line: 324
S 1 7 5 393 Assert in file: "MT_RFManagement.c" in line: 393
S 1 7 5 420 Assert in file: "MT_RFManagement.c" in line: 420
S 1 7 5 575 Assert in file: "MT_RFManagement.c" in line: 575
S 1 7 6 540 Assert in file: "MT_UMA_aggr_data_task.c" in line: 540
S 1 7 6 857 vUM_MAN_OPEN_AGGR_REQ, Index - %d, total - %d
S 1 7 6 863 Assert in file: "MT_UMA_aggr_data_task.c" in line: 863
S 1 7 6 868 Fatal Error in file: "MT_UMA_aggr_data_task.c"; Fatal Print:  Open Aggr : Aggr is Already Open 
S 1 7 6 871 vUM_MAN_OPEN_AGGR_REQ Failed, AGGR already open
S 1 7 6 875 Fatal Error in file: "MT_UMA_aggr_data_task.c"; Fatal Print:  Open Aggr : No Entry found for STA
S 1 7 6 877 vUM_MAN_OPEN_AGGR_REQ Failed, STA not in DB
S 1 7 6 926 Assert in file: "MT_UMA_aggr_data_task.c" in line: 926
S 1 7 6 927 Assert in file: "MT_UMA_aggr_data_task.c" in line: 927
S 1 7 6 929 Assert in file: "MT_UMA_aggr_data_task.c" in line: 929
S 1 7 6 975 Assert in file: "MT_UMA_aggr_data_task.c" in line: 975
S 1 7 6 1003 Assert in file: "MT_UMA_aggr_data_task.c" in line: 1003
S 1 7 6 1014 Close AGGR Failed, STA not in DB
S 1 7 6 1021 Fatal Error in file: "MT_UMA_aggr_data_task.c"; Fatal Print: STA is NULL
S 1 7 6 1031 TS Clean, STA - %Y, Priority - %d, Index - %d, num - %d
S 1 7 6 1103 Assert in file: "MT_UMA_aggr_data_task.c" in line: 1103
S 1 7 6 1122 vUM_MAN_ADDBA_REQ_TX: priority %x, token %d, timeout %d
S 1 7 6 1139 vUM_MAN_ADDBA_REQ_TX: sta %d, priority %d, sizeof payload:%d
S 1 7 6 1169 vUM_MAN_ADDBA_REQ_TX, UMI_STATION_UNKNOWN
S 1 7 6 1194 vUM_MAN_ADDBA_RES_TX: sta %d
S 1 7 6 1262 vUM_MAN_DELBA_REQ_TX: priority %x, reason %d
S 1 7 6 1400 Assert in file: "MT_UMA_aggr_data_task.c" in line: 1400
S 1 7 6 1428 Assert in file: "MT_UMA_aggr_data_task.c" in line: 1428
S 1 7 6 1590 Assert in file: "MT_UMA_aggr_data_task.c" in line: 1590
S 1 7 6 1868 Assert in file: "MT_UMA_aggr_data_task.c" in line: 1868
S 1 7 6 1940 Assert in file: "MT_UMA_aggr_data_task.c" in line: 1940
S 1 7 6 2000 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2000
S 1 7 6 2048 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2048
S 1 7 6 2110 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2110
S 1 7 6 2114 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2114
S 1 7 6 2124 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2124
S 1 7 6 2145 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2145
S 1 7 6 2150 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2150
S 1 7 6 2162 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2162
S 1 7 6 2311 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2311
S 1 7 6 2325 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2325
S 1 7 6 2444 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2444
S 1 7 6 2540 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2540
S 1 7 6 2552 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2552
S 1 7 6 2565 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2565
S 1 7 6 2756 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2756
S 1 7 6 2839 Assert in file: "MT_UMA_aggr_data_task.c" in line: 2839
S 1 7 6 3056 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3056
S 1 7 6 3059 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3059
S 1 7 6 3114 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3114
S 1 7 6 3260 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3260
S 1 7 6 3383 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3383
S 1 7 6 3391 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3391
S 1 7 6 3392 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3392
S 1 7 6 3422 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3422
S 1 7 6 3434 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3434
S 1 7 6 3436 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3436
S 1 7 6 3477 MT_UMA_AggregateNackEvent: Consecutive NACKs SID=%d, SeqNackWeight=%d, SeqNackTsf=%u, txRate=%d, extRate=%d, time=%u, MIB NackWeight=%d, NackTimes=%d
S 1 7 6 3649 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3649
S 1 7 6 3656 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3656
S 1 7 6 3660 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3660
S 1 7 6 3829 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3829
S 1 7 6 3853 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3853
S 1 7 6 3896 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3896
S 1 7 6 3900 Assert in file: "MT_UMA_aggr_data_task.c" in line: 3900
S 1 7 6 4177 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4177
S 1 7 6 4184 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4184
S 1 7 6 4192 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4192
S 1 7 6 4197 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4197
S 1 7 6 4198 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4198
S 1 7 6 4199 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4199
S 1 7 6 4200 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4200
S 1 7 6 4356 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4356
S 1 7 6 4363 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4363
S 1 7 6 4426 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4426
S 1 7 6 4429 MT_UMA_postponeAggInTs, SID - %d, prio - %d
S 1 7 6 4433 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4433
S 1 7 6 4641 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4641
S 1 7 6 4703 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4703
S 1 7 6 4707 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4707
S 1 7 6 4736 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4736
S 1 7 6 4750 Assert in file: "MT_UMA_aggr_data_task.c" in line: 4750
S 1 7 7 160 Assert in file: "MT_UMA_ba_wnd.c" in line: 160
S 1 7 7 164 Assert in file: "MT_UMA_ba_wnd.c" in line: 164
S 1 7 7 724 Assert in file: "MT_UMA_ba_wnd.c" in line: 724
S 1 7 2 410 Assert in file: "rate_fallback.c" in line: 410
S 1 7 2 565 Assert in file: "rate_fallback.c" in line: 565
S 1 7 2 696 Fatal Error in file: "rate_fallback.c"; Fatal Print: Unknown protocol
S 1 7 2 928 Fatal Error in file: "rate_fallback.c"; Fatal Print: Unknown protocol
S 1 7 2 997 Assert in file: "rate_fallback.c" in line: 997
S 1 7 2 1087 u16RFB_GetFallbackRate: SID=%d, Current Rate=%d, min rate=%d, max rate=%d rate mask=0x%x
S 1 7 2 1088 Assert in file: "rate_fallback.c" in line: 1088
S 1 7 2 1663 Assert in file: "rate_fallback.c" in line: 1663
S 1 7 2 1672 Assert in file: "rate_fallback.c" in line: 1672
S 1 7 2 1697 Assert in file: "rate_fallback.c" in line: 1697
S 1 7 2 1703 Assert in file: "rate_fallback.c" in line: 1703
S 1 7 2 1805 Remove stale result from general queue, tries = %d
S 1 7 2 1815 Assert in file: "rate_fallback.c" in line: 1815
S 1 7 2 1838 Assert in file: "rate_fallback.c" in line: 1838
S 1 7 2 1852 Assert in file: "rate_fallback.c" in line: 1852
S 1 7 2 1855 Assert in file: "rate_fallback.c" in line: 1855
S 1 7 2 1860 Assert in file: "rate_fallback.c" in line: 1860
S 1 7 2 1947 Assert in file: "rate_fallback.c" in line: 1947
S 1 7 2 1976 Assert in file: "rate_fallback.c" in line: 1976
S 1 7 2 1990 Assert in file: "rate_fallback.c" in line: 1990
S 1 7 2 1993 Assert in file: "rate_fallback.c" in line: 1993
S 1 7 2 1998 Assert in file: "rate_fallback.c" in line: 1998
S 1 7 2 2028 Assert in file: "rate_fallback.c" in line: 2028
S 1 7 2 2029 Assert in file: "rate_fallback.c" in line: 2029
S 1 7 2 2122 Assert in file: "rate_fallback.c" in line: 2122
S 1 7 2 2294 PfSetTimer: %d, SID: %d
S 1 7 2 2448 Process 11b feedback. fsdu state = %u, u8Forced11bRate = %u u32UseRate = %u MSDU ptr = %u
S 1 7 2 2498 Assert in file: "rate_fallback.c" in line: 2498
S 1 7 2 2591 11b Feedback - 11b retries = %u, 11b eff rate = %u, 11n retries = %u, 11n eff rate = %u
S 1 7 2 2602 Enhanced 11b: Turn 11b flag off for STA: %Y
S 1 7 2 2610 PfSetTimer: %d, SID: %d
S 1 7 2 2682 Assert in file: "rate_fallback.c" in line: 2682
S 1 7 2 2834 Assert in file: "rate_fallback.c" in line: 2834
S 1 7 2 3060 Assert in file: "rate_fallback.c" in line: 3060
S 1 7 2 3163 Assert in file: "rate_fallback.c" in line: 3163
S 1 7 2 3171 vRFB_SetBestRate: Rate = %d, u8ConsecutiveFailures=	%d
S 1 7 2 3193 vRFB_SetBestRate,enhancedRate11BMaxTp = %d,  u16BestEffectiveRateBeforeLimit = %d
S 1 7 2 3335 Assert in file: "rate_fallback.c" in line: 3335
S 1 7 2 3344 Assert in file: "rate_fallback.c" in line: 3344
S 1 7 2 3365 Assert in file: "rate_fallback.c" in line: 3365
S 1 7 2 3368 Assert in file: "rate_fallback.c" in line: 3368
S 1 7 2 3373 Assert in file: "rate_fallback.c" in line: 3373
S 1 7 2 3491 Assert in file: "rate_fallback.c" in line: 3491
S 1 7 2 3703 RFB_Stability = %d
S 1 7 2 3712 Assert in file: "rate_fallback.c" in line: 3712
S 1 7 2 3794 Enhanced 11b: Turn 11b flag on for STA: %Y
S 1 7 9 668 Discard Legacy Uni - prio - %d, curr AGGR - %d, BE - %d, BK - %d, VI - %d, VO - %d
S 1 7 9 810 Assert in file: "tx_queue_task.c" in line: 810
S 1 7 9 822 Discard Legacy BCAST - prio - %d, curr AGGR - %d, BE - %d, BK - %d, VI - %d, VO - %d
S 1 7 9 952 vTXQU_Enable: sTXQUstate is %d
S 1 7 9 986 vTXQU_Disable: sTXQUstate is %d
S 1 7 9 1170 ActionPreTBTTres, Changequeues:%d
S 1 7 9 1435 Assert in file: "tx_queue_task.c" in line: 1435
S 1 7 9 1437 Assert in file: "tx_queue_task.c" in line: 1437
S 1 7 9 1450 Assert in file: "tx_queue_task.c" in line: 1450
S 1 7 9 1478 Enhanced 11b: packet will be sent as legacy. MSDU ptr = %u
S 1 7 9 1496 Enhanced 11b: Aggregation was disassembled to single packets. TsIndex = %d
S 1 7 9 1798 Assert in file: "tx_queue_task.c" in line: 1798
S 1 7 9 1823 Assert in file: "tx_queue_task.c" in line: 1823
S 1 7 9 1863 Assert in file: "tx_queue_task.c" in line: 1863
S 1 7 9 2187 Assert in file: "tx_queue_task.c" in line: 2187
S 1 7 9 2371 Assert in file: "tx_queue_task.c" in line: 2371
S 1 7 9 2465 Assert in file: "tx_queue_task.c" in line: 2465
S 1 7 8 419 SendMsduWithFsdu, number of elements in DeferActiveQueue [%d]:%d
S 1 7 8 420 SendMsduWithFsdu, CurrentMsduQueue: %X
S 1 7 8 490 Assert in file: "tx_state_task.c" in line: 490
S 1 7 8 501 Assert in file: "tx_state_task.c" in line: 501
S 1 7 8 514 SendMsduWithFsdu, NumberOfAllocatedFsdu[%d]:%d
S 1 7 8 527 Assert in file: "tx_state_task.c" in line: 527
S 1 7 8 679 Assert in file: "tx_state_task.c" in line: 679
S 1 7 8 734 Assert in file: "tx_state_task.c" in line: 734
S 1 7 8 738 Assert in file: "tx_state_task.c" in line: 738
S 1 7 8 789 Assert in file: "tx_state_task.c" in line: 789
S 1 7 8 815 Enhanced 11b: FsduCallback - forced rate. now check if flag is on
S 1 7 8 862 Assert in file: "tx_state_task.c" in line: 862
S 1 7 8 866 FsduCallBack, NumOfFsduAllocated[%d]: %d
S 1 7 8 913 Assert in file: "tx_state_task.c" in line: 913
S 1 7 8 950 Assert in file: "tx_state_task.c" in line: 950
S 1 7 8 1111 PutTxFsdu, SetFifoQ [%d], fifoEntries: %d
S 1 7 8 1146 Assert in file: "tx_state_task.c" in line: 1146
S 1 7 8 1256 PutTxFsdu, SetFifoQ [%d], fifoEntriesAfterPut %d
S 1 7 8 1474 Assert in file: "tx_state_task.c" in line: 1474
S 1 7 8 1578 Assert in file: "tx_state_task.c" in line: 1578
S 1 7 8 1659 Assert in file: "tx_state_task.c" in line: 1659
S 1 7 8 1689 Assert in file: "tx_state_task.c" in line: 1689
S 1 7 8 1755 Assert in file: "tx_state_task.c" in line: 1755
S 1 7 8 1759 Assert in file: "tx_state_task.c" in line: 1759
S 1 7 8 1801 Assert in file: "tx_state_task.c" in line: 1801
S 1 7 8 1814 Assert in file: "tx_state_task.c" in line: 1814
S 1 7 8 2016 Assert in file: "tx_state_task.c" in line: 2016
S 1 31 1 50 Assert in file: "MT_bb_utils.c" in line: 50
S 1 31 2 56 Assert in file: "MT_Math.c" in line: 56
S 1 1 1 255 Assert in file: "mt_11h.c" in line: 255
S 1 1 1 333 Assert in file: "mt_11h.c" in line: 333
S 1 1 1 418 Assert in file: "mt_11h.c" in line: 418
S 1 1 1 423 Assert in file: "mt_11h.c" in line: 423
S 1 1 1 424 Assert in file: "mt_11h.c" in line: 424
S 1 1 1 428 Assert in file: "mt_11h.c" in line: 428
S 1 1 1 429 Assert in file: "mt_11h.c" in line: 429
S 1 1 1 444 Assert in file: "mt_11h.c" in line: 444
S 1 1 1 497 Assert in file: "mt_11h.c" in line: 497
S 1 1 1 546 Assert in file: "mt_11h.c" in line: 546
S 1 1 1 672 Mt11h_SetStatus, %d -> %d
S 1 1 1 714 Mt11h_ChannelSwitchClearDown:Mt11h_TxPause=%x psMsg=%x Mt11h_IsClearDown=%x
S 1 1 1 731 Assert in file: "mt_11h.c" in line: 731
S 1 1 1 785 Mt11h_ChannelSwitchSm, Mt11h_Status:%d
S 1 1 1 963 Mt11h_ChannelSwitchSm, send UMI_MC_DFS_END_IND
S 1 1 1 1122 Assert in file: "mt_11h.c" in line: 1122
S 1 1 1 1247 Mt11h_TxDoPauseRequest: val=%x returnTask=%d
S 1 1 1 1257 Assert in file: "mt_11h.c" in line: 1257
S 1 1 1 1709 Assert in file: "mt_11h.c" in line: 1709
S 1 1 1 2218 Assert in file: "mt_11h.c" in line: 2218
S 1 1 1 2289 Assert in file: "mt_11h.c" in line: 2289
S 1 4 3 206 Assert in file: "auth_task.c" in line: 206
S 1 4 3 304 Assert in file: "auth_task.c" in line: 304
S 1 4 3 305 Assert in file: "auth_task.c" in line: 305
S 1 4 3 314 vAUTH_TxAuthentication, u16AuthSeq:%d, u16AuthType:%d, u16AuthStatus:%d
S 1 4 3 401 Assert in file: "auth_task.c" in line: 401
S 1 4 3 477 Assert in file: "auth_task.c" in line: 477
S 1 4 3 484 Assert in file: "auth_task.c" in line: 484
S 1 4 3 502 Rx authentication request from sta: %Y
S 1 4 3 507 Adding STA to DB
S 1 4 3 516 Assert in file: "auth_task.c" in line: 516
S 1 4 3 532 ERROR! max allow connection overflow 
S 1 4 3 546 STA already exists in DB, keep Authenticate msg, report disconnection and trigger authentication again
S 1 6 2 186 Assert in file: "BSSmanager_BssSM.c" in line: 186
S 1 6 2 268 Assert in file: "BSSmanager_BssSM.c" in line: 268
S 1 6 2 292 Assert in file: "BSSmanager_BssSM.c" in line: 292
S 1 6 2 314 Assert in file: "BSSmanager_BssSM.c" in line: 314
S 1 6 2 318 Assert in file: "BSSmanager_BssSM.c" in line: 318
S 1 6 2 550 Assert in file: "BSSmanager_BssSM.c" in line: 550
S 1 6 2 577 Assert in file: "BSSmanager_BssSM.c" in line: 577
S 1 6 2 602 Assert in file: "BSSmanager_BssSM.c" in line: 602
S 1 6 2 615 Assert in file: "BSSmanager_BssSM.c" in line: 615
S 1 6 2 647 BSSmanager_BuildSharedInformationElements: update Template
S 1 15 6 570 TPC: Finished Calibration. Run Time = %d
S 1 15 6 651 Fatal Error in file: "TpcClbrHndlr.c"; Fatal Print: No TPC data
S 1 15 6 735 TPC_UpdateStrInScan Max Power Ant0 = %d Ant1 = %d Ant2 = %d
S 1 15 6 931 TPC_SetTxPowerIndex: 3 ANT TPC index = %d
S 1 15 6 972 Assert in file: "TpcClbrHndlr.c" in line: 972
S 1 15 6 1088 TPC_CalibrateSingleAntenna:Executing Calibration For Antenna %d PA_low_power_flag 0x%X
S 1 15 6 1117 No Power Fix is needed, expected Power is %d, Power_upper_Limit:%d, powerLowerLimit:%d
S 1 15 6 1133 The expected Power after TPC & digital change is %d, Power_upper_Limit:%d
S 1 15 6 1209 TPC Power Window For Tx PowerIndex %d is between %d and %d
S 1 15 6 1257 The feedback is  %d and the power is %d
S 1 15 6 1302 TPC_FixPowerGains CurrentTPC Index is %d Current Digital Index is %d gain Fix required %d
S 1 15 6 1314 Only digital Fix is done New Digital Index is %d gain Fix required %d
S 1 15 6 1331 New TPC Index:%d gain Fix still required is %d
S 1 15 6 1341 newDigitalIndex:%d gain Fix still required is %d
S 1 15 6 1355 Gains after gains adjustment newDigitalIndex:%d newTpcIndex %d
S 1 15 6 1625 TPC fixPowerGains: Gain Fix required %d Current Digital Index %d
S 1 15 6 1631 TPC fixPowerGains Current Analog TPC Index %d Current Mixer Index %d Current External PA Index %d
S 1 15 6 1643 Only digital Fix done: New Digital Index is %d gain Fix required %d
S 1 15 6 1666 TPC fixPowerGains SWITCH: Analog TPC Index %d Mixer Index %d External PA %d
S 1 15 6 1676 TPC fixPowerGains ATPC Adjust: Analog TPC Index:%d gain Fix still required is %d
S 1 15 6 1687 TPC fixPowerGains DTPC Adjust: Digital TPC Index:%d gain Fix still required is %d
S 1 15 6 1697 TPC fixPowerGains DTPC Adjust-NONE: Digital TPC Index:%d gain Fix still required is %d
S 1 15 6 1705 TPC fixPowerGains after gains adjustment: gain Fix still required %d
S 1 15 6 2007 calcAnalogTpcGainDuringInit tpcSwitched: Analog TPC Index %d Mixer Index %d External PA %d
S 1 15 6 2428 TPC_InitOpenLoopTpc:Open loop TPC:Ant0_TpcIndex = %d,Ant1 TpcIndex = %d Ant2 TpcIndex = %d
S 1 15 6 2481 TPC_Initialize:Close loop TPC CB power limit = %d nCB power limit = %d (3 bit fixed point)
S 1 15 6 2712 Assert in file: "TpcClbrHndlr.c" in line: 2712
S 1 15 6 2721 TPC_SetPowerLimitTable:Max Power of Ant %d is %d (3 bit fixed point)
S 1 15 6 2763 Assert in file: "TpcClbrHndlr.c" in line: 2763
S 1 15 6 2771 setPowerLimitTable, txPowerIndex:%d, TPC_MaxPowerOffset[txPowerIndex]:%d, maxTxPoweLimit:%d, TPC_RegLimitOffset[txPowerIndex]:%d, regPowerLimit:%d, maxPowerLimit1:%d, maxPowerLimit2:%d
S 1 15 6 2878 Assert in file: "TpcClbrHndlr.c" in line: 2878
S 1 15 6 2903 TPC_UpdateTxGainsTables: Tpc_max_power:%d, tpc_max_power_idx:%d, current_power:%d, desired_power:%d, TpcIndexEnd:%d
S 1 15 6 2939 Starting TPC for Tx Power index %d is = %d
S 1 15 6 2966 TPC Debug Mode  Max Power TPC Index is = %d
S 1 15 6 3030 Assert in file: "TpcClbrHndlr.c" in line: 3030
S 1 15 6 3051 Assert in file: "TpcClbrHndlr.c" in line: 3051
S 1 15 6 3154 Assert in file: "TpcClbrHndlr.c" in line: 3154
S 1 19 1 1236 Assert in file: "lminfra.c" in line: 1236
S 1 19 1 1240 Assert in file: "lminfra.c" in line: 1240
S 1 19 1 1245 Assert in file: "lminfra.c" in line: 1245
S 1 19 1 1358 Assert in file: "lminfra.c" in line: 1358
S 1 19 1 1896 Assert in file: "lminfra.c" in line: 1896
S 1 19 1 2053 Assert in file: "lminfra.c" in line: 2053
S 1 19 1 2075 Assert in file: "lminfra.c" in line: 2075
S 1 19 1 2086 Assert in file: "lminfra.c" in line: 2086
S 1 19 1 2091 Assert in file: "lminfra.c" in line: 2091
S 1 19 1 2094 Assert in file: "lminfra.c" in line: 2094
S 1 19 1 2161 CurFSDU, Qindx: %d, Fifo Size: %d
S 1 19 1 2183 Assert in file: "lminfra.c" in line: 2183
S 1 19 1 2256 NxtFSDU, Qindx: %d, Fifo Size: %d
S 1 19 1 2271 Assert in file: "lminfra.c" in line: 2271
S 1 19 1 2367 NxtNxtFSDU, Qindx: %d, Fifo Size: %d
S 1 19 1 2380 Assert in file: "lminfra.c" in line: 2380
S 1 19 1 2729 Assert in file: "lminfra.c" in line: 2729
S 1 19 1 2763 Assert in file: "lminfra.c" in line: 2763
S 1 19 1 2933 Assert in file: "lminfra.c" in line: 2933
S 1 19 1 3147 Assert in file: "lminfra.c" in line: 3147
S 1 19 1 3421 Assert in file: "lminfra.c" in line: 3421
S 1 19 1 3451 Assert in file: "lminfra.c" in line: 3451
S 1 19 1 3488 Assert in file: "lminfra.c" in line: 3488
S 1 19 1 3651 Assert in file: "lminfra.c" in line: 3651
S 1 19 1 3708 Fatal Error in file: "lminfra.c"; Fatal Print: Hardware setup failure
S 1 19 1 3890 Fatal Error in file: "lminfra.c"; Fatal Print: Unhandled case in switch
S 1 19 1 3930 Assert in file: "lminfra.c" in line: 3930
S 1 19 1 3943 Assert in file: "lminfra.c" in line: 3943
S 1 19 1 4047 Assert in file: "lminfra.c" in line: 4047
S 1 19 1 4050 HandleQswitch,eSwitchEvent: %d, u8direction: %d 
S 1 19 1 4063 Assert in file: "lminfra.c" in line: 4063
S 1 19 1 4068 Assert in file: "lminfra.c" in line: 4068
S 1 19 1 4253 Assert in file: "lminfra.c" in line: 4253
S 1 19 1 4298 Qswitch NSE_BCN_CP,nextMcPsQueue:%d,CurrentMcPsQueue: %d
S 1 19 1 4300 Assert in file: "lminfra.c" in line: 4300
S 1 19 1 4335 Qswitch NSE_DTIM_END, CurrentMcPsQueue: %d
S 1 19 1 4490 Assert in file: "lminfra.c" in line: 4490
S 1 19 1 5750 Fatal Error in file: "lminfra.c"; Fatal Print: Hardware setup failure
S 1 19 1 5769 Fatal Error in file: "lminfra.c"; Fatal Print: Hardware setup failure
S 1 19 1 6371 Assert in file: "lminfra.c" in line: 6371
S 1 19 1 6406 Assert in file: "lminfra.c" in line: 6406
S 1 19 1 6725 Assert in file: "lminfra.c" in line: 6725
S 1 19 1 7054 Fatal Error in file: "lminfra.c"; Fatal Print: Unhandled case in switch
S 1 19 1 7276 GetFromMpsQueue,index: %d,  Multicast_PS entries before flush:%d
S 1 19 1 7277 GetFromMpsQueue, FlushBitMap:%d, MoreDataBit: %d
S 1 19 1 7282 Assert in file: "lminfra.c" in line: 7282
S 1 19 1 7306 GetFromMpsQueue, Multicast_PS current queue entries after flash:%d
S 1 19 1 7342 FlushPostopned[%d]
S 1 19 1 7382 MpsSwitchOff, immediate, vapIndex: %d
S 1 19 1 7392 MpsSwitchOff, posponed, vapIndex: %d
S 1 19 1 7439 FlushMps[%d]
S 1 19 1 7804 Assert in file: "lminfra.c" in line: 7804
S 1 19 1 7829 Assert in file: "lminfra.c" in line: 7829
S 1 19 1 8158 Assert in file: "lminfra.c" in line: 8158
S 1 19 5 267 Assert in file: "lminfrafg.c" in line: 267
S 1 19 5 292 Assert in file: "lminfrafg.c" in line: 292
S 1 19 5 320 LM_MAN_PRE_TBTT_IND_SW_TMR_IND 1, ts: %010u
S 1 19 5 529 Assert in file: "lminfrafg.c" in line: 529
S 1 19 5 603 Assert in file: "lminfrafg.c" in line: 603
S 1 19 3 425 Assert in file: "lmmain.c" in line: 425
S 1 19 3 591 Assert in file: "lmmain.c" in line: 591
S 1 19 3 724 Assert in file: "lmmain.c" in line: 724
S 1 19 3 764 Assert in file: "lmmain.c" in line: 764
S 1 19 3 967 Fatal Error in file: "lmmain.c"; Fatal Print: Unknown PHY type
S 1 19 3 1536 ------ ResetDetectionParams --------
S 1 19 3 1569 SetDetectionTimeouts: current pollingTO %d, indTO %d TSF %u
S 1 19 3 1593 DetectionPollingTimeout: mode %d, counter %d, TSF %u
S 1 19 3 1598 #### Read value %d
S 1 19 3 1600 0:%d,1:%d,2:%d,3:%d
S 1 19 3 1666 Assert in file: "lmmain.c" in line: 1666
S 1 19 3 1744 Assert in file: "lmmain.c" in line: 1744
S 1 19 3 1836 Assert in file: "lmmain.c" in line: 1836
S 1 21 1 317 Assert in file: "lm_interface_task.c" in line: 317
S 1 21 1 340 Assert in file: "lm_interface_task.c" in line: 340
S 1 21 1 341 Assert in file: "lm_interface_task.c" in line: 341
S 1 21 1 342 Assert in file: "lm_interface_task.c" in line: 342
S 1 21 1 343 Assert in file: "lm_interface_task.c" in line: 343
S 1 21 1 349 Assert in file: "lm_interface_task.c" in line: 349
S 1 21 1 351 Assert in file: "lm_interface_task.c" in line: 351
S 1 21 1 352 Assert in file: "lm_interface_task.c" in line: 352
S 1 21 1 353 Assert in file: "lm_interface_task.c" in line: 353
S 1 21 1 355 Assert in file: "lm_interface_task.c" in line: 355
S 1 21 1 358 Assert in file: "lm_interface_task.c" in line: 358
S 1 21 1 393 Assert in file: "lm_interface_task.c" in line: 393
S 1 21 1 403 Assert in file: "lm_interface_task.c" in line: 403
S 1 21 1 486 Assert in file: "lm_interface_task.c" in line: 486
S 1 21 1 774 Assert in file: "lm_interface_task.c" in line: 774
S 1 21 1 831 Assert in file: "lm_interface_task.c" in line: 831
S 1 21 1 880 Assert in file: "lm_interface_task.c" in line: 880
S 1 21 1 944 Unhandled msgType 1 0x%04x !!
S 1 21 1 945 Assert in file: "lm_interface_task.c" in line: 945
S 1 21 1 978 Assert in file: "lm_interface_task.c" in line: 978
S 1 21 1 990 Assert in file: "lm_interface_task.c" in line: 990
S 1 21 1 1010 LM sleep time in micro %010u out of %010u printed at %010u
S 1 21 1 1023 vLMI_ISR_M_CFM_IND: LM_INTERFERER_IND: time %u
S 1 21 1 1030 Unhandled msgType 2 0x%04x !!
S 1 21 1 1208 Fatal Error in file: "lm_interface_task.c"; Fatal Print: Lower MAC Assertion
S 1 21 1 1383 Assert in file: "lm_interface_task.c" in line: 1383
S 1 21 1 1403 Assert in file: "lm_interface_task.c" in line: 1403
S 1 21 1 1538 Assert in file: "lm_interface_task.c" in line: 1538
S 1 21 1 1578 Assert in file: "lm_interface_task.c" in line: 1578
S 1 7 3 410 Assert in file: "txpacket.c" in line: 410
S 1 7 3 411 Assert in file: "txpacket.c" in line: 411
S 1 7 3 516 Assert in file: "txpacket.c" in line: 516
S 1 7 3 517 Assert in file: "txpacket.c" in line: 517
S 1 7 3 528 Assert in file: "txpacket.c" in line: 528
S 1 7 3 550 bTXP_SendManagePkt failed, Unknown VAP - pkt type %d
S 1 7 3 628 Assert in file: "txpacket.c" in line: 628
S 1 7 3 658 bTXP_SendManagePkt failed, no MSDU - pkt type %d
S 1 7 3 703 Assert in file: "txpacket.c" in line: 703
S 1 7 3 704 Assert in file: "txpacket.c" in line: 704
S 1 7 3 840 Assert in file: "txpacket.c" in line: 840
S 1 7 3 981 Assert in file: "txpacket.c" in line: 981
S 1 7 3 998 Assert in file: "txpacket.c" in line: 998
S 1 7 3 1062 Assert in file: "txpacket.c" in line: 1062
S 1 7 3 1157 Assert in file: "txpacket.c" in line: 1157
S 1 7 3 1198 LBF_ENABLED STBC_Transmission CDDindex =%d
S 1 7 3 1203 LBF_ENABLED !NOT! STBC_Transmission CDDindex =%d
S 1 7 3 1208 LBF_DISABLED  !NOT! STBC_Transmission CDDindex =%d
S 1 7 3 1266 InitLegacyRateTable: rate mask %x, MIB basic rate set %x
S 1 7 3 1283 InitLegacyRateTable: rate %d, basic rate %d
S 1 7 3 1486 vTXP_SetFrameHeader: EOSPD = 1,currentTxFrames: %x 
S 1 7 3 1689 Assert in file: "txpacket.c" in line: 1689
S 1 7 3 1692 Assert in file: "txpacket.c" in line: 1692
S 1 7 3 1744 Assert in file: "txpacket.c" in line: 1744
S 1 7 3 1750 Assert in file: "txpacket.c" in line: 1750
S 1 7 3 1899 Assert in file: "txpacket.c" in line: 1899
S 1 7 3 1911 Assert in file: "txpacket.c" in line: 1911
S 1 7 3 1918 Fatal Error in file: "txpacket.c"; Fatal Print: Unknown frame type
S 1 7 3 1978 Assert in file: "txpacket.c" in line: 1978
S 1 7 3 2012 Assert in file: "txpacket.c" in line: 2012
S 1 7 3 2123 Assert in file: "txpacket.c" in line: 2123
S 1 7 3 2181 Assert in file: "txpacket.c" in line: 2181
S 1 7 3 2214 Assert in file: "txpacket.c" in line: 2214
S 1 7 3 2273 u32TXP_SetRate: rate is short=%d, update to long, u16SID = %d
S 1 7 3 2279 u32TXP_SetRate: rate is long=%d, update to short, u16SID = %d
S 1 7 3 2323 Assert in file: "txpacket.c" in line: 2323
S 1 7 3 2348 Assert in file: "txpacket.c" in line: 2348
S 1 7 3 2395 Assert in file: "txpacket.c" in line: 2395
S 1 7 3 2636 enhanced 11b: ChangeRateTo11b - psMsduFsdu->sPartialData.u8TxRate = %d
S 1 7 3 2658 Assert in file: "txpacket.c" in line: 2658
S 1 7 3 2769 enhanced 11b: u16TxRate = %d, u16TxFallbackRate1 = %d, u16TxFallbackRate2 = %d
S 1 30 1 812 Assert in file: "um_interface_task.c" in line: 812
S 1 30 1 981 Assert in file: "um_interface_task.c" in line: 981
S 1 30 1 1509 UMI_ENABLE_DETECTION_REQ: time %u
S 1 30 1 1633 Assert in file: "um_interface_task.c" in line: 1633
S 1 30 1 1789 vUM_DISCONNECT_CFM 
S 1 30 1 1839 Fatal Error in file: "um_interface_task.c"; Fatal Print: Debug Assert Requested by Host
S 1 30 1 1845 Assert in file: "um_interface_task.c" in line: 1845
S 1 30 1 1893 Assert in file: "um_interface_task.c" in line: 1893
S 1 30 1 1900 Assert in file: "um_interface_task.c" in line: 1900
S 1 30 1 1901 Assert in file: "um_interface_task.c" in line: 1901
S 1 30 1 1903 Assert in file: "um_interface_task.c" in line: 1903
S 1 30 1 1934 vUM_MAN_GET_GROUP_PN_REQ /CFM, vapId:%d, u16Status:%d, au8TxSeqNum:%d %d %d %d %d %d
S 1 30 1 2143 Assert in file: "um_interface_task.c" in line: 2143
S 1 30 1 2205 Assert in file: "um_interface_task.c" in line: 2205
S 1 30 1 2224 Assert in file: "um_interface_task.c" in line: 2224
S 1 30 1 2256 Assert in file: "um_interface_task.c" in line: 2256
S 1 30 1 2342 Assert in file: "um_interface_task.c" in line: 2342
S 1 30 1 2353 Assert in file: "um_interface_task.c" in line: 2353
S 1 30 1 2689 Assert in file: "um_interface_task.c" in line: 2689
S 1 30 1 3111 vUM_MAN_ADD_PEERAP_REQ: VapDBptr->numOfPeerWepAP = %d, VapDBptr->numOfPeerAP++ = %d, vapID = %d
S 1 30 1 3372 UMAC Rx UM_DBG_CLI_REQ from Host, action:%d, argc:%d, data1:%d, data2:%d, data3:%d
S 1 30 1 3392 mask = %x addr = 0X%x%x%x%x%x%x
S 1 30 1 3410 Assert in file: "um_interface_task.c" in line: 3410
S 1 30 1 3631 Assert in file: "um_interface_task.c" in line: 3631
S 1 30 1 3676 u8Consecutive11bProbingSuccessThreshold = %d, u8Consecutive11bSuccessThreshold = %d
S 1 30 1 3680 Enhanced 11b feature is not supported.
S 1 30 1 3714 Enhanced 11b feature is not supported.
S 1 4 1 703 Assert in file: "bss_manage_task.c" in line: 703
S 1 4 1 724 Assert in file: "bss_manage_task.c" in line: 724
S 1 4 1 749 Assert in file: "bss_manage_task.c" in line: 749
S 1 4 1 801 Assert in file: "bss_manage_task.c" in line: 801
S 1 4 1 870 Assert in file: "bss_manage_task.c" in line: 870
S 1 4 1 936 Bss_PreActivateReq FWinterface=%d
S 1 4 1 1087 Assert in file: "bss_manage_task.c" in line: 1087
S 1 4 1 1209 vBSS_ScanReq: entered scan request. state is %d
S 1 4 1 1213 vBSS_ScanReq: got scan request while bss sm is not ready (u8BSSmanState is %d)
S 1 4 1 1276 vBSS_ScanReq: start BG scan
S 1 4 1 1285 vBSS_ScanReq: start regular scan
S 1 4 1 1295 Assert in file: "bss_manage_task.c" in line: 1295
S 1 4 1 1325 Assert in file: "bss_manage_task.c" in line: 1325
S 1 4 1 1961 Assert in file: "bss_manage_task.c" in line: 1961
S 1 4 1 1971 Assert in file: "bss_manage_task.c" in line: 1971
S 1 4 1 2053 vBSS_LmStopModuleNewReq: uLmStopReason: %d
S 1 4 1 2088 vBSS_LmStopModule: psMsg->tKMsgType 0x%x, uLmStopReason %d, u8BSSLMState %d
S 1 4 1 2095 Assert in file: "bss_manage_task.c" in line: 2095
S 1 4 1 2188 Assert in file: "bss_manage_task.c" in line: 2188
S 1 4 1 2203 vBSS_LmStopConfirm: uLmStopReason: %d
S 1 4 1 2219 Assert in file: "bss_manage_task.c" in line: 2219
S 1 4 1 2454 vBSS_JoinBSS: u16RFchannel %d
S 1 4 1 2485 vBSS_JoinBSSreq, BeaconPeriod:%d, BasicRateSet:%d, OperationalRateSet:%d
S 1 4 1 2647 vBSS_StartBSS, Ch:%d, SmRequired:%d
S 1 4 1 2763 Assert in file: "bss_manage_task.c" in line: 2763
S 1 4 1 2771 u16BSS_GetFirstChannel: channel = %d, mode = %x
S 1 4 1 2809 Assert in file: "bss_manage_task.c" in line: 2809
S 1 4 1 2828 u16BSS_GetNextChannel: channel = %d, mode = %x
S 1 4 1 2874 vBSS_StartScan: u8BSSmanState: %d u8BSSLMState: %d
S 1 4 1 2881 vBSS_StartScan: start LM scan on channel %d
S 1 4 1 3414 vBSS_StartScanLM: RfChannel %d
S 1 4 1 3513 vBSS_RxFilterCfm: u16RxFilter: %d, psScan: 0x%x
S 1 4 1 3518 Assert in file: "bss_manage_task.c" in line: 3518
S 1 4 1 3552 Assert in file: "bss_manage_task.c" in line: 3552
S 1 4 1 3595 Assert in file: "bss_manage_task.c" in line: 3595
S 1 4 1 3603 vBSS_ScanTimeout: u8BSSLMState: %d, bIsMinTime: %d, probe reqs: %d
S 1 4 1 3605 vBSS_ScanTimeout: u8BSSLMState: %d, bIsMinTime: %d
S 1 4 1 3630 vBSS_ScanTimeout: set timer to %u
S 1 4 1 3657 vBSS_ScanTimeout: next channel = %d (0xFFFF is INVALID_CHANNEL)
S 1 4 1 3756 vBSS_ScanCurrentChannel: LM_SCAN_ACTIVE channel number: %d, u16CurMinActiveScanTime: %d, u16CurMaxActiveScanTime: %d
S 1 4 1 3771 vBSS_ScanCurrentChannel: set probe timer %d
S 1 4 1 3789 vBSS_ScanCurrentChannel: LM_SCAN_PASSIVE channel number: %d, u16CurMinPassiveScanTime: %d, u16CurMaxPassiveScanTime: %d
S 1 4 1 3823 vBSS_StopOnlineCalibCfm: isSelfStopCalReq %d
S 1 4 1 3864 vBSS_SetChannelCfm: FIRST_CHANNEL: u8BSSLMState: %d
S 1 4 1 3902 vBSS_SetChannelCfm: NON_FIRST_CHANNEL: sMIB_Objects.u16CurrentChannelNumber %d, sCurChanParams.u16Channel %d
S 1 4 1 3926 vBSS_SetRxFilter: filter type: %d, returnTask: %d
S 1 4 1 3956 vBSS_TxPauseCfmHandler
S 1 4 1 3982 Assert in file: "bss_manage_task.c" in line: 3982
S 1 4 1 4103 vBSS_PrepareSetChannelReqOnJoin: psState %d, u8BSSLMState %d
S 1 4 1 4129 Assert in file: "bss_manage_task.c" in line: 4129
S 1 4 1 4290 Fatal Error in file: "bss_manage_task.c"; Fatal Print: PCI Timeout
S 1 4 1 4355 Assert in file: "bss_manage_task.c" in line: 4355
S 1 4 1 4362 Assert in file: "bss_manage_task.c" in line: 4362
S 1 15 14 118 CM: issueHostDataTransaction() uHostBaseAddress 0x%x start 0x%x end 0x%x
S 1 15 14 120 Assert in file: "CalibrationManager.c" in line: 120
S 1 15 14 167 CalibrationManager: Finished offline calibrations. state=%d
S 1 15 14 186 CalibrationManager: Calibration data to be stored
S 1 15 14 204 CM: Issue calibration Req: type=%d, proc=%d, seamless=%d
S 1 15 14 208 Assert in file: "CalibrationManager.c" in line: 208
S 1 15 14 294 #######Reset Req: Init Mask=%x Offline Mask=%x, Online Mask=%x
S 1 15 14 296 Assert in file: "CalibrationManager.c" in line: 296
S 1 15 14 329 Assert in file: "CalibrationManager.c" in line: 329
S 1 15 14 343 Assert in file: "CalibrationManager.c" in line: 343
S 1 15 14 346 Assert in file: "CalibrationManager.c" in line: 346
S 1 15 14 363 Assert in file: "CalibrationManager.c" in line: 363
S 1 15 14 408 Assert in file: "CalibrationManager.c" in line: 408
S 1 15 14 413 $$$RunOfflineCalibration: Cur state:%d, Procs bitmask=%d
S 1 15 14 472 ClbrMngr_CalibActiveCfmCb: m_state: %d
S 1 15 14 484 Calibrations returned with failure: Algo Type: %d, Error Code: %d
S 1 15 14 505 QBF offline Cal Succeeded
S 1 15 14 512 QBF offline Cal Fail
S 1 15 14 545 Assert in file: "CalibrationManager.c" in line: 545
S 1 15 14 558 QBF online Cal Succeeded
S 1 15 14 591 Finished online calibrations. next proc bit val=0x%x, Online Calib proc=0x%x, state=%d
S 1 15 14 610 QBF offline Cal Succeeded
S 1 15 14 617 QBF offline Cal Fail
S 1 15 14 743 ClbrMngr_HostDataChunkDmaCompleteCb: state: %d
S 1 15 14 791 Assert in file: "CalibrationManager.c" in line: 791
S 1 15 10 135 Assert in file: "CalibrationManagerDB.c" in line: 135
S 1 15 10 185 Assert in file: "CalibrationManagerDB.c" in line: 185
T 1 4 7 223 FM_PAYLOAD_AUTHENTICATION
T 1 4 4 2276 FM_PAYLOAD_ADDBA_REQ
T 1 4 4 2286 FM_PAYLOAD_ADDBA_RES
T 1 4 4 2296 FM_PAYLOAD_DELBA
T 1 4 4 2734 UMI_DISCONNECT
T 1 5 7 928 FM_PAYLOAD_SAQUERY
T 1 5 7 1172 FM_PAYLOAD_SAQUERY
T 1 6 1 225 UMI_ACTIVATE_VAP
T 1 6 3 938 PhyLoggerBeaconSeq_t
T 1 8 2 394 UMI_MIB
T 1 15 31 2306 QbfAgcOffsetCalParams_t
T 1 15 31 2521 int8_cmplx_t
T 1 15 31 2549 QbfAgcOffsetCalParams_t
T 1 15 31 2550 QbfTxOffsetCalParams_t
T 1 15 21 249 QbfSessionParams_t
T 1 18 5 1597 PhyLoggerBuffer_t
T 1 27 14 91 UMI_SET_KEY
T 1 7 6 789 UMI_OPEN_AGGR_REQ
T 1 7 6 883 UMI_OPEN_AGGR_REQ
T 1 7 6 908 UMI_CLOSE_AGGR_REQ
T 1 7 6 1151 FM_PAYLOAD_ADDBA_REQ
T 1 7 6 1170 UMI_ADDBA_REQ_SEND
T 1 7 6 1226 FM_PAYLOAD_ADDBA_RES
T 1 1 1 399 FREQUENCY_ELEMENT
T 1 21 1 1024 UMI_INTERFERER
T 1 30 1 1720 UMI_CONNECTION_EVENT
T 1 30 1 3080 UMI_PEERAP_REQ
T 1 30 1 3141 UMI_PEERAP_REQ
T 1 4 1 932 UMI_MBSS_PRE_ACTIVATE
T 1 4 1 1224 UMI_SCAN_HDR
T 1 4 1 2947 UMI_NETWORK_EVENT
