#!/bin/sh
if [ -f /sysconfig/ipv6-cfg ]; then
    cp /sysconfig/ipv6-cfg /tmp/ipv6-cfg.old
    . /sysconfig/ipv6-cfg
    if [ "${IPV6_ENABLE}" = "off" ]; then
        sysctl -w net.ipv6.conf.all.disable_ipv6=1
        echo "IPv6 ENABLE is off"
    else
        echo "IPv6 ENABLE on LanInit"
        sysctl -w net.ipv6.conf.all.disable_ipv6=0
        sysctl -w net.ipv6.conf.all.forwarding=1
    fi
else
    echo "No /sysconfig/ipv6-cfg"
fi

LANIP=`sqlite3 -cmd ".timeout 1000" /tmp/system.db "select ipaddr from networkInterface where LogicalIfName = 'LAN1';"`
SUBNET=`sqlite3 -cmd ".timeout 1000" /tmp/system.db "select subnetmask from networkInterface where LogicalIfName = 'LAN1';"`
DOMAIN=`sqlite3 -cmd ".timeout 1000" /tmp/system.db "select domain from system;"`
NAME=`sqlite3 -cmd ".timeout 1000" /tmp/system.db "select name from system;"`
INTERFACE=`sqlite3 -cmd ".timeout 1000" /tmp/system.db "select interfaceName from networkInterface where LogicalIfName = 'LAN1';"`
NATENABLE=`sqlite3 -cmd ".timeout 1000" /tmp/system.db "select Enable from FirewallNatConfig;"`
WANINTERFACE=`sqlite3 -cmd ".timeout 1000" /tmp/system.db "select interfaceName from networkInterface where LogicalIfName = 'LTE-WAN1';"`
#sleep 2
ifconfig $INTERFACE $LANIP netmask $SUBNET
if [ "$NAME" != "" ]; then
	hostname $NAME
	if [ "$DOMAIN" = "" ]; then
		echo "$LANIP	$NAME.com $NAME " > /etc/hosts
	else
		echo "$LANIP	$NAME.$DOMAIN $NAME " > /etc/hosts
	fi
fi

if [ "$NATENABLE" = "5" ]; then #bridge mode
	brctl addif br0 $WANINTERFACE
	fwnat.sh
else
	/usr/local/bin/fwnat.sh
fi

#/usr/local/bin/routing.sh

if [ "$1" = "restart" ]; then 
	/usr/local/bin/dhcpdInit restart
else	
	/usr/local/bin/dhcpdInit
	# start dnsmasq
	/usr/sbin/dnsmasq -u root --resolv-file=/ramdisk/etc/resolv.conf
fi

# when lanInit, upnp configuration also need to be reconfigured
/usr/local/bin/upnp_service.sh

/usr/local/bin/ipv6_lan.sh

