/* adpRandLib.c - adaptos PRNG hook library */

/* Copyright (c) 2005, TeamF1, Inc. */

/*
modification history
--------------------
01c,28aug05,rnp  added new adpRand API - adpRandSeed(), adpRandLibExit(),
                 adpRandGen()
01b,17jun03,gnm  code cleanups: changed module description language,
                 formatting changes.
01a,24apr03,ksn  created.
*/

/*
DESCRIPTION

This library implements functionality to enable a user to add his own 
pseudo-random number generation utility. A user can install a random number 
generation utility by calling the routine `adpRandLibInit' and passing the 
address of the function of his random generation utility.

The random generation utility provided by the user should have two arguments;
first for pointer to unsigned char buffer, and second for size of the buffer.
First argument is for storing rand numbers generated by random generation
utility, and second arguemnt tells the size of buffer provided by the caller
routines.

INCLUDES: adaptos.h

*/

/* includes */

#include "adaptos.h"

/* defines */

/* local */
LOCAL ADP_RAND_FUNC_TBL   randFuncTbl;
LOCAL ADP_RAND_FUNC_TBL * pRandFuncTbl = &randFuncTbl;

/*******************************************************************************
* 
* adpRand - call custom PRNG routine
*
* This routine calls a user specific random number generation routine, that
* copies <randSize> number of random bytes into <pRandBuf>. This API is now
* deprecated, Used adpRandGen() instead,
*
* RETURNS: ST_OK, otherwise returns ST_ERROR.
*/
STATUS adpRand
    (
    char *    pRandBuf,  /* buffer to store random data */
    int       randSize   /* size of buffer */
    )
    {
    return (adpRandGen(pRandBuf, randSize));
    }

/*******************************************************************************
*
* adpRandLibInit - intialize adaptos random library
*
* This routine initializes the random library for adaptos layer. A user can
* pass his random seed generation routine as an argument.
*
* <pInitFunc>   - pointer to PRNG provider init func
*
* <arg1>    - argument required by PRNG provider init func
*
* RETURNS: ST_OK on success and ST_ERROR otherwise.
*/
STATUS adpRandLibInit
    (
    ADP_RAND_PROV_INIT_FUNC pInitFunc,  /* crypto provider init func */
    int                     arg1        /* argument to init func */
    )
    {
    ADP_RAND_FUNC_TBL * pFuncTbl = NULL;
    
    /* initialize the function table */
    memset (pRandFuncTbl, 0, sizeof(*pRandFuncTbl));
    
    if ((pFuncTbl = (*pInitFunc)(arg1)) == NULL)
        {
        adpErrnoSet(S_adpRandLib_INIT_FAILED);
        return (ST_ERROR);
        }

    *pRandFuncTbl = *pFuncTbl;

    return (ST_OK);
    }
 
/*******************************************************************************
* 
* adpRandLibExit - de-intialize adaptos PRNG library
*
* This routine de-initializes the random library for adaptos layer. A user can
* pass his random seed generation routine as an argument.
*
* RETURNS: ST_OK
*/
STATUS adpRandLibExit (void)
    {
    if (pRandFuncTbl != NULL && pRandFuncTbl->randExit != NULL)
        return ((*pRandFuncTbl->randExit)());

     adpErrnoSet (S_adpRandLib_NOT_SUPPORTED);
     return (ST_ERROR);
    }

/*******************************************************************************
* 
* adpRandGen - call custom PRNG routine
*
* This routine calls a user specific random number generation routine, that
* copies <randSize> number of random bytes into <pRandBuf>
*
* RETURNS: ST_OK, otherwise returns ST_ERROR.
*/
STATUS adpRandGen
    (
    char *    pRandBuf,  /* buffer to store random data */
    int       randSize   /* size of buffer */
    )
    {
    if (pRandFuncTbl != NULL && pRandFuncTbl->randGen != NULL)
        return ((*pRandFuncTbl->randGen) (pRandBuf, randSize));

    adpErrnoSet (S_adpRandLib_NOT_SUPPORTED);
    return (ST_ERROR);
    }

/*******************************************************************************
* 
* adpRandSeed - call a custom random seeding routine
*
* This routine calls a user specific random seeding or entropy addition routine
* using the <seedSize> number of bytes available in <pSeedBuf>
*
* RETURNS: ST_OK, otherwise returns ST_ERROR.
*/
STATUS adpRandSeed
    (
    char *    pSeedBuf,  /* buffer containing entropy data */
    int       seedSize   /* size of buffer */
    )
    {
    if (pRandFuncTbl != NULL && pRandFuncTbl->randSeed != NULL)
        return ((*pRandFuncTbl->randSeed) (pSeedBuf, seedSize));

    adpErrnoSet (S_adpRandLib_NOT_SUPPORTED);
    
    return (ST_ERROR);
    }
