obj-$(CONFIG_LANTIQ_VRX318) += ltq_vrx318.o
obj-$(CONFIG_LANTIQ_ETH_FRAMEWORK) += lantiq_eth_framework.o
obj-$(CONFIG_LTQ_ETH_OAM) += ltq_eth_oam_handler.o
ifneq ($(CONFIG_LTQ_ETH_OAM),)
  obj-y += ltq_eth_oam_netif.o
endif
obj-$(CONFIG_LTQ_ETHSW_API) += switch-api/
