# Makefile - build rules for cron/linux/user
#
# Copyright (c) 2007, TeamF1, Inc.
#
# modification history
# --------------------
# 01a,08Oct07,rks  written.
#
# DESCRIPTION
# This file contains rules to build cron for linux(user space)
#*/

all:
	make -C ./src
	make -C ./src archive
clean:
	make -C ./src clean
