CREATE TABLE DbgSetting (
    "CmDbg_DbgLvl" INTEGER DEFAULT (0),
    "CmDbg_DbgType" INTEGER DEFAULT (0),
    "MmDbg_DbgLvl" INTEGER DEFAULT (0),
    "MmDbg_DbgType" INTEGER DEFAULT (0),
    "AgentsDbg_DbgLvl" INTEGER DEFAULT (0),
    "AgentsDbg_DbgType" INTEGER DEFAULT (0),
    "RtpDbg_DbgLvl" INTEGER DEFAULT (0),
    "RtpDbg_DbgType" INTEGER DEFAULT (0),
    "VmapiDbg_DbgLvl" INTEGER DEFAULT (0),
    "VmapiDbg_DbgType" INTEGER DEFAULT (0),
    "SipDbg_DbgLvl" INTEGER DEFAULT (0),
    "SipDbg_DbgType" INTEGER DEFAULT (0),
    "FaxDbg_DbgLvl" INTEGER DEFAULT (0),
    "FaxDbg_DbgType" INTEGER DEFAULT (0),
    "COMMENT" TEXT
);
CREATE TABLE VoiceProfile (
    "ProfileId"               INTEGER DEFAULT (0),
    "ProfileName"             TEXT DEFAULT ('0'),
    "AssocCountry"            INTEGER DEFAULT (0),
    "State"                   INTEGER DEFAULT (0),
    "Reset"                    INTEGER DEFAULT (0),
    "NoOfLines"               INTEGER DEFAULT (0),
    "Lines"                  INTEGER DEFAULT (0),
    "AssoLineIds"            INTEGER DEFAULT (0),
    "DtmfPayloadType"         INTEGER DEFAULT (0),
    "DtmfMethod"              INTEGER DEFAULT (0),
    "G711DtmfMethod"          INTEGER DEFAULT (0),
    "EnableDigitMap"           INTEGER DEFAULT (0),
    "DigitMap"                TEXT DEFAULT ('0'),
    "EnableStun"               INTEGER DEFAULT (0),
		"StunServer" TEXT DEFAULT ('Null'),
		"StunPort" INTEGER DEFAULT (0),
		"StunUserName" TEXT DEFAULT ('Null'),
		"StunPassword" TEXT DEFAULT ('Null'),
		"NatKeepAliveTime" INTEGER DEFAULT (0),
		"NatType" INTEGER DEFAULT (0),
    "DataResUpBandwidth"      INTEGER DEFAULT (0),
    "DataResDownBandwidth"    INTEGER DEFAULT (0),
    "PstnFailOver"             INTEGER DEFAULT (0),
    "FaxPassThru"              INTEGER DEFAULT (0),
    "ModemPassThru"            INTEGER DEFAULT (0),
    "COMMENT" TEXT
);
CREATE TABLE VoiceProfileSignaling (
		"ProfileId" INTEGER DEFAULT (0),
		"EnableProxy" INTEGER DEFAULT (0),
		"EnableRegistrar"  INTEGER DEFAULT (0),
		"ProxyAddr" TEXT DEFAULT ('0'),
		"ProxyPort"  INTEGER DEFAULT (0),
		"ProxyProtocol"  INTEGER DEFAULT (0),
		"RegistrarAddr" TEXT DEFAULT ('Null'),
		"RegistrarPort" INTEGER DEFAULT (0),
		"RegistrarProtocol" INTEGER DEFAULT (0),
		"BackupRegAddr" TEXT DEFAULT ('Null'),
		"BackupRegPort" INTEGER DEFAULT (0),
		"BackupRegProtocol" INTEGER DEFAULT (0),
		"RegExpirationTime" INTEGER DEFAULT (0),
		"RegExpirationTimePercent" INTEGER DEFAULT (0),
		"RegRetryTime" INTEGER DEFAULT (0),
		"RegRetryAttempts" INTEGER DEFAULT (0),
		"UADomain" TEXT DEFAULT ('Null'),
		"DnsQueryTimeOut" INTEGER DEFAULT (0),
		"UAPort" INTEGER DEFAULT (0),
		"UAProtocol"INTEGER DEFAULT (0),
		"OutboundProxyAddr" TEXT DEFAULT ('Null'),
		"OutboundProxyPort" INTEGER DEFAULT (0),
		"WellKnownSource" INTEGER DEFAULT (0),
		"Org" TEXT DEFAULT ('Null'),
		"T1" INTEGER DEFAULT (0),
		"Tk" INTEGER DEFAULT (0),
		"T2" INTEGER DEFAULT (0),
		"T4" INTEGER DEFAULT (0),
		"Ta" INTEGER DEFAULT (0),
		"Tb" INTEGER DEFAULT (0),
		"Tc" INTEGER DEFAULT (0),
		"Td" INTEGER DEFAULT (0),
		"Te" INTEGER DEFAULT (0),
		"Tf" INTEGER DEFAULT (0),
		"Tg" INTEGER DEFAULT (0),
		"Th" INTEGER DEFAULT (0),
		"Ti" INTEGER DEFAULT (0),
		"Tj" INTEGER DEFAULT (0),
		"InvExpires" INTEGER DEFAULT (0),
		"ReInvExpires" INTEGER DEFAULT (0),
		"RegExpires" INTEGER DEFAULT (0),
		"RegMinExpires" INTEGER DEFAULT (0),
		"InboundAuth" INTEGER DEFAULT (0),
		"InbAuthUserName" TEXT DEFAULT ('Null'),
		"InbAuthPassword" TEXT DEFAULT ('Null'),
		"CohMethod" INTEGER DEFAULT (0),
		"UseCompactHdrs" INTEGER DEFAULT (0),
		"UserAgentHdr" TEXT DEFAULT ('Null'),
		"AnnounceMethod" INTEGER DEFAULT (0),
		"SipDscp" INTEGER DEFAULT (0),
		"SipVlanId" INTEGER DEFAULT (0),
		"SipEthPriority" INTEGER DEFAULT (0),
		"COMMENT" TEXT
);
CREATE TABLE VoiceLine (
		"LineId" INTEGER DEFAULT (0),
		"ProfileId" INTEGER DEFAULT (0),
		"AssocVoiceInterface" INTEGER DEFAULT (0),
		"DirName" TEXT DEFAULT ('Null'),
		"Name" TEXT DEFAULT ('Null'),
		"State" INTEGER DEFAULT (0),
		"LineStatus" INTEGER DEFAULT (0),
		"CallStatus" INTEGER DEFAULT (0),
		"GatewayMode" INTEGER DEFAULT (0),
		"LineMode" INTEGER DEFAULT (0),
		"Intrusion" INTEGER DEFAULT (0),
		"COMMENT" TEXT
);
CREATE TABLE VoiceLineSignaling (
		"ProfileId" INTEGER DEFAULT (0),
		"LineId" INTEGER DEFAULT (0),
		"SipUserName" TEXT DEFAULT ('Null'),
		"SipDispName" TEXT DEFAULT ('Null'),
		"NoOfSipAuthCfg" INTEGER DEFAULT (0),
		"COMMENT" TEXT
);
CREATE TABLE AuthCfg (
		"ProfileId" INTEGER DEFAULT (0),
		"LineId" INTEGER DEFAULT (0),
		"Realm" TEXT DEFAULT ('Null'),
		"SipAuthUsrName" TEXT DEFAULT ('Null'),
		"SipAuthPasswd" TEXT DEFAULT ('Null'),
		"COMMENT" TEXT
);
CREATE TABLE DNSSrv (
		"Priority" INTEGER DEFAULT (0),
		"Weight" INTEGER DEFAULT (0),
		"Port" INTEGER DEFAULT (5060),
		"Domain" TEXT DEFAULT ('Null')
);
