#!/bin/sh

# Defines
if [ ! "$MTLK_INIT_PLATFORM" ]; then			
	. /tmp/mtlk_init_platform.sh
fi

print2log DBG "running wave_wlan_wds_cli: args: $*" 
apIndex=$1

timestamp "wave_wlan_wds_cli:$apIndex:begin"

# Get corresponding wlan network interface from mapping file
wlan=`find_wave_if_from_index $apIndex`

WDSEnabledVal=`host_api get $$ $wlan WDSEnabled`

(. $ETC_PATH/wave_wlan_wds_modify $apIndex)

if [ $WDSEnabledVal -eq 1 ]
then
	(. $ETC_PATH/wave_wlan_sec_modify $apIndex)
fi

print2log DBG "wave_wlan_wds_cli done"
timestamp "wave_wlan_wds_cli:$apIndex:done"