/* soapH.h
   Generated by gSOAP 2.7.9k from tr069.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__unsignedInt
#define SOAP_TYPE_xsd__unsignedInt (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_xsd__unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_xsd__unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum _Enum_1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum _Enum_1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum _Enum_1 *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum _Enum_1);
SOAP_FMAC3 enum _Enum_1 * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum _Enum_1 *, const char*, const char*);
SOAP_FMAC3 enum _Enum_1 * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum _Enum_1 *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum _Enum_1 *);

#ifndef SOAP_TYPE__Enum_1
#define SOAP_TYPE__Enum_1 (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__Enum_1(struct soap*, enum _Enum_1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__Enum_1(struct soap*, const enum _Enum_1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__Enum_1(struct soap*, const char*, int, const enum _Enum_1 *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__Enum_12s(struct soap*, enum _Enum_1);
SOAP_FMAC3 enum _Enum_1 * SOAP_FMAC4 soap_get__Enum_1(struct soap*, enum _Enum_1 *, const char*, const char*);
SOAP_FMAC3 enum _Enum_1 * SOAP_FMAC4 soap_in__Enum_1(struct soap*, const char*, enum _Enum_1 *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_Enum_1(struct soap*, const char*, enum _Enum_1 *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef SOAP_TYPE_cwmp__Reboot
#define SOAP_TYPE_cwmp__Reboot (90)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__Reboot(struct soap*, struct cwmp__Reboot *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__Reboot(struct soap*, const struct cwmp__Reboot *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__Reboot(struct soap*, const struct cwmp__Reboot *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__Reboot(struct soap*, const char*, int, const struct cwmp__Reboot *, const char*);
SOAP_FMAC3 struct cwmp__Reboot * SOAP_FMAC4 soap_get_cwmp__Reboot(struct soap*, struct cwmp__Reboot *, const char*, const char*);
SOAP_FMAC3 struct cwmp__Reboot * SOAP_FMAC4 soap_in_cwmp__Reboot(struct soap*, const char*, struct cwmp__Reboot *, const char*);

#ifndef SOAP_TYPE_RebootResponse
#define SOAP_TYPE_RebootResponse (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_RebootResponse(struct soap*, struct RebootResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_RebootResponse(struct soap*, const struct RebootResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_RebootResponse(struct soap*, const struct RebootResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_RebootResponse(struct soap*, const char*, int, const struct RebootResponse *, const char*);
SOAP_FMAC3 struct RebootResponse * SOAP_FMAC4 soap_get_RebootResponse(struct soap*, struct RebootResponse *, const char*, const char*);
SOAP_FMAC3 struct RebootResponse * SOAP_FMAC4 soap_in_RebootResponse(struct soap*, const char*, struct RebootResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__FactoryReset
#define SOAP_TYPE_cwmp__FactoryReset (86)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__FactoryReset(struct soap*, struct cwmp__FactoryReset *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__FactoryReset(struct soap*, const struct cwmp__FactoryReset *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__FactoryReset(struct soap*, const struct cwmp__FactoryReset *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__FactoryReset(struct soap*, const char*, int, const struct cwmp__FactoryReset *, const char*);
SOAP_FMAC3 struct cwmp__FactoryReset * SOAP_FMAC4 soap_get_cwmp__FactoryReset(struct soap*, struct cwmp__FactoryReset *, const char*, const char*);
SOAP_FMAC3 struct cwmp__FactoryReset * SOAP_FMAC4 soap_in_cwmp__FactoryReset(struct soap*, const char*, struct cwmp__FactoryReset *, const char*);

#ifndef SOAP_TYPE_FactoryResetResponse
#define SOAP_TYPE_FactoryResetResponse (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_FactoryResetResponse(struct soap*, struct FactoryResetResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_FactoryResetResponse(struct soap*, const struct FactoryResetResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_FactoryResetResponse(struct soap*, const struct FactoryResetResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_FactoryResetResponse(struct soap*, const char*, int, const struct FactoryResetResponse *, const char*);
SOAP_FMAC3 struct FactoryResetResponse * SOAP_FMAC4 soap_get_FactoryResetResponse(struct soap*, struct FactoryResetResponse *, const char*, const char*);
SOAP_FMAC3 struct FactoryResetResponse * SOAP_FMAC4 soap_in_FactoryResetResponse(struct soap*, const char*, struct FactoryResetResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__DeleteObject
#define SOAP_TYPE_cwmp__DeleteObject (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__DeleteObject(struct soap*, struct cwmp__DeleteObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__DeleteObject(struct soap*, const struct cwmp__DeleteObject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__DeleteObject(struct soap*, const struct cwmp__DeleteObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__DeleteObject(struct soap*, const char*, int, const struct cwmp__DeleteObject *, const char*);
SOAP_FMAC3 struct cwmp__DeleteObject * SOAP_FMAC4 soap_get_cwmp__DeleteObject(struct soap*, struct cwmp__DeleteObject *, const char*, const char*);
SOAP_FMAC3 struct cwmp__DeleteObject * SOAP_FMAC4 soap_in_cwmp__DeleteObject(struct soap*, const char*, struct cwmp__DeleteObject *, const char*);

#ifndef SOAP_TYPE_cwmp__DeleteObjectResponse
#define SOAP_TYPE_cwmp__DeleteObjectResponse (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__DeleteObjectResponse(struct soap*, struct cwmp__DeleteObjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__DeleteObjectResponse(struct soap*, const struct cwmp__DeleteObjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__DeleteObjectResponse(struct soap*, const struct cwmp__DeleteObjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__DeleteObjectResponse(struct soap*, const char*, int, const struct cwmp__DeleteObjectResponse *, const char*);
SOAP_FMAC3 struct cwmp__DeleteObjectResponse * SOAP_FMAC4 soap_get_cwmp__DeleteObjectResponse(struct soap*, struct cwmp__DeleteObjectResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__DeleteObjectResponse * SOAP_FMAC4 soap_in_cwmp__DeleteObjectResponse(struct soap*, const char*, struct cwmp__DeleteObjectResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__AddObject
#define SOAP_TYPE_cwmp__AddObject (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__AddObject(struct soap*, struct cwmp__AddObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__AddObject(struct soap*, const struct cwmp__AddObject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__AddObject(struct soap*, const struct cwmp__AddObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__AddObject(struct soap*, const char*, int, const struct cwmp__AddObject *, const char*);
SOAP_FMAC3 struct cwmp__AddObject * SOAP_FMAC4 soap_get_cwmp__AddObject(struct soap*, struct cwmp__AddObject *, const char*, const char*);
SOAP_FMAC3 struct cwmp__AddObject * SOAP_FMAC4 soap_in_cwmp__AddObject(struct soap*, const char*, struct cwmp__AddObject *, const char*);

#ifndef SOAP_TYPE_cwmp__TransferComplete
#define SOAP_TYPE_cwmp__TransferComplete (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__TransferComplete(struct soap*, struct cwmp__TransferComplete *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__TransferComplete(struct soap*, const struct cwmp__TransferComplete *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__TransferComplete(struct soap*, const struct cwmp__TransferComplete *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__TransferComplete(struct soap*, const char*, int, const struct cwmp__TransferComplete *, const char*);
SOAP_FMAC3 struct cwmp__TransferComplete * SOAP_FMAC4 soap_get_cwmp__TransferComplete(struct soap*, struct cwmp__TransferComplete *, const char*, const char*);
SOAP_FMAC3 struct cwmp__TransferComplete * SOAP_FMAC4 soap_in_cwmp__TransferComplete(struct soap*, const char*, struct cwmp__TransferComplete *, const char*);

#ifndef SOAP_TYPE_cwmp__TransferCompleteResponse
#define SOAP_TYPE_cwmp__TransferCompleteResponse (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__TransferCompleteResponse(struct soap*, struct cwmp__TransferCompleteResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__TransferCompleteResponse(struct soap*, const struct cwmp__TransferCompleteResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__TransferCompleteResponse(struct soap*, const struct cwmp__TransferCompleteResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__TransferCompleteResponse(struct soap*, const char*, int, const struct cwmp__TransferCompleteResponse *, const char*);
SOAP_FMAC3 struct cwmp__TransferCompleteResponse * SOAP_FMAC4 soap_get_cwmp__TransferCompleteResponse(struct soap*, struct cwmp__TransferCompleteResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__TransferCompleteResponse * SOAP_FMAC4 soap_in_cwmp__TransferCompleteResponse(struct soap*, const char*, struct cwmp__TransferCompleteResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__Download
#define SOAP_TYPE_cwmp__Download (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__Download(struct soap*, struct cwmp__Download *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__Download(struct soap*, const struct cwmp__Download *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__Download(struct soap*, const struct cwmp__Download *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__Download(struct soap*, const char*, int, const struct cwmp__Download *, const char*);
SOAP_FMAC3 struct cwmp__Download * SOAP_FMAC4 soap_get_cwmp__Download(struct soap*, struct cwmp__Download *, const char*, const char*);
SOAP_FMAC3 struct cwmp__Download * SOAP_FMAC4 soap_in_cwmp__Download(struct soap*, const char*, struct cwmp__Download *, const char*);

#ifndef SOAP_TYPE_cwmp__GetParameterAttributes
#define SOAP_TYPE_cwmp__GetParameterAttributes (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__GetParameterAttributes(struct soap*, struct cwmp__GetParameterAttributes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__GetParameterAttributes(struct soap*, const struct cwmp__GetParameterAttributes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__GetParameterAttributes(struct soap*, const struct cwmp__GetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__GetParameterAttributes(struct soap*, const char*, int, const struct cwmp__GetParameterAttributes *, const char*);
SOAP_FMAC3 struct cwmp__GetParameterAttributes * SOAP_FMAC4 soap_get_cwmp__GetParameterAttributes(struct soap*, struct cwmp__GetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 struct cwmp__GetParameterAttributes * SOAP_FMAC4 soap_in_cwmp__GetParameterAttributes(struct soap*, const char*, struct cwmp__GetParameterAttributes *, const char*);

#ifndef SOAP_TYPE_cwmp__GetParameterAttributesResponse
#define SOAP_TYPE_cwmp__GetParameterAttributesResponse (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__GetParameterAttributesResponse(struct soap*, struct cwmp__GetParameterAttributesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__GetParameterAttributesResponse(struct soap*, const struct cwmp__GetParameterAttributesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__GetParameterAttributesResponse(struct soap*, const struct cwmp__GetParameterAttributesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__GetParameterAttributesResponse(struct soap*, const char*, int, const struct cwmp__GetParameterAttributesResponse *, const char*);
SOAP_FMAC3 struct cwmp__GetParameterAttributesResponse * SOAP_FMAC4 soap_get_cwmp__GetParameterAttributesResponse(struct soap*, struct cwmp__GetParameterAttributesResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__GetParameterAttributesResponse * SOAP_FMAC4 soap_in_cwmp__GetParameterAttributesResponse(struct soap*, const char*, struct cwmp__GetParameterAttributesResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__SetParameterAttributes
#define SOAP_TYPE_cwmp__SetParameterAttributes (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__SetParameterAttributes(struct soap*, struct cwmp__SetParameterAttributes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__SetParameterAttributes(struct soap*, const struct cwmp__SetParameterAttributes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__SetParameterAttributes(struct soap*, const struct cwmp__SetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__SetParameterAttributes(struct soap*, const char*, int, const struct cwmp__SetParameterAttributes *, const char*);
SOAP_FMAC3 struct cwmp__SetParameterAttributes * SOAP_FMAC4 soap_get_cwmp__SetParameterAttributes(struct soap*, struct cwmp__SetParameterAttributes *, const char*, const char*);
SOAP_FMAC3 struct cwmp__SetParameterAttributes * SOAP_FMAC4 soap_in_cwmp__SetParameterAttributes(struct soap*, const char*, struct cwmp__SetParameterAttributes *, const char*);

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesResponse
#define SOAP_TYPE_cwmp__SetParameterAttributesResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__SetParameterAttributesResponse(struct soap*, struct cwmp__SetParameterAttributesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__SetParameterAttributesResponse(struct soap*, const struct cwmp__SetParameterAttributesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__SetParameterAttributesResponse(struct soap*, const struct cwmp__SetParameterAttributesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__SetParameterAttributesResponse(struct soap*, const char*, int, const struct cwmp__SetParameterAttributesResponse *, const char*);
SOAP_FMAC3 struct cwmp__SetParameterAttributesResponse * SOAP_FMAC4 soap_get_cwmp__SetParameterAttributesResponse(struct soap*, struct cwmp__SetParameterAttributesResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__SetParameterAttributesResponse * SOAP_FMAC4 soap_in_cwmp__SetParameterAttributesResponse(struct soap*, const char*, struct cwmp__SetParameterAttributesResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__GetParameterValues
#define SOAP_TYPE_cwmp__GetParameterValues (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__GetParameterValues(struct soap*, struct cwmp__GetParameterValues *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__GetParameterValues(struct soap*, const struct cwmp__GetParameterValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__GetParameterValues(struct soap*, const struct cwmp__GetParameterValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__GetParameterValues(struct soap*, const char*, int, const struct cwmp__GetParameterValues *, const char*);
SOAP_FMAC3 struct cwmp__GetParameterValues * SOAP_FMAC4 soap_get_cwmp__GetParameterValues(struct soap*, struct cwmp__GetParameterValues *, const char*, const char*);
SOAP_FMAC3 struct cwmp__GetParameterValues * SOAP_FMAC4 soap_in_cwmp__GetParameterValues(struct soap*, const char*, struct cwmp__GetParameterValues *, const char*);

#ifndef SOAP_TYPE_cwmp__GetParameterValuesResponse
#define SOAP_TYPE_cwmp__GetParameterValuesResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__GetParameterValuesResponse(struct soap*, struct cwmp__GetParameterValuesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__GetParameterValuesResponse(struct soap*, const struct cwmp__GetParameterValuesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__GetParameterValuesResponse(struct soap*, const struct cwmp__GetParameterValuesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__GetParameterValuesResponse(struct soap*, const char*, int, const struct cwmp__GetParameterValuesResponse *, const char*);
SOAP_FMAC3 struct cwmp__GetParameterValuesResponse * SOAP_FMAC4 soap_get_cwmp__GetParameterValuesResponse(struct soap*, struct cwmp__GetParameterValuesResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__GetParameterValuesResponse * SOAP_FMAC4 soap_in_cwmp__GetParameterValuesResponse(struct soap*, const char*, struct cwmp__GetParameterValuesResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__SetParameterValues
#define SOAP_TYPE_cwmp__SetParameterValues (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__SetParameterValues(struct soap*, struct cwmp__SetParameterValues *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__SetParameterValues(struct soap*, const struct cwmp__SetParameterValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__SetParameterValues(struct soap*, const struct cwmp__SetParameterValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__SetParameterValues(struct soap*, const char*, int, const struct cwmp__SetParameterValues *, const char*);
SOAP_FMAC3 struct cwmp__SetParameterValues * SOAP_FMAC4 soap_get_cwmp__SetParameterValues(struct soap*, struct cwmp__SetParameterValues *, const char*, const char*);
SOAP_FMAC3 struct cwmp__SetParameterValues * SOAP_FMAC4 soap_in_cwmp__SetParameterValues(struct soap*, const char*, struct cwmp__SetParameterValues *, const char*);

#ifndef SOAP_TYPE_cwmp__SetParameterValuesResponse
#define SOAP_TYPE_cwmp__SetParameterValuesResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__SetParameterValuesResponse(struct soap*, struct cwmp__SetParameterValuesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__SetParameterValuesResponse(struct soap*, const struct cwmp__SetParameterValuesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__SetParameterValuesResponse(struct soap*, const struct cwmp__SetParameterValuesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__SetParameterValuesResponse(struct soap*, const char*, int, const struct cwmp__SetParameterValuesResponse *, const char*);
SOAP_FMAC3 struct cwmp__SetParameterValuesResponse * SOAP_FMAC4 soap_get_cwmp__SetParameterValuesResponse(struct soap*, struct cwmp__SetParameterValuesResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__SetParameterValuesResponse * SOAP_FMAC4 soap_in_cwmp__SetParameterValuesResponse(struct soap*, const char*, struct cwmp__SetParameterValuesResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__GetParameterNames
#define SOAP_TYPE_cwmp__GetParameterNames (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__GetParameterNames(struct soap*, struct cwmp__GetParameterNames *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__GetParameterNames(struct soap*, const struct cwmp__GetParameterNames *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__GetParameterNames(struct soap*, const struct cwmp__GetParameterNames *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__GetParameterNames(struct soap*, const char*, int, const struct cwmp__GetParameterNames *, const char*);
SOAP_FMAC3 struct cwmp__GetParameterNames * SOAP_FMAC4 soap_get_cwmp__GetParameterNames(struct soap*, struct cwmp__GetParameterNames *, const char*, const char*);
SOAP_FMAC3 struct cwmp__GetParameterNames * SOAP_FMAC4 soap_in_cwmp__GetParameterNames(struct soap*, const char*, struct cwmp__GetParameterNames *, const char*);

#ifndef SOAP_TYPE_cwmp__GetParameterNamesResponse
#define SOAP_TYPE_cwmp__GetParameterNamesResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__GetParameterNamesResponse(struct soap*, struct cwmp__GetParameterNamesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__GetParameterNamesResponse(struct soap*, const struct cwmp__GetParameterNamesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__GetParameterNamesResponse(struct soap*, const struct cwmp__GetParameterNamesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__GetParameterNamesResponse(struct soap*, const char*, int, const struct cwmp__GetParameterNamesResponse *, const char*);
SOAP_FMAC3 struct cwmp__GetParameterNamesResponse * SOAP_FMAC4 soap_get_cwmp__GetParameterNamesResponse(struct soap*, struct cwmp__GetParameterNamesResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__GetParameterNamesResponse * SOAP_FMAC4 soap_in_cwmp__GetParameterNamesResponse(struct soap*, const char*, struct cwmp__GetParameterNamesResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__GetRPCMethods
#define SOAP_TYPE_cwmp__GetRPCMethods (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__GetRPCMethods(struct soap*, struct cwmp__GetRPCMethods *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__GetRPCMethods(struct soap*, const struct cwmp__GetRPCMethods *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__GetRPCMethods(struct soap*, const struct cwmp__GetRPCMethods *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__GetRPCMethods(struct soap*, const char*, int, const struct cwmp__GetRPCMethods *, const char*);
SOAP_FMAC3 struct cwmp__GetRPCMethods * SOAP_FMAC4 soap_get_cwmp__GetRPCMethods(struct soap*, struct cwmp__GetRPCMethods *, const char*, const char*);
SOAP_FMAC3 struct cwmp__GetRPCMethods * SOAP_FMAC4 soap_in_cwmp__GetRPCMethods(struct soap*, const char*, struct cwmp__GetRPCMethods *, const char*);

#ifndef SOAP_TYPE_cwmp__GetRPCMethodsResponse
#define SOAP_TYPE_cwmp__GetRPCMethodsResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__GetRPCMethodsResponse(struct soap*, struct cwmp__GetRPCMethodsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__GetRPCMethodsResponse(struct soap*, const struct cwmp__GetRPCMethodsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__GetRPCMethodsResponse(struct soap*, const struct cwmp__GetRPCMethodsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__GetRPCMethodsResponse(struct soap*, const char*, int, const struct cwmp__GetRPCMethodsResponse *, const char*);
SOAP_FMAC3 struct cwmp__GetRPCMethodsResponse * SOAP_FMAC4 soap_get_cwmp__GetRPCMethodsResponse(struct soap*, struct cwmp__GetRPCMethodsResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__GetRPCMethodsResponse * SOAP_FMAC4 soap_in_cwmp__GetRPCMethodsResponse(struct soap*, const char*, struct cwmp__GetRPCMethodsResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__Inform
#define SOAP_TYPE_cwmp__Inform (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__Inform(struct soap*, struct cwmp__Inform *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__Inform(struct soap*, const struct cwmp__Inform *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__Inform(struct soap*, const struct cwmp__Inform *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__Inform(struct soap*, const char*, int, const struct cwmp__Inform *, const char*);
SOAP_FMAC3 struct cwmp__Inform * SOAP_FMAC4 soap_get_cwmp__Inform(struct soap*, struct cwmp__Inform *, const char*, const char*);
SOAP_FMAC3 struct cwmp__Inform * SOAP_FMAC4 soap_in_cwmp__Inform(struct soap*, const char*, struct cwmp__Inform *, const char*);

#ifndef SOAP_TYPE_cwmp__AddObjectResponse
#define SOAP_TYPE_cwmp__AddObjectResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__AddObjectResponse(struct soap*, struct cwmp__AddObjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__AddObjectResponse(struct soap*, const struct cwmp__AddObjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__AddObjectResponse(struct soap*, const struct cwmp__AddObjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__AddObjectResponse(struct soap*, const char*, int, const struct cwmp__AddObjectResponse *, const char*);
SOAP_FMAC3 struct cwmp__AddObjectResponse * SOAP_FMAC4 soap_get_cwmp__AddObjectResponse(struct soap*, struct cwmp__AddObjectResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__AddObjectResponse * SOAP_FMAC4 soap_in_cwmp__AddObjectResponse(struct soap*, const char*, struct cwmp__AddObjectResponse *, const char*);

#ifndef SOAP_TYPE_cwmp__FaultStruct
#define SOAP_TYPE_cwmp__FaultStruct (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__FaultStruct(struct soap*, struct cwmp__FaultStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__FaultStruct(struct soap*, const struct cwmp__FaultStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__FaultStruct(struct soap*, const struct cwmp__FaultStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__FaultStruct(struct soap*, const char*, int, const struct cwmp__FaultStruct *, const char*);
SOAP_FMAC3 struct cwmp__FaultStruct * SOAP_FMAC4 soap_get_cwmp__FaultStruct(struct soap*, struct cwmp__FaultStruct *, const char*, const char*);
SOAP_FMAC3 struct cwmp__FaultStruct * SOAP_FMAC4 soap_in_cwmp__FaultStruct(struct soap*, const char*, struct cwmp__FaultStruct *, const char*);

#ifndef SOAP_TYPE_cwmp__Fault
#define SOAP_TYPE_cwmp__Fault (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__Fault(struct soap*, struct cwmp__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__Fault(struct soap*, const struct cwmp__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__Fault(struct soap*, const struct cwmp__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__Fault(struct soap*, const char*, int, const struct cwmp__Fault *, const char*);
SOAP_FMAC3 struct cwmp__Fault * SOAP_FMAC4 soap_get_cwmp__Fault(struct soap*, struct cwmp__Fault *, const char*, const char*);
SOAP_FMAC3 struct cwmp__Fault * SOAP_FMAC4 soap_in_cwmp__Fault(struct soap*, const char*, struct cwmp__Fault *, const char*);

#ifndef SOAP_TYPE_cwmp__DownloadResponse
#define SOAP_TYPE_cwmp__DownloadResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__DownloadResponse(struct soap*, struct cwmp__DownloadResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__DownloadResponse(struct soap*, const struct cwmp__DownloadResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__DownloadResponse(struct soap*, const struct cwmp__DownloadResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__DownloadResponse(struct soap*, const char*, int, const struct cwmp__DownloadResponse *, const char*);
SOAP_FMAC3 struct cwmp__DownloadResponse * SOAP_FMAC4 soap_get_cwmp__DownloadResponse(struct soap*, struct cwmp__DownloadResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__DownloadResponse * SOAP_FMAC4 soap_in_cwmp__DownloadResponse(struct soap*, const char*, struct cwmp__DownloadResponse *, const char*);

#ifndef SOAP_TYPE_ParameterList_GetAttributes
#define SOAP_TYPE_ParameterList_GetAttributes (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ParameterList_GetAttributes(struct soap*, struct ParameterList_GetAttributes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ParameterList_GetAttributes(struct soap*, struct ParameterList_GetAttributes const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ParameterList_GetAttributes(struct soap*, const struct ParameterList_GetAttributes *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterList_GetAttributes(struct soap*, const char*, int, const struct ParameterList_GetAttributes *, const char*);
SOAP_FMAC3 struct ParameterList_GetAttributes * SOAP_FMAC4 soap_get_ParameterList_GetAttributes(struct soap*, struct ParameterList_GetAttributes *, const char*, const char*);
SOAP_FMAC3 struct ParameterList_GetAttributes * SOAP_FMAC4 soap_in_ParameterList_GetAttributes(struct soap*, const char*, struct ParameterList_GetAttributes *, const char*);

#ifndef SOAP_TYPE_ParameterAttributeStruct
#define SOAP_TYPE_ParameterAttributeStruct (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ParameterAttributeStruct(struct soap*, struct ParameterAttributeStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ParameterAttributeStruct(struct soap*, const struct ParameterAttributeStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ParameterAttributeStruct(struct soap*, const struct ParameterAttributeStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterAttributeStruct(struct soap*, const char*, int, const struct ParameterAttributeStruct *, const char*);
SOAP_FMAC3 struct ParameterAttributeStruct * SOAP_FMAC4 soap_get_ParameterAttributeStruct(struct soap*, struct ParameterAttributeStruct *, const char*, const char*);
SOAP_FMAC3 struct ParameterAttributeStruct * SOAP_FMAC4 soap_in_ParameterAttributeStruct(struct soap*, const char*, struct ParameterAttributeStruct *, const char*);

#ifndef SOAP_TYPE_ParameterList_Attributes
#define SOAP_TYPE_ParameterList_Attributes (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ParameterList_Attributes(struct soap*, struct ParameterList_Attributes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ParameterList_Attributes(struct soap*, struct ParameterList_Attributes const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ParameterList_Attributes(struct soap*, const struct ParameterList_Attributes *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterList_Attributes(struct soap*, const char*, int, const struct ParameterList_Attributes *, const char*);
SOAP_FMAC3 struct ParameterList_Attributes * SOAP_FMAC4 soap_get_ParameterList_Attributes(struct soap*, struct ParameterList_Attributes *, const char*, const char*);
SOAP_FMAC3 struct ParameterList_Attributes * SOAP_FMAC4 soap_in_ParameterList_Attributes(struct soap*, const char*, struct ParameterList_Attributes *, const char*);

#ifndef SOAP_TYPE_SetParameterAttributesStruct
#define SOAP_TYPE_SetParameterAttributesStruct (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SetParameterAttributesStruct(struct soap*, struct SetParameterAttributesStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SetParameterAttributesStruct(struct soap*, const struct SetParameterAttributesStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SetParameterAttributesStruct(struct soap*, const struct SetParameterAttributesStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SetParameterAttributesStruct(struct soap*, const char*, int, const struct SetParameterAttributesStruct *, const char*);
SOAP_FMAC3 struct SetParameterAttributesStruct * SOAP_FMAC4 soap_get_SetParameterAttributesStruct(struct soap*, struct SetParameterAttributesStruct *, const char*, const char*);
SOAP_FMAC3 struct SetParameterAttributesStruct * SOAP_FMAC4 soap_in_SetParameterAttributesStruct(struct soap*, const char*, struct SetParameterAttributesStruct *, const char*);

#ifndef SOAP_TYPE_ParameterList_Name
#define SOAP_TYPE_ParameterList_Name (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ParameterList_Name(struct soap*, struct ParameterList_Name *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ParameterList_Name(struct soap*, struct ParameterList_Name const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ParameterList_Name(struct soap*, const struct ParameterList_Name *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterList_Name(struct soap*, const char*, int, const struct ParameterList_Name *, const char*);
SOAP_FMAC3 struct ParameterList_Name * SOAP_FMAC4 soap_get_ParameterList_Name(struct soap*, struct ParameterList_Name *, const char*, const char*);
SOAP_FMAC3 struct ParameterList_Name * SOAP_FMAC4 soap_in_ParameterList_Name(struct soap*, const char*, struct ParameterList_Name *, const char*);

#ifndef SOAP_TYPE_ParameterInfoStruct
#define SOAP_TYPE_ParameterInfoStruct (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ParameterInfoStruct(struct soap*, struct ParameterInfoStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ParameterInfoStruct(struct soap*, const struct ParameterInfoStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ParameterInfoStruct(struct soap*, const struct ParameterInfoStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterInfoStruct(struct soap*, const char*, int, const struct ParameterInfoStruct *, const char*);
SOAP_FMAC3 struct ParameterInfoStruct * SOAP_FMAC4 soap_get_ParameterInfoStruct(struct soap*, struct ParameterInfoStruct *, const char*, const char*);
SOAP_FMAC3 struct ParameterInfoStruct * SOAP_FMAC4 soap_in_ParameterInfoStruct(struct soap*, const char*, struct ParameterInfoStruct *, const char*);

#ifndef SOAP_TYPE_ArrayOfstring
#define SOAP_TYPE_ArrayOfstring (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfstring(struct soap*, struct ArrayOfstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfstring(struct soap*, struct ArrayOfstring const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfstring(struct soap*, const struct ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfstring(struct soap*, const char*, int, const struct ArrayOfstring *, const char*);
SOAP_FMAC3 struct ArrayOfstring * SOAP_FMAC4 soap_get_ArrayOfstring(struct soap*, struct ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfstring * SOAP_FMAC4 soap_in_ArrayOfstring(struct soap*, const char*, struct ArrayOfstring *, const char*);

#ifndef SOAP_TYPE_ParameterList_Value
#define SOAP_TYPE_ParameterList_Value (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ParameterList_Value(struct soap*, struct ParameterList_Value *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ParameterList_Value(struct soap*, struct ParameterList_Value const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ParameterList_Value(struct soap*, const struct ParameterList_Value *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterList_Value(struct soap*, const char*, int, const struct ParameterList_Value *, const char*);
SOAP_FMAC3 struct ParameterList_Value * SOAP_FMAC4 soap_get_ParameterList_Value(struct soap*, struct ParameterList_Value *, const char*, const char*);
SOAP_FMAC3 struct ParameterList_Value * SOAP_FMAC4 soap_in_ParameterList_Value(struct soap*, const char*, struct ParameterList_Value *, const char*);

#ifndef SOAP_TYPE_ParameterValueStruct
#define SOAP_TYPE_ParameterValueStruct (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ParameterValueStruct(struct soap*, struct ParameterValueStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ParameterValueStruct(struct soap*, const struct ParameterValueStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ParameterValueStruct(struct soap*, const struct ParameterValueStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ParameterValueStruct(struct soap*, const char*, int, const struct ParameterValueStruct *, const char*);
SOAP_FMAC3 struct ParameterValueStruct * SOAP_FMAC4 soap_get_ParameterValueStruct(struct soap*, struct ParameterValueStruct *, const char*, const char*);
SOAP_FMAC3 struct ParameterValueStruct * SOAP_FMAC4 soap_in_ParameterValueStruct(struct soap*, const char*, struct ParameterValueStruct *, const char*);

#ifndef SOAP_TYPE_cwmp__InformResponse
#define SOAP_TYPE_cwmp__InformResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__InformResponse(struct soap*, struct cwmp__InformResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__InformResponse(struct soap*, const struct cwmp__InformResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__InformResponse(struct soap*, const struct cwmp__InformResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__InformResponse(struct soap*, const char*, int, const struct cwmp__InformResponse *, const char*);
SOAP_FMAC3 struct cwmp__InformResponse * SOAP_FMAC4 soap_get_cwmp__InformResponse(struct soap*, struct cwmp__InformResponse *, const char*, const char*);
SOAP_FMAC3 struct cwmp__InformResponse * SOAP_FMAC4 soap_in_cwmp__InformResponse(struct soap*, const char*, struct cwmp__InformResponse *, const char*);

#ifndef SOAP_TYPE_EventArray
#define SOAP_TYPE_EventArray (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EventArray(struct soap*, struct EventArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EventArray(struct soap*, struct EventArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EventArray(struct soap*, const struct EventArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EventArray(struct soap*, const char*, int, const struct EventArray *, const char*);
SOAP_FMAC3 struct EventArray * SOAP_FMAC4 soap_get_EventArray(struct soap*, struct EventArray *, const char*, const char*);
SOAP_FMAC3 struct EventArray * SOAP_FMAC4 soap_in_EventArray(struct soap*, const char*, struct EventArray *, const char*);

#ifndef SOAP_TYPE_EventStruct
#define SOAP_TYPE_EventStruct (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EventStruct(struct soap*, struct EventStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EventStruct(struct soap*, const struct EventStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EventStruct(struct soap*, const struct EventStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EventStruct(struct soap*, const char*, int, const struct EventStruct *, const char*);
SOAP_FMAC3 struct EventStruct * SOAP_FMAC4 soap_get_EventStruct(struct soap*, struct EventStruct *, const char*, const char*);
SOAP_FMAC3 struct EventStruct * SOAP_FMAC4 soap_in_EventStruct(struct soap*, const char*, struct EventStruct *, const char*);

#ifndef SOAP_TYPE_DeviceIdStruct
#define SOAP_TYPE_DeviceIdStruct (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_DeviceIdStruct(struct soap*, struct DeviceIdStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_DeviceIdStruct(struct soap*, const struct DeviceIdStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_DeviceIdStruct(struct soap*, const struct DeviceIdStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_DeviceIdStruct(struct soap*, const char*, int, const struct DeviceIdStruct *, const char*);
SOAP_FMAC3 struct DeviceIdStruct * SOAP_FMAC4 soap_get_DeviceIdStruct(struct soap*, struct DeviceIdStruct *, const char*, const char*);
SOAP_FMAC3 struct DeviceIdStruct * SOAP_FMAC4 soap_in_DeviceIdStruct(struct soap*, const char*, struct DeviceIdStruct *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (97)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (96)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (92)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToRebootResponse
#define SOAP_TYPE_PointerToRebootResponse (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToRebootResponse(struct soap*, struct RebootResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToRebootResponse(struct soap*, struct RebootResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToRebootResponse(struct soap*, const char *, int, struct RebootResponse *const*, const char *);
SOAP_FMAC3 struct RebootResponse ** SOAP_FMAC4 soap_get_PointerToRebootResponse(struct soap*, struct RebootResponse **, const char*, const char*);
SOAP_FMAC3 struct RebootResponse ** SOAP_FMAC4 soap_in_PointerToRebootResponse(struct soap*, const char*, struct RebootResponse **, const char*);

#ifndef SOAP_TYPE_PointerToFactoryResetResponse
#define SOAP_TYPE_PointerToFactoryResetResponse (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToFactoryResetResponse(struct soap*, struct FactoryResetResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToFactoryResetResponse(struct soap*, struct FactoryResetResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToFactoryResetResponse(struct soap*, const char *, int, struct FactoryResetResponse *const*, const char *);
SOAP_FMAC3 struct FactoryResetResponse ** SOAP_FMAC4 soap_get_PointerToFactoryResetResponse(struct soap*, struct FactoryResetResponse **, const char*, const char*);
SOAP_FMAC3 struct FactoryResetResponse ** SOAP_FMAC4 soap_in_PointerToFactoryResetResponse(struct soap*, const char*, struct FactoryResetResponse **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__int
#define SOAP_TYPE_PointerToxsd__int (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__int(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__int(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__int(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToxsd__int(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToxsd__int(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerTocwmp__AddObjectResponse
#define SOAP_TYPE_PointerTocwmp__AddObjectResponse (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocwmp__AddObjectResponse(struct soap*, struct cwmp__AddObjectResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocwmp__AddObjectResponse(struct soap*, struct cwmp__AddObjectResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocwmp__AddObjectResponse(struct soap*, const char *, int, struct cwmp__AddObjectResponse *const*, const char *);
SOAP_FMAC3 struct cwmp__AddObjectResponse ** SOAP_FMAC4 soap_get_PointerTocwmp__AddObjectResponse(struct soap*, struct cwmp__AddObjectResponse **, const char*, const char*);
SOAP_FMAC3 struct cwmp__AddObjectResponse ** SOAP_FMAC4 soap_in_PointerTocwmp__AddObjectResponse(struct soap*, const char*, struct cwmp__AddObjectResponse **, const char*);

#ifndef SOAP_TYPE_PointerTocwmp__TransferCompleteResponse
#define SOAP_TYPE_PointerTocwmp__TransferCompleteResponse (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocwmp__TransferCompleteResponse(struct soap*, struct cwmp__TransferCompleteResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocwmp__TransferCompleteResponse(struct soap*, struct cwmp__TransferCompleteResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocwmp__TransferCompleteResponse(struct soap*, const char *, int, struct cwmp__TransferCompleteResponse *const*, const char *);
SOAP_FMAC3 struct cwmp__TransferCompleteResponse ** SOAP_FMAC4 soap_get_PointerTocwmp__TransferCompleteResponse(struct soap*, struct cwmp__TransferCompleteResponse **, const char*, const char*);
SOAP_FMAC3 struct cwmp__TransferCompleteResponse ** SOAP_FMAC4 soap_in_PointerTocwmp__TransferCompleteResponse(struct soap*, const char*, struct cwmp__TransferCompleteResponse **, const char*);

#ifndef SOAP_TYPE_PointerTocwmp__FaultStruct
#define SOAP_TYPE_PointerTocwmp__FaultStruct (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocwmp__FaultStruct(struct soap*, struct cwmp__FaultStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocwmp__FaultStruct(struct soap*, struct cwmp__FaultStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocwmp__FaultStruct(struct soap*, const char *, int, struct cwmp__FaultStruct *const*, const char *);
SOAP_FMAC3 struct cwmp__FaultStruct ** SOAP_FMAC4 soap_get_PointerTocwmp__FaultStruct(struct soap*, struct cwmp__FaultStruct **, const char*, const char*);
SOAP_FMAC3 struct cwmp__FaultStruct ** SOAP_FMAC4 soap_in_PointerTocwmp__FaultStruct(struct soap*, const char*, struct cwmp__FaultStruct **, const char*);

#ifndef SOAP_TYPE_PointerTocwmp__DownloadResponse
#define SOAP_TYPE_PointerTocwmp__DownloadResponse (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocwmp__DownloadResponse(struct soap*, struct cwmp__DownloadResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocwmp__DownloadResponse(struct soap*, struct cwmp__DownloadResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocwmp__DownloadResponse(struct soap*, const char *, int, struct cwmp__DownloadResponse *const*, const char *);
SOAP_FMAC3 struct cwmp__DownloadResponse ** SOAP_FMAC4 soap_get_PointerTocwmp__DownloadResponse(struct soap*, struct cwmp__DownloadResponse **, const char*, const char*);
SOAP_FMAC3 struct cwmp__DownloadResponse ** SOAP_FMAC4 soap_in_PointerTocwmp__DownloadResponse(struct soap*, const char*, struct cwmp__DownloadResponse **, const char*);

#ifndef SOAP_TYPE_PointerToParameterList_GetAttributes
#define SOAP_TYPE_PointerToParameterList_GetAttributes (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterList_GetAttributes(struct soap*, struct ParameterList_GetAttributes *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterList_GetAttributes(struct soap*, struct ParameterList_GetAttributes *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterList_GetAttributes(struct soap*, const char *, int, struct ParameterList_GetAttributes *const*, const char *);
SOAP_FMAC3 struct ParameterList_GetAttributes ** SOAP_FMAC4 soap_get_PointerToParameterList_GetAttributes(struct soap*, struct ParameterList_GetAttributes **, const char*, const char*);
SOAP_FMAC3 struct ParameterList_GetAttributes ** SOAP_FMAC4 soap_in_PointerToParameterList_GetAttributes(struct soap*, const char*, struct ParameterList_GetAttributes **, const char*);

#ifndef SOAP_TYPE_PointerTocwmp__SetParameterAttributesResponse
#define SOAP_TYPE_PointerTocwmp__SetParameterAttributesResponse (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocwmp__SetParameterAttributesResponse(struct soap*, struct cwmp__SetParameterAttributesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocwmp__SetParameterAttributesResponse(struct soap*, struct cwmp__SetParameterAttributesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocwmp__SetParameterAttributesResponse(struct soap*, const char *, int, struct cwmp__SetParameterAttributesResponse *const*, const char *);
SOAP_FMAC3 struct cwmp__SetParameterAttributesResponse ** SOAP_FMAC4 soap_get_PointerTocwmp__SetParameterAttributesResponse(struct soap*, struct cwmp__SetParameterAttributesResponse **, const char*, const char*);
SOAP_FMAC3 struct cwmp__SetParameterAttributesResponse ** SOAP_FMAC4 soap_in_PointerTocwmp__SetParameterAttributesResponse(struct soap*, const char*, struct cwmp__SetParameterAttributesResponse **, const char*);

#ifndef SOAP_TYPE_PointerToParameterList_Attributes
#define SOAP_TYPE_PointerToParameterList_Attributes (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterList_Attributes(struct soap*, struct ParameterList_Attributes *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterList_Attributes(struct soap*, struct ParameterList_Attributes *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterList_Attributes(struct soap*, const char *, int, struct ParameterList_Attributes *const*, const char *);
SOAP_FMAC3 struct ParameterList_Attributes ** SOAP_FMAC4 soap_get_PointerToParameterList_Attributes(struct soap*, struct ParameterList_Attributes **, const char*, const char*);
SOAP_FMAC3 struct ParameterList_Attributes ** SOAP_FMAC4 soap_in_PointerToParameterList_Attributes(struct soap*, const char*, struct ParameterList_Attributes **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__unsignedInt
#define SOAP_TYPE_PointerToxsd__unsignedInt (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__unsignedInt(struct soap*, unsigned int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__unsignedInt(struct soap*, unsigned int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__unsignedInt(struct soap*, const char *, int, unsigned int *const*, const char *);
SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_get_PointerToxsd__unsignedInt(struct soap*, unsigned int **, const char*, const char*);
SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_in_PointerToxsd__unsignedInt(struct soap*, const char*, unsigned int **, const char*);

#ifndef SOAP_TYPE_PointerToParameterList_Name
#define SOAP_TYPE_PointerToParameterList_Name (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterList_Name(struct soap*, struct ParameterList_Name *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterList_Name(struct soap*, struct ParameterList_Name *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterList_Name(struct soap*, const char *, int, struct ParameterList_Name *const*, const char *);
SOAP_FMAC3 struct ParameterList_Name ** SOAP_FMAC4 soap_get_PointerToParameterList_Name(struct soap*, struct ParameterList_Name **, const char*, const char*);
SOAP_FMAC3 struct ParameterList_Name ** SOAP_FMAC4 soap_in_PointerToParameterList_Name(struct soap*, const char*, struct ParameterList_Name **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfstring
#define SOAP_TYPE_PointerToArrayOfstring (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfstring(struct soap*, struct ArrayOfstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfstring(struct soap*, struct ArrayOfstring *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfstring(struct soap*, const char *, int, struct ArrayOfstring *const*, const char *);
SOAP_FMAC3 struct ArrayOfstring ** SOAP_FMAC4 soap_get_PointerToArrayOfstring(struct soap*, struct ArrayOfstring **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfstring ** SOAP_FMAC4 soap_in_PointerToArrayOfstring(struct soap*, const char*, struct ArrayOfstring **, const char*);

#ifndef SOAP_TYPE_PointerTocwmp__InformResponse
#define SOAP_TYPE_PointerTocwmp__InformResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocwmp__InformResponse(struct soap*, struct cwmp__InformResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocwmp__InformResponse(struct soap*, struct cwmp__InformResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocwmp__InformResponse(struct soap*, const char *, int, struct cwmp__InformResponse *const*, const char *);
SOAP_FMAC3 struct cwmp__InformResponse ** SOAP_FMAC4 soap_get_PointerTocwmp__InformResponse(struct soap*, struct cwmp__InformResponse **, const char*, const char*);
SOAP_FMAC3 struct cwmp__InformResponse ** SOAP_FMAC4 soap_in_PointerTocwmp__InformResponse(struct soap*, const char*, struct cwmp__InformResponse **, const char*);

#ifndef SOAP_TYPE_PointerToParameterList_Value
#define SOAP_TYPE_PointerToParameterList_Value (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterList_Value(struct soap*, struct ParameterList_Value *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterList_Value(struct soap*, struct ParameterList_Value *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterList_Value(struct soap*, const char *, int, struct ParameterList_Value *const*, const char *);
SOAP_FMAC3 struct ParameterList_Value ** SOAP_FMAC4 soap_get_PointerToParameterList_Value(struct soap*, struct ParameterList_Value **, const char*, const char*);
SOAP_FMAC3 struct ParameterList_Value ** SOAP_FMAC4 soap_in_PointerToParameterList_Value(struct soap*, const char*, struct ParameterList_Value **, const char*);

#ifndef SOAP_TYPE_PointerToEventArray
#define SOAP_TYPE_PointerToEventArray (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToEventArray(struct soap*, struct EventArray *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToEventArray(struct soap*, struct EventArray *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToEventArray(struct soap*, const char *, int, struct EventArray *const*, const char *);
SOAP_FMAC3 struct EventArray ** SOAP_FMAC4 soap_get_PointerToEventArray(struct soap*, struct EventArray **, const char*, const char*);
SOAP_FMAC3 struct EventArray ** SOAP_FMAC4 soap_in_PointerToEventArray(struct soap*, const char*, struct EventArray **, const char*);

#ifndef SOAP_TYPE_PointerToDeviceIdStruct
#define SOAP_TYPE_PointerToDeviceIdStruct (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToDeviceIdStruct(struct soap*, struct DeviceIdStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToDeviceIdStruct(struct soap*, struct DeviceIdStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToDeviceIdStruct(struct soap*, const char *, int, struct DeviceIdStruct *const*, const char *);
SOAP_FMAC3 struct DeviceIdStruct ** SOAP_FMAC4 soap_get_PointerToDeviceIdStruct(struct soap*, struct DeviceIdStruct **, const char*, const char*);
SOAP_FMAC3 struct DeviceIdStruct ** SOAP_FMAC4 soap_in_PointerToDeviceIdStruct(struct soap*, const char*, struct DeviceIdStruct **, const char*);

#ifndef SOAP_TYPE_PointerToParameterAttributeStruct
#define SOAP_TYPE_PointerToParameterAttributeStruct (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterAttributeStruct(struct soap*, struct ParameterAttributeStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterAttributeStruct(struct soap*, struct ParameterAttributeStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterAttributeStruct(struct soap*, const char *, int, struct ParameterAttributeStruct *const*, const char *);
SOAP_FMAC3 struct ParameterAttributeStruct ** SOAP_FMAC4 soap_get_PointerToParameterAttributeStruct(struct soap*, struct ParameterAttributeStruct **, const char*, const char*);
SOAP_FMAC3 struct ParameterAttributeStruct ** SOAP_FMAC4 soap_in_PointerToParameterAttributeStruct(struct soap*, const char*, struct ParameterAttributeStruct **, const char*);

#ifndef SOAP_TYPE_PointerToSetParameterAttributesStruct
#define SOAP_TYPE_PointerToSetParameterAttributesStruct (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSetParameterAttributesStruct(struct soap*, struct SetParameterAttributesStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSetParameterAttributesStruct(struct soap*, struct SetParameterAttributesStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSetParameterAttributesStruct(struct soap*, const char *, int, struct SetParameterAttributesStruct *const*, const char *);
SOAP_FMAC3 struct SetParameterAttributesStruct ** SOAP_FMAC4 soap_get_PointerToSetParameterAttributesStruct(struct soap*, struct SetParameterAttributesStruct **, const char*, const char*);
SOAP_FMAC3 struct SetParameterAttributesStruct ** SOAP_FMAC4 soap_in_PointerToSetParameterAttributesStruct(struct soap*, const char*, struct SetParameterAttributesStruct **, const char*);

#ifndef SOAP_TYPE_PointerToParameterInfoStruct
#define SOAP_TYPE_PointerToParameterInfoStruct (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterInfoStruct(struct soap*, struct ParameterInfoStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterInfoStruct(struct soap*, struct ParameterInfoStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterInfoStruct(struct soap*, const char *, int, struct ParameterInfoStruct *const*, const char *);
SOAP_FMAC3 struct ParameterInfoStruct ** SOAP_FMAC4 soap_get_PointerToParameterInfoStruct(struct soap*, struct ParameterInfoStruct **, const char*, const char*);
SOAP_FMAC3 struct ParameterInfoStruct ** SOAP_FMAC4 soap_in_PointerToParameterInfoStruct(struct soap*, const char*, struct ParameterInfoStruct **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__string(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerToParameterValueStruct
#define SOAP_TYPE_PointerToParameterValueStruct (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToParameterValueStruct(struct soap*, struct ParameterValueStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToParameterValueStruct(struct soap*, struct ParameterValueStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToParameterValueStruct(struct soap*, const char *, int, struct ParameterValueStruct *const*, const char *);
SOAP_FMAC3 struct ParameterValueStruct ** SOAP_FMAC4 soap_get_PointerToParameterValueStruct(struct soap*, struct ParameterValueStruct **, const char*, const char*);
SOAP_FMAC3 struct ParameterValueStruct ** SOAP_FMAC4 soap_in_PointerToParameterValueStruct(struct soap*, const char*, struct ParameterValueStruct **, const char*);

#ifndef SOAP_TYPE_PointerToEventStruct
#define SOAP_TYPE_PointerToEventStruct (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToEventStruct(struct soap*, struct EventStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToEventStruct(struct soap*, struct EventStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToEventStruct(struct soap*, const char *, int, struct EventStruct *const*, const char *);
SOAP_FMAC3 struct EventStruct ** SOAP_FMAC4 soap_get_PointerToEventStruct(struct soap*, struct EventStruct **, const char*, const char*);
SOAP_FMAC3 struct EventStruct ** SOAP_FMAC4 soap_in_PointerToEventStruct(struct soap*, const char*, struct EventStruct **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef _JPR_AM_
#ifndef SOAP_TYPE_cwmp__Upload
#define SOAP_TYPE_cwmp__Upload (161)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__Upload(struct soap*, const struct cwmp__Upload *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__Upload(struct soap*, struct cwmp__Upload *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__Upload(struct soap*, const struct cwmp__Upload *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__Upload(struct soap*, const char*, int, const struct cwmp__Upload *, const char*);
SOAP_FMAC3 struct cwmp__Upload * SOAP_FMAC4 soap_get_cwmp__Upload(struct soap*, struct cwmp__Upload *, const char*, const char*);
SOAP_FMAC3 struct cwmp__Upload * SOAP_FMAC4 soap_in_cwmp__Upload(struct soap*, const char*, struct cwmp__Upload *, const char*);

#ifndef SOAP_TYPE_cwmp__UploadResponse
#define SOAP_TYPE_cwmp__UploadResponse (158)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cwmp__UploadResponse(struct soap*, struct UploadResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cwmp__UploadResponse(struct soap*, struct UploadResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_cwmp__UploadResponse(struct soap*, const struct UploadResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cwmp__UploadResponse(struct soap*, const char*, int, const struct UploadResponse *, const char*);
SOAP_FMAC3 struct UploadResponse * SOAP_FMAC4 soap_get_cwmp__UploadResponse(struct soap*, struct UploadResponse *, const char*, const char*);
SOAP_FMAC3 struct UploadResponse * SOAP_FMAC4 soap_in_cwmp__UploadResponse(struct soap*, const char*, struct UploadResponse *, const char*);

#ifndef SOAP_TYPE_UploadResponse
#define SOAP_TYPE_UploadResponse (157)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_UploadResponse(struct soap*, const struct UploadResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_UploadResponse(struct soap*, struct UploadResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_UploadResponse(struct soap*, const struct UploadResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_UploadResponse(struct soap*, const char*, int, const struct UploadResponse *, const char*);
SOAP_FMAC3 struct UploadResponse * SOAP_FMAC4 soap_get_UploadResponse(struct soap*, struct UploadResponse *, const char*, const char*);
SOAP_FMAC3 struct UploadResponse * SOAP_FMAC4 soap_in_UploadResponse(struct soap*, const char*, struct UploadResponse *, const char*);

#ifndef SOAP_TYPE_PointerTocwmp__UploadResponse
#define SOAP_TYPE_PointerTocwmp__UploadResponse (159)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocwmp__UploadResponse(struct soap*, struct UploadResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocwmp__UploadResponse(struct soap*, struct UploadResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocwmp__UploadResponse(struct soap*, const char *, int, struct UploadResponse *const*, const char *);
SOAP_FMAC3 struct UploadResponse ** SOAP_FMAC4 soap_get_PointerTocwmp__UploadResponse(struct soap*, struct UploadResponse **, const char*, const char*);
SOAP_FMAC3 struct UploadResponse ** SOAP_FMAC4 soap_in_PointerTocwmp__UploadResponse(struct soap*, const char*, struct UploadResponse **, const char*);
#endif

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
