/* soapServer.c
   Generated by gSOAP 2.7.9k from tr069.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.7.9k 2009-09-01 06:24:54 GMT")

extern char MGT_SERVER_URL[];

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	
#ifdef _JPR_AM_		
			if ( soap->error == SOAP_NO_DATA && soap->length == 0 ){
				soap_closesock(soap);
				break;
			}
#endif
			if (soap->error < SOAP_STOP)
			{
				if (soap->error != 204)
#ifdef WITH_FASTCGI
					soap_send_fault(soap);
#else 
					return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
			if (soap->error != 204)
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else
				return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Inform"))
		return soap_serve_cwmp__Inform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetRPCMethods"))
		return soap_serve_cwmp__GetRPCMethods(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterNames"))
		return soap_serve_cwmp__GetParameterNames(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterValues"))
		return soap_serve_cwmp__SetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterValues"))
		return soap_serve_cwmp__GetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterAttributes"))
		return soap_serve_cwmp__SetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterAttributes"))
		return soap_serve_cwmp__GetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Download"))
		return soap_serve_cwmp__Download(soap);
#ifdef _JPR_AM_
	if (!soap_match_tag(soap, soap->tag, "cwmp:Upload"))
		return soap_serve_cwmp__Upload(soap);
#endif
	if (!soap_match_tag(soap, soap->tag, "cwmp:TransferComplete"))
		return soap_serve_cwmp__TransferComplete(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:AddObject"))
		return soap_serve_cwmp__AddObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:DeleteObject"))
		return soap_serve_cwmp__DeleteObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:FactoryReset"))
		return soap_serve_cwmp__FactoryReset(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Reboot"))
		return soap_serve_cwmp__Reboot(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Inform(struct soap *soap)
{	struct cwmp__Inform soap_tmp_cwmp__Inform;
	struct cwmp__InformResponse result;
	soap_default_cwmp__InformResponse(soap, &result);
	soap_default_cwmp__Inform(soap, &soap_tmp_cwmp__Inform);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__Inform(soap, &soap_tmp_cwmp__Inform, "cwmp:Inform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Inform(soap, soap_tmp_cwmp__Inform.DeviceId, soap_tmp_cwmp__Inform.Event, soap_tmp_cwmp__Inform.MaxEnvelopes, soap_tmp_cwmp__Inform.CurrentTime, soap_tmp_cwmp__Inform.RetryCount, soap_tmp_cwmp__Inform.ParameterList, &result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__InformResponse(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__InformResponse(soap, &result, "cwmp:InformResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__InformResponse(soap, &result, "cwmp:InformResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetRPCMethods(struct soap *soap)
{	struct cwmp__GetRPCMethods soap_tmp_cwmp__GetRPCMethods;
	struct cwmp__GetRPCMethodsResponse soap_tmp_cwmp__GetRPCMethodsResponse;
	struct ArrayOfstring soap_tmp_ArrayOfstring;
	soap_default_cwmp__GetRPCMethodsResponse(soap, &soap_tmp_cwmp__GetRPCMethodsResponse);
	soap_default_ArrayOfstring(soap, &soap_tmp_ArrayOfstring);
	soap_tmp_cwmp__GetRPCMethodsResponse.MethodList = &soap_tmp_ArrayOfstring;
	soap_default_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods, "cwmp:GetRPCMethods", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetRPCMethods(soap, soap_tmp_cwmp__GetRPCMethods._, &soap_tmp_ArrayOfstring);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetRPCMethodsResponse(soap, &soap_tmp_cwmp__GetRPCMethodsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetRPCMethodsResponse(soap, &soap_tmp_cwmp__GetRPCMethodsResponse, "cwmp:GetRPCMethodsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetRPCMethodsResponse(soap, &soap_tmp_cwmp__GetRPCMethodsResponse, "cwmp:GetRPCMethodsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterNames(struct soap *soap)
{	struct cwmp__GetParameterNames soap_tmp_cwmp__GetParameterNames;
	struct cwmp__GetParameterNamesResponse soap_tmp_cwmp__GetParameterNamesResponse;
	struct ParameterList_Name soap_tmp_ParameterList_Name;
	soap_default_cwmp__GetParameterNamesResponse(soap, &soap_tmp_cwmp__GetParameterNamesResponse);
	soap_default_ParameterList_Name(soap, &soap_tmp_ParameterList_Name);
	soap_tmp_cwmp__GetParameterNamesResponse.ParameterList = &soap_tmp_ParameterList_Name;
	soap_default_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames, "cwmp:GetParameterNames", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetParameterNames(soap, soap_tmp_cwmp__GetParameterNames.ParameterPath, soap_tmp_cwmp__GetParameterNames.NextLevel, &soap_tmp_ParameterList_Name);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterNamesResponse(soap, &soap_tmp_cwmp__GetParameterNamesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterNamesResponse(soap, &soap_tmp_cwmp__GetParameterNamesResponse, "cwmp:GetParameterNamesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterNamesResponse(soap, &soap_tmp_cwmp__GetParameterNamesResponse, "cwmp:GetParameterNamesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterValues(struct soap *soap)
{	struct cwmp__SetParameterValues soap_tmp_cwmp__SetParameterValues;
	struct cwmp__SetParameterValuesResponse soap_tmp_cwmp__SetParameterValuesResponse;
	unsigned int soap_tmp_xsd__unsignedInt;
	soap_default_cwmp__SetParameterValuesResponse(soap, &soap_tmp_cwmp__SetParameterValuesResponse);
	soap_default_xsd__unsignedInt(soap, &soap_tmp_xsd__unsignedInt);
	soap_tmp_cwmp__SetParameterValuesResponse.Status = &soap_tmp_xsd__unsignedInt;
	soap_default_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues, "cwmp:SetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__SetParameterValues(soap, soap_tmp_cwmp__SetParameterValues.ParameterList, soap_tmp_cwmp__SetParameterValues.ParameterKey, &soap_tmp_xsd__unsignedInt);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__SetParameterValuesResponse(soap, &soap_tmp_cwmp__SetParameterValuesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__SetParameterValuesResponse(soap, &soap_tmp_cwmp__SetParameterValuesResponse, "cwmp:SetParameterValuesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__SetParameterValuesResponse(soap, &soap_tmp_cwmp__SetParameterValuesResponse, "cwmp:SetParameterValuesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterValues(struct soap *soap)
{	struct cwmp__GetParameterValues soap_tmp_cwmp__GetParameterValues;
	struct cwmp__GetParameterValuesResponse soap_tmp_cwmp__GetParameterValuesResponse;
	struct ParameterList_Value soap_tmp_ParameterList_Value;
	soap_default_cwmp__GetParameterValuesResponse(soap, &soap_tmp_cwmp__GetParameterValuesResponse);
	soap_default_ParameterList_Value(soap, &soap_tmp_ParameterList_Value);
	soap_tmp_cwmp__GetParameterValuesResponse.ParameterList = &soap_tmp_ParameterList_Value;
	soap_default_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues, "cwmp:GetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetParameterValues(soap, soap_tmp_cwmp__GetParameterValues.ParameterNames, &soap_tmp_ParameterList_Value);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterValuesResponse(soap, &soap_tmp_cwmp__GetParameterValuesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterValuesResponse(soap, &soap_tmp_cwmp__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterValuesResponse(soap, &soap_tmp_cwmp__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterAttributes(struct soap *soap)
{	struct cwmp__SetParameterAttributes soap_tmp_cwmp__SetParameterAttributes;
	struct cwmp__SetParameterAttributesResponse out;
	soap_default_cwmp__SetParameterAttributesResponse(soap, &out);
	soap_default_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes, "cwmp:SetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__SetParameterAttributes(soap, soap_tmp_cwmp__SetParameterAttributes.ParameterList, &out);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__SetParameterAttributesResponse(soap, &out);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__SetParameterAttributesResponse(soap, &out, "cwmp:SetParameterAttributesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__SetParameterAttributesResponse(soap, &out, "cwmp:SetParameterAttributesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterAttributes(struct soap *soap)
{	struct cwmp__GetParameterAttributes soap_tmp_cwmp__GetParameterAttributes;
	struct cwmp__GetParameterAttributesResponse soap_tmp_cwmp__GetParameterAttributesResponse;
	struct ParameterList_GetAttributes soap_tmp_ParameterList_GetAttributes;
	soap_default_cwmp__GetParameterAttributesResponse(soap, &soap_tmp_cwmp__GetParameterAttributesResponse);
	soap_default_ParameterList_GetAttributes(soap, &soap_tmp_ParameterList_GetAttributes);
	soap_tmp_cwmp__GetParameterAttributesResponse.ParameterList = &soap_tmp_ParameterList_GetAttributes;
	soap_default_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes, "cwmp:GetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetParameterAttributes(soap, soap_tmp_cwmp__GetParameterAttributes.ParameterNames, &soap_tmp_ParameterList_GetAttributes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterAttributesResponse(soap, &soap_tmp_cwmp__GetParameterAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterAttributesResponse(soap, &soap_tmp_cwmp__GetParameterAttributesResponse, "cwmp:GetParameterAttributesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterAttributesResponse(soap, &soap_tmp_cwmp__GetParameterAttributesResponse, "cwmp:GetParameterAttributesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Download(struct soap *soap)
{	struct cwmp__Download soap_tmp_cwmp__Download;
	struct cwmp__DownloadResponse result;
	soap_default_cwmp__DownloadResponse(soap, &result);
	soap_default_cwmp__Download(soap, &soap_tmp_cwmp__Download);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__Download(soap, &soap_tmp_cwmp__Download, "cwmp:Download", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Download(soap, soap_tmp_cwmp__Download.CommandKey, soap_tmp_cwmp__Download.FileType, soap_tmp_cwmp__Download.URL, soap_tmp_cwmp__Download.Username, soap_tmp_cwmp__Download.Password, soap_tmp_cwmp__Download.FileSize, soap_tmp_cwmp__Download.TargetFileName, soap_tmp_cwmp__Download.DelaySeconds, soap_tmp_cwmp__Download.SuccessURL, soap_tmp_cwmp__Download.FailureURL, &result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__DownloadResponse(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__DownloadResponse(soap, &result, "cwmp:DownloadResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__DownloadResponse(soap, &result, "cwmp:DownloadResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
#ifdef _JPR_AM_
	soap->keep_alive = 0;
#endif
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__TransferComplete(struct soap *soap)
{	struct cwmp__TransferComplete soap_tmp_cwmp__TransferComplete;
	struct cwmp__TransferCompleteResponse out;
	soap_default_cwmp__TransferCompleteResponse(soap, &out);
	soap_default_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete, "cwmp:TransferComplete", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__TransferComplete(soap, soap_tmp_cwmp__TransferComplete.CommandKey, soap_tmp_cwmp__TransferComplete.FaultStruct, soap_tmp_cwmp__TransferComplete.StartTime, soap_tmp_cwmp__TransferComplete.CompleteTime, &out);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__TransferCompleteResponse(soap, &out);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__TransferCompleteResponse(soap, &out, "cwmp:TransferCompleteResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__TransferCompleteResponse(soap, &out, "cwmp:TransferCompleteResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__AddObject(struct soap *soap)
{	struct cwmp__AddObject soap_tmp_cwmp__AddObject;
	struct cwmp__AddObjectResponse result;
	soap_default_cwmp__AddObjectResponse(soap, &result);
	soap_default_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject, "cwmp:AddObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__AddObject(soap, soap_tmp_cwmp__AddObject.ObjectName, soap_tmp_cwmp__AddObject.ParameterKey, &result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__AddObjectResponse(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__AddObjectResponse(soap, &result, "cwmp:AddObjectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__AddObjectResponse(soap, &result, "cwmp:AddObjectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__DeleteObject(struct soap *soap)
{	struct cwmp__DeleteObject soap_tmp_cwmp__DeleteObject;
	struct cwmp__DeleteObjectResponse soap_tmp_cwmp__DeleteObjectResponse;
	int soap_tmp_xsd__int;
	soap_default_cwmp__DeleteObjectResponse(soap, &soap_tmp_cwmp__DeleteObjectResponse);
	soap_default_xsd__int(soap, &soap_tmp_xsd__int);
	soap_tmp_cwmp__DeleteObjectResponse.Status = &soap_tmp_xsd__int;
	soap_default_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject, "cwmp:DeleteObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__DeleteObject(soap, soap_tmp_cwmp__DeleteObject.ObjectName, soap_tmp_cwmp__DeleteObject.ParameterKey, &soap_tmp_xsd__int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__DeleteObjectResponse(soap, &soap_tmp_cwmp__DeleteObjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__DeleteObjectResponse(soap, &soap_tmp_cwmp__DeleteObjectResponse, "cwmp:DeleteObjectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__DeleteObjectResponse(soap, &soap_tmp_cwmp__DeleteObjectResponse, "cwmp:DeleteObjectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__FactoryReset(struct soap *soap)
{	struct cwmp__FactoryReset soap_tmp_cwmp__FactoryReset;
	struct FactoryResetResponse out;
	soap_default_FactoryResetResponse(soap, &out);
	soap_default_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset, "cwmp:FactoryReset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__FactoryReset(soap, soap_tmp_cwmp__FactoryReset._, &out);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_FactoryResetResponse(soap, &out);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_FactoryResetResponse(soap, &out, "FactoryResetResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_FactoryResetResponse(soap, &out, "FactoryResetResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Reboot(struct soap *soap)
{	struct cwmp__Reboot soap_tmp_cwmp__Reboot;
	struct RebootResponse out;
	soap_default_RebootResponse(soap, &out);
	soap_default_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot, "cwmp:Reboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Reboot(soap, soap_tmp_cwmp__Reboot.CommandKey, &out);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_RebootResponse(soap, &out);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_RebootResponse(soap, &out, "RebootResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_RebootResponse(soap, &out, "RebootResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef _JPR_AM_
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Upload(struct soap *soap)
{	struct cwmp__Upload soap_tmp_cwmp__Upload;
	struct UploadResponse response;
	soap_default_cwmp__UploadResponse(soap, &response);
	soap_default_cwmp__Upload(soap, &soap_tmp_cwmp__Upload);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__Upload(soap, &soap_tmp_cwmp__Upload, "cwmp:Upload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Upload(soap, soap_tmp_cwmp__Upload.CommandKey, soap_tmp_cwmp__Upload.FileType, soap_tmp_cwmp__Upload.URL, soap_tmp_cwmp__Upload.Username, soap_tmp_cwmp__Upload.Password, soap_tmp_cwmp__Upload.DelaySeconds, &response);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__UploadResponse(soap, &response);
	if (soap_begin_count(soap))
		return soap->error;

	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__UploadResponse(soap, &response, "cwmp:UploadResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_connect(soap, MGT_SERVER_URL, "")
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__UploadResponse(soap, &response, "cwmp:UploadResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
//#ifdef _JPR_AM_
	soap->keep_alive = 0;
//#endif
	return soap_closesock(soap);
}
#endif

#ifdef __cplusplus
}
#endif

/* End of soapServer.c */
