/* soapClient.c
   Generated by gSOAP 2.7.9k from tr069.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.9k 2009-09-01 06:24:54 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct DeviceIdStruct *DeviceId, struct EventArray *Event, unsigned int MaxEnvelopes, char *CurrentTime, unsigned int RetryCount, struct ParameterList_Value *ParameterList, struct cwmp__InformResponse *result)
{	struct cwmp__Inform soap_tmp_cwmp__Inform;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__Inform.DeviceId = DeviceId;
	soap_tmp_cwmp__Inform.Event = Event;
	soap_tmp_cwmp__Inform.MaxEnvelopes = MaxEnvelopes;
	soap_tmp_cwmp__Inform.CurrentTime = CurrentTime;
	soap_tmp_cwmp__Inform.RetryCount = RetryCount;
	soap_tmp_cwmp__Inform.ParameterList = ParameterList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__Inform(soap, &soap_tmp_cwmp__Inform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__Inform(soap, &soap_tmp_cwmp__Inform, "cwmp:Inform", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__Inform(soap, &soap_tmp_cwmp__Inform, "cwmp:Inform", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_cwmp__InformResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_cwmp__InformResponse(soap, result, "cwmp:InformResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct ArrayOfstring *MethodList)
{	struct cwmp__GetRPCMethods soap_tmp_cwmp__GetRPCMethods;
	struct cwmp__GetRPCMethodsResponse *soap_tmp_cwmp__GetRPCMethodsResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__GetRPCMethods._ = _;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods, "cwmp:GetRPCMethods", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods, "cwmp:GetRPCMethods", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ArrayOfstring(soap, MethodList);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_cwmp__GetRPCMethodsResponse = soap_get_cwmp__GetRPCMethodsResponse(soap, NULL, "cwmp:GetRPCMethodsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (MethodList && soap_tmp_cwmp__GetRPCMethodsResponse->MethodList)
		*MethodList = *soap_tmp_cwmp__GetRPCMethodsResponse->MethodList;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ParameterPath, enum _Enum_1 NextLevel, struct ParameterList_Name *ParameterList)
{	struct cwmp__GetParameterNames soap_tmp_cwmp__GetParameterNames;
	struct cwmp__GetParameterNamesResponse *soap_tmp_cwmp__GetParameterNamesResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__GetParameterNames.ParameterPath = ParameterPath;
	soap_tmp_cwmp__GetParameterNames.NextLevel = NextLevel;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames, "cwmp:GetParameterNames", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames, "cwmp:GetParameterNames", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ParameterList_Name(soap, ParameterList);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_cwmp__GetParameterNamesResponse = soap_get_cwmp__GetParameterNamesResponse(soap, NULL, "cwmp:GetParameterNamesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ParameterList && soap_tmp_cwmp__GetParameterNamesResponse->ParameterList)
		*ParameterList = *soap_tmp_cwmp__GetParameterNamesResponse->ParameterList;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ParameterList_Value *ParameterList, char *ParameterKey, unsigned int *Status)
{	struct cwmp__SetParameterValues soap_tmp_cwmp__SetParameterValues;
	struct cwmp__SetParameterValuesResponse *soap_tmp_cwmp__SetParameterValuesResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__SetParameterValues.ParameterList = ParameterList;
	soap_tmp_cwmp__SetParameterValues.ParameterKey = ParameterKey;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues, "cwmp:SetParameterValues", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues, "cwmp:SetParameterValues", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_xsd__unsignedInt(soap, Status);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_cwmp__SetParameterValuesResponse = soap_get_cwmp__SetParameterValuesResponse(soap, NULL, "cwmp:SetParameterValuesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (Status && soap_tmp_cwmp__SetParameterValuesResponse->Status)
		*Status = *soap_tmp_cwmp__SetParameterValuesResponse->Status;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ArrayOfstring *ParameterNames, struct ParameterList_Value *ParameterList)
{	struct cwmp__GetParameterValues soap_tmp_cwmp__GetParameterValues;
	struct cwmp__GetParameterValuesResponse *soap_tmp_cwmp__GetParameterValuesResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__GetParameterValues.ParameterNames = ParameterNames;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues, "cwmp:GetParameterValues", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues, "cwmp:GetParameterValues", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ParameterList_Value(soap, ParameterList);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_cwmp__GetParameterValuesResponse = soap_get_cwmp__GetParameterValuesResponse(soap, NULL, "cwmp:GetParameterValuesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ParameterList && soap_tmp_cwmp__GetParameterValuesResponse->ParameterList)
		*ParameterList = *soap_tmp_cwmp__GetParameterValuesResponse->ParameterList;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ParameterList_Attributes *ParameterList, struct cwmp__SetParameterAttributesResponse *out)
{	struct cwmp__SetParameterAttributes soap_tmp_cwmp__SetParameterAttributes;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__SetParameterAttributes.ParameterList = ParameterList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes, "cwmp:SetParameterAttributes", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes, "cwmp:SetParameterAttributes", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_cwmp__SetParameterAttributesResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_cwmp__SetParameterAttributesResponse(soap, out, "cwmp:SetParameterAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ArrayOfstring *ParameterNames, struct ParameterList_GetAttributes *ParameterList)
{	struct cwmp__GetParameterAttributes soap_tmp_cwmp__GetParameterAttributes;
	struct cwmp__GetParameterAttributesResponse *soap_tmp_cwmp__GetParameterAttributesResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__GetParameterAttributes.ParameterNames = ParameterNames;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes, "cwmp:GetParameterAttributes", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes, "cwmp:GetParameterAttributes", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ParameterList_GetAttributes(soap, ParameterList);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_cwmp__GetParameterAttributesResponse = soap_get_cwmp__GetParameterAttributesResponse(soap, NULL, "cwmp:GetParameterAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ParameterList && soap_tmp_cwmp__GetParameterAttributesResponse->ParameterList)
		*ParameterList = *soap_tmp_cwmp__GetParameterAttributesResponse->ParameterList;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *CommandKey, char *FileType, char *URL, char *Username, char *Password, unsigned int FileSize, char *TargetFileName, unsigned int DelaySeconds, char *SuccessURL, char *FailureURL, struct cwmp__DownloadResponse *result)
{	struct cwmp__Download soap_tmp_cwmp__Download;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__Download.CommandKey = CommandKey;
	soap_tmp_cwmp__Download.FileType = FileType;
	soap_tmp_cwmp__Download.URL = URL;
	soap_tmp_cwmp__Download.Username = Username;
	soap_tmp_cwmp__Download.Password = Password;
	soap_tmp_cwmp__Download.FileSize = FileSize;
	soap_tmp_cwmp__Download.TargetFileName = TargetFileName;
	soap_tmp_cwmp__Download.DelaySeconds = DelaySeconds;
	soap_tmp_cwmp__Download.SuccessURL = SuccessURL;
	soap_tmp_cwmp__Download.FailureURL = FailureURL;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__Download(soap, &soap_tmp_cwmp__Download);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__Download(soap, &soap_tmp_cwmp__Download, "cwmp:Download", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__Download(soap, &soap_tmp_cwmp__Download, "cwmp:Download", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_cwmp__DownloadResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_cwmp__DownloadResponse(soap, result, "cwmp:DownloadResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *CommandKey, struct cwmp__FaultStruct *FaultStruct, char *StartTime, char *CompleteTime, struct cwmp__TransferCompleteResponse *out)
{	struct cwmp__TransferComplete soap_tmp_cwmp__TransferComplete;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__TransferComplete.CommandKey = CommandKey;
	soap_tmp_cwmp__TransferComplete.FaultStruct = FaultStruct;
	soap_tmp_cwmp__TransferComplete.StartTime = StartTime;
	soap_tmp_cwmp__TransferComplete.CompleteTime = CompleteTime;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete, "cwmp:TransferComplete", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete, "cwmp:TransferComplete", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_cwmp__TransferCompleteResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_cwmp__TransferCompleteResponse(soap, out, "cwmp:TransferCompleteResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ObjectName, char *ParameterKey, struct cwmp__AddObjectResponse *result)
{	struct cwmp__AddObject soap_tmp_cwmp__AddObject;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__AddObject.ObjectName = ObjectName;
	soap_tmp_cwmp__AddObject.ParameterKey = ParameterKey;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject, "cwmp:AddObject", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject, "cwmp:AddObject", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_cwmp__AddObjectResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_cwmp__AddObjectResponse(soap, result, "cwmp:AddObjectResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ObjectName, char *ParameterKey, int *Status)
{	struct cwmp__DeleteObject soap_tmp_cwmp__DeleteObject;
	struct cwmp__DeleteObjectResponse *soap_tmp_cwmp__DeleteObjectResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__DeleteObject.ObjectName = ObjectName;
	soap_tmp_cwmp__DeleteObject.ParameterKey = ParameterKey;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject, "cwmp:DeleteObject", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject, "cwmp:DeleteObject", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_xsd__int(soap, Status);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_cwmp__DeleteObjectResponse = soap_get_cwmp__DeleteObjectResponse(soap, NULL, "cwmp:DeleteObjectResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (Status && soap_tmp_cwmp__DeleteObjectResponse->Status)
		*Status = *soap_tmp_cwmp__DeleteObjectResponse->Status;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct FactoryResetResponse *out)
{	struct cwmp__FactoryReset soap_tmp_cwmp__FactoryReset;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__FactoryReset._ = _;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset, "cwmp:FactoryReset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset, "cwmp:FactoryReset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_FactoryResetResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_FactoryResetResponse(soap, out, "FactoryResetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *CommandKey, struct RebootResponse *out)
{	struct cwmp__Reboot soap_tmp_cwmp__Reboot;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = "";
	soap_tmp_cwmp__Reboot.CommandKey = CommandKey;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot, "cwmp:Reboot", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot, "cwmp:Reboot", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_RebootResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_RebootResponse(soap, out, "RebootResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef _JPR_AM_
SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *CommandKey, char *FileType, char *URL, char *Username, char *Password, unsigned int DelaySeconds, struct UploadResponse *response)
{	struct cwmp__Upload soap_tmp_cwmp__Upload;
	soap->encodingStyle = "";
	soap_tmp_cwmp__Upload.CommandKey = CommandKey;
	soap_tmp_cwmp__Upload.FileType = FileType;
	soap_tmp_cwmp__Upload.URL = URL;
	soap_tmp_cwmp__Upload.Username = Username;
	soap_tmp_cwmp__Upload.Password = Password;
	soap_tmp_cwmp__Upload.DelaySeconds = DelaySeconds;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_cwmp__Upload(soap, &soap_tmp_cwmp__Upload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__Upload(soap, &soap_tmp_cwmp__Upload, "cwmp:Upload", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__Upload(soap, &soap_tmp_cwmp__Upload, "cwmp:Upload", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_cwmp__UploadResponse(soap, response);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_cwmp__UploadResponse(soap, response, "cwmp:UploadResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
